# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class BeneficioMunicipal(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tp_bm': 'int',
        'n_bm': 'str',
        'v_red_bcbm': 'float',
        'p_red_bcbm': 'float'
    }

    attribute_map = {
        'tp_bm': 'tpBM',
        'n_bm': 'nBM',
        'v_red_bcbm': 'vRedBCBM',
        'p_red_bcbm': 'pRedBCBM'
    }

    def __init__(self, tp_bm=None, n_bm=None, v_red_bcbm=None, p_red_bcbm=None, local_vars_configuration=None):  # noqa: E501
        """BeneficioMunicipal - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._tp_bm = None
        self._n_bm = None
        self._v_red_bcbm = None
        self._p_red_bcbm = None
        self.discriminator = None

        self.tp_bm = tp_bm
        self.n_bm = n_bm
        self.v_red_bcbm = v_red_bcbm
        self.p_red_bcbm = p_red_bcbm

    @property
    def tp_bm(self):
        """Gets the tp_bm of this BeneficioMunicipal.  # noqa: E501

        Tipo do Benefício Municipal:  * 1 - Alíquota Diferenciada  * 2 - Redução da BC  * 3 - Isenção    **Atenção**: Para emissões pelo Sistema Nacional NFS-e, esse campo é ignorado.  # noqa: E501

        :return: The tp_bm of this BeneficioMunicipal.  # noqa: E501
        :rtype: int
        """
        return self._tp_bm

    @tp_bm.setter
    def tp_bm(self, tp_bm):
        """Sets the tp_bm of this BeneficioMunicipal.

        Tipo do Benefício Municipal:  * 1 - Alíquota Diferenciada  * 2 - Redução da BC  * 3 - Isenção    **Atenção**: Para emissões pelo Sistema Nacional NFS-e, esse campo é ignorado.  # noqa: E501

        :param tp_bm: The tp_bm of this BeneficioMunicipal.  # noqa: E501
        :type tp_bm: int
        """

        self._tp_bm = tp_bm

    @property
    def n_bm(self):
        """Gets the n_bm of this BeneficioMunicipal.  # noqa: E501

        Identificador do benefício parametrizado pelo município.  Trata-se de um identificador único que foi gerado pelo Sistema Nacional no momento em que o município de incidência do ISSQN incluiu o benefício no sistema.  Critério de formação do número de identificação de parâmetros municipais:  7 dígitos - posição 1 a 7: número identificador do Município, conforme código IBGE  2 dígitos - posições 8 e 9 : número identificador do tipo de parametrização (01-legislação, 02-regimes especiais, 03-retenções, 04-outros benefícios)  5 dígitos - posição 10 a 14 : número sequencial definido pelo sistema quando do registro específico do parâmetro dentro do tipo de parametrização no sistema.  # noqa: E501

        :return: The n_bm of this BeneficioMunicipal.  # noqa: E501
        :rtype: str
        """
        return self._n_bm

    @n_bm.setter
    def n_bm(self, n_bm):
        """Sets the n_bm of this BeneficioMunicipal.

        Identificador do benefício parametrizado pelo município.  Trata-se de um identificador único que foi gerado pelo Sistema Nacional no momento em que o município de incidência do ISSQN incluiu o benefício no sistema.  Critério de formação do número de identificação de parâmetros municipais:  7 dígitos - posição 1 a 7: número identificador do Município, conforme código IBGE  2 dígitos - posições 8 e 9 : número identificador do tipo de parametrização (01-legislação, 02-regimes especiais, 03-retenções, 04-outros benefícios)  5 dígitos - posição 10 a 14 : número sequencial definido pelo sistema quando do registro específico do parâmetro dentro do tipo de parametrização no sistema.  # noqa: E501

        :param n_bm: The n_bm of this BeneficioMunicipal.  # noqa: E501
        :type n_bm: str
        """

        self._n_bm = n_bm

    @property
    def v_red_bcbm(self):
        """Gets the v_red_bcbm of this BeneficioMunicipal.  # noqa: E501

        Valor monetário informado pelo emitente para redução da base de cálculo (BC) do ISSQN devido a um Benefício Municipal (BM).  # noqa: E501

        :return: The v_red_bcbm of this BeneficioMunicipal.  # noqa: E501
        :rtype: float
        """
        return self._v_red_bcbm

    @v_red_bcbm.setter
    def v_red_bcbm(self, v_red_bcbm):
        """Sets the v_red_bcbm of this BeneficioMunicipal.

        Valor monetário informado pelo emitente para redução da base de cálculo (BC) do ISSQN devido a um Benefício Municipal (BM).  # noqa: E501

        :param v_red_bcbm: The v_red_bcbm of this BeneficioMunicipal.  # noqa: E501
        :type v_red_bcbm: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_red_bcbm is not None and v_red_bcbm < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_red_bcbm`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_red_bcbm = v_red_bcbm

    @property
    def p_red_bcbm(self):
        """Gets the p_red_bcbm of this BeneficioMunicipal.  # noqa: E501

        Valor percentual informado pelo emitente para redução da base de cálculo (BC) do ISSQN devido a um Benefício Municipal (BM).  # noqa: E501

        :return: The p_red_bcbm of this BeneficioMunicipal.  # noqa: E501
        :rtype: float
        """
        return self._p_red_bcbm

    @p_red_bcbm.setter
    def p_red_bcbm(self, p_red_bcbm):
        """Sets the p_red_bcbm of this BeneficioMunicipal.

        Valor percentual informado pelo emitente para redução da base de cálculo (BC) do ISSQN devido a um Benefício Municipal (BM).  # noqa: E501

        :param p_red_bcbm: The p_red_bcbm of this BeneficioMunicipal.  # noqa: E501
        :type p_red_bcbm: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_red_bcbm is not None and p_red_bcbm < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_red_bcbm`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_red_bcbm = p_red_bcbm

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeneficioMunicipal):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BeneficioMunicipal):
            return True

        return self.to_dict() != other.to_dict()
