# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.12
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class ContaExtratoCredito(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tenant_id': 'str',
        'created_at': 'datetime',
        'quota_name': 'str',
        'movement_type': 'str',
        'credits': 'float',
        'document_id': 'str',
        'arquivo_id': 'str',
        'http_method': 'str',
        'uri': 'str',
        'client_id': 'str',
        'origin': 'str',
        'resource_type': 'str',
        'resource_id': 'str',
        'request_id': 'str'
    }

    attribute_map = {
        'tenant_id': 'tenant_id',
        'created_at': 'created_at',
        'quota_name': 'quota_name',
        'movement_type': 'movement_type',
        'credits': 'credits',
        'document_id': 'document_id',
        'arquivo_id': 'arquivo_id',
        'http_method': 'http_method',
        'uri': 'uri',
        'client_id': 'client_id',
        'origin': 'origin',
        'resource_type': 'resource_type',
        'resource_id': 'resource_id',
        'request_id': 'request_id'
    }

    def __init__(self, tenant_id=None, created_at=None, quota_name=None, movement_type=None, credits=None, document_id=None, arquivo_id=None, http_method=None, uri=None, client_id=None, origin=None, resource_type=None, resource_id=None, request_id=None, local_vars_configuration=None):  # noqa: E501
        """ContaExtratoCredito - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._tenant_id = None
        self._created_at = None
        self._quota_name = None
        self._movement_type = None
        self._credits = None
        self._document_id = None
        self._arquivo_id = None
        self._http_method = None
        self._uri = None
        self._client_id = None
        self._origin = None
        self._resource_type = None
        self._resource_id = None
        self._request_id = None
        self.discriminator = None

        if tenant_id is not None:
            self.tenant_id = tenant_id
        if created_at is not None:
            self.created_at = created_at
        if quota_name is not None:
            self.quota_name = quota_name
        if movement_type is not None:
            self.movement_type = movement_type
        if credits is not None:
            self.credits = credits
        if document_id is not None:
            self.document_id = document_id
        if arquivo_id is not None:
            self.arquivo_id = arquivo_id
        if http_method is not None:
            self.http_method = http_method
        if uri is not None:
            self.uri = uri
        if client_id is not None:
            self.client_id = client_id
        if origin is not None:
            self.origin = origin
        if resource_type is not None:
            self.resource_type = resource_type
        if resource_id is not None:
            self.resource_id = resource_id
        if request_id is not None:
            self.request_id = request_id

    @property
    def tenant_id(self):
        """Gets the tenant_id of this ContaExtratoCredito.  # noqa: E501


        :return: The tenant_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this ContaExtratoCredito.


        :param tenant_id: The tenant_id of this ContaExtratoCredito.  # noqa: E501
        :type tenant_id: str
        """

        self._tenant_id = tenant_id

    @property
    def created_at(self):
        """Gets the created_at of this ContaExtratoCredito.  # noqa: E501


        :return: The created_at of this ContaExtratoCredito.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ContaExtratoCredito.


        :param created_at: The created_at of this ContaExtratoCredito.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def quota_name(self):
        """Gets the quota_name of this ContaExtratoCredito.  # noqa: E501


        :return: The quota_name of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._quota_name

    @quota_name.setter
    def quota_name(self, quota_name):
        """Sets the quota_name of this ContaExtratoCredito.


        :param quota_name: The quota_name of this ContaExtratoCredito.  # noqa: E501
        :type quota_name: str
        """

        self._quota_name = quota_name

    @property
    def movement_type(self):
        """Gets the movement_type of this ContaExtratoCredito.  # noqa: E501


        :return: The movement_type of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._movement_type

    @movement_type.setter
    def movement_type(self, movement_type):
        """Sets the movement_type of this ContaExtratoCredito.


        :param movement_type: The movement_type of this ContaExtratoCredito.  # noqa: E501
        :type movement_type: str
        """

        self._movement_type = movement_type

    @property
    def credits(self):
        """Gets the credits of this ContaExtratoCredito.  # noqa: E501


        :return: The credits of this ContaExtratoCredito.  # noqa: E501
        :rtype: float
        """
        return self._credits

    @credits.setter
    def credits(self, credits):
        """Sets the credits of this ContaExtratoCredito.


        :param credits: The credits of this ContaExtratoCredito.  # noqa: E501
        :type credits: float
        """

        self._credits = credits

    @property
    def document_id(self):
        """Gets the document_id of this ContaExtratoCredito.  # noqa: E501


        :return: The document_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this ContaExtratoCredito.


        :param document_id: The document_id of this ContaExtratoCredito.  # noqa: E501
        :type document_id: str
        """

        self._document_id = document_id

    @property
    def arquivo_id(self):
        """Gets the arquivo_id of this ContaExtratoCredito.  # noqa: E501


        :return: The arquivo_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._arquivo_id

    @arquivo_id.setter
    def arquivo_id(self, arquivo_id):
        """Sets the arquivo_id of this ContaExtratoCredito.


        :param arquivo_id: The arquivo_id of this ContaExtratoCredito.  # noqa: E501
        :type arquivo_id: str
        """

        self._arquivo_id = arquivo_id

    @property
    def http_method(self):
        """Gets the http_method of this ContaExtratoCredito.  # noqa: E501


        :return: The http_method of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._http_method

    @http_method.setter
    def http_method(self, http_method):
        """Sets the http_method of this ContaExtratoCredito.


        :param http_method: The http_method of this ContaExtratoCredito.  # noqa: E501
        :type http_method: str
        """

        self._http_method = http_method

    @property
    def uri(self):
        """Gets the uri of this ContaExtratoCredito.  # noqa: E501


        :return: The uri of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this ContaExtratoCredito.


        :param uri: The uri of this ContaExtratoCredito.  # noqa: E501
        :type uri: str
        """

        self._uri = uri

    @property
    def client_id(self):
        """Gets the client_id of this ContaExtratoCredito.  # noqa: E501


        :return: The client_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this ContaExtratoCredito.


        :param client_id: The client_id of this ContaExtratoCredito.  # noqa: E501
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def origin(self):
        """Gets the origin of this ContaExtratoCredito.  # noqa: E501


        :return: The origin of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this ContaExtratoCredito.


        :param origin: The origin of this ContaExtratoCredito.  # noqa: E501
        :type origin: str
        """

        self._origin = origin

    @property
    def resource_type(self):
        """Gets the resource_type of this ContaExtratoCredito.  # noqa: E501


        :return: The resource_type of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ContaExtratoCredito.


        :param resource_type: The resource_type of this ContaExtratoCredito.  # noqa: E501
        :type resource_type: str
        """

        self._resource_type = resource_type

    @property
    def resource_id(self):
        """Gets the resource_id of this ContaExtratoCredito.  # noqa: E501


        :return: The resource_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this ContaExtratoCredito.


        :param resource_id: The resource_id of this ContaExtratoCredito.  # noqa: E501
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def request_id(self):
        """Gets the request_id of this ContaExtratoCredito.  # noqa: E501


        :return: The request_id of this ContaExtratoCredito.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this ContaExtratoCredito.


        :param request_id: The request_id of this ContaExtratoCredito.  # noqa: E501
        :type request_id: str
        """

        self._request_id = request_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContaExtratoCredito):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContaExtratoCredito):
            return True

        return self.to_dict() != other.to_dict()
