# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSefazDevTrib(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'p_dev_trib': 'float',
        'v_dev_trib': 'float'
    }

    attribute_map = {
        'p_dev_trib': 'pDevTrib',
        'v_dev_trib': 'vDevTrib'
    }

    def __init__(self, p_dev_trib=None, v_dev_trib=None, local_vars_configuration=None):  # noqa: E501
        """CteSefazDevTrib - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._p_dev_trib = None
        self._v_dev_trib = None
        self.discriminator = None

        self.p_dev_trib = p_dev_trib
        self.v_dev_trib = v_dev_trib

    @property
    def p_dev_trib(self):
        """Gets the p_dev_trib of this CteSefazDevTrib.  # noqa: E501

        Percentual de devolução do tributo, conforme LC 214/25 art. 118.  # noqa: E501

        :return: The p_dev_trib of this CteSefazDevTrib.  # noqa: E501
        :rtype: float
        """
        return self._p_dev_trib

    @p_dev_trib.setter
    def p_dev_trib(self, p_dev_trib):
        """Sets the p_dev_trib of this CteSefazDevTrib.

        Percentual de devolução do tributo, conforme LC 214/25 art. 118.  # noqa: E501

        :param p_dev_trib: The p_dev_trib of this CteSefazDevTrib.  # noqa: E501
        :type p_dev_trib: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_dev_trib is not None and p_dev_trib < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_dev_trib`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_dev_trib = p_dev_trib

    @property
    def v_dev_trib(self):
        """Gets the v_dev_trib of this CteSefazDevTrib.  # noqa: E501

        Valor do tributo devolvido. (“cashback” de desconto na própria Nota Fiscal / Fatura).  # noqa: E501

        :return: The v_dev_trib of this CteSefazDevTrib.  # noqa: E501
        :rtype: float
        """
        return self._v_dev_trib

    @v_dev_trib.setter
    def v_dev_trib(self, v_dev_trib):
        """Sets the v_dev_trib of this CteSefazDevTrib.

        Valor do tributo devolvido. (“cashback” de desconto na própria Nota Fiscal / Fatura).  # noqa: E501

        :param v_dev_trib: The v_dev_trib of this CteSefazDevTrib.  # noqa: E501
        :type v_dev_trib: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_dev_trib is not None and v_dev_trib < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_dev_trib`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_dev_trib = v_dev_trib

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSefazDevTrib):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSefazDevTrib):
            return True

        return self.to_dict() != other.to_dict()
