# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteOsSefazTribRegularOS(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cst_reg': 'str',
        'c_class_trib_reg': 'str',
        'p_aliq_efet_reg_ibsuf': 'float',
        'v_trib_reg_ibsuf': 'float',
        'p_aliq_efet_reg_ibs_mun': 'float',
        'v_trib_reg_ibs_mun': 'float',
        'p_aliq_efet_reg_cbs': 'float',
        'v_trib_reg_cbs': 'float'
    }

    attribute_map = {
        'cst_reg': 'CSTReg',
        'c_class_trib_reg': 'cClassTribReg',
        'p_aliq_efet_reg_ibsuf': 'pAliqEfetRegIBSUF',
        'v_trib_reg_ibsuf': 'vTribRegIBSUF',
        'p_aliq_efet_reg_ibs_mun': 'pAliqEfetRegIBSMun',
        'v_trib_reg_ibs_mun': 'vTribRegIBSMun',
        'p_aliq_efet_reg_cbs': 'pAliqEfetRegCBS',
        'v_trib_reg_cbs': 'vTribRegCBS'
    }

    def __init__(self, cst_reg=None, c_class_trib_reg=None, p_aliq_efet_reg_ibsuf=None, v_trib_reg_ibsuf=None, p_aliq_efet_reg_ibs_mun=None, v_trib_reg_ibs_mun=None, p_aliq_efet_reg_cbs=None, v_trib_reg_cbs=None, local_vars_configuration=None):  # noqa: E501
        """CteOsSefazTribRegularOS - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cst_reg = None
        self._c_class_trib_reg = None
        self._p_aliq_efet_reg_ibsuf = None
        self._v_trib_reg_ibsuf = None
        self._p_aliq_efet_reg_ibs_mun = None
        self._v_trib_reg_ibs_mun = None
        self._p_aliq_efet_reg_cbs = None
        self._v_trib_reg_cbs = None
        self.discriminator = None

        self.cst_reg = cst_reg
        self.c_class_trib_reg = c_class_trib_reg
        self.p_aliq_efet_reg_ibsuf = p_aliq_efet_reg_ibsuf
        self.v_trib_reg_ibsuf = v_trib_reg_ibsuf
        self.p_aliq_efet_reg_ibs_mun = p_aliq_efet_reg_ibs_mun
        self.v_trib_reg_ibs_mun = v_trib_reg_ibs_mun
        self.p_aliq_efet_reg_cbs = p_aliq_efet_reg_cbs
        self.v_trib_reg_cbs = v_trib_reg_cbs

    @property
    def cst_reg(self):
        """Gets the cst_reg of this CteOsSefazTribRegularOS.  # noqa: E501

        Código da Situação Tributária do IBS e CBS.  Informar qual seria o CST caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The cst_reg of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: str
        """
        return self._cst_reg

    @cst_reg.setter
    def cst_reg(self, cst_reg):
        """Sets the cst_reg of this CteOsSefazTribRegularOS.

        Código da Situação Tributária do IBS e CBS.  Informar qual seria o CST caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param cst_reg: The cst_reg of this CteOsSefazTribRegularOS.  # noqa: E501
        :type cst_reg: str
        """

        self._cst_reg = cst_reg

    @property
    def c_class_trib_reg(self):
        """Gets the c_class_trib_reg of this CteOsSefazTribRegularOS.  # noqa: E501

        Informar qual seria o cClassTrib caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The c_class_trib_reg of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: str
        """
        return self._c_class_trib_reg

    @c_class_trib_reg.setter
    def c_class_trib_reg(self, c_class_trib_reg):
        """Sets the c_class_trib_reg of this CteOsSefazTribRegularOS.

        Informar qual seria o cClassTrib caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param c_class_trib_reg: The c_class_trib_reg of this CteOsSefazTribRegularOS.  # noqa: E501
        :type c_class_trib_reg: str
        """

        self._c_class_trib_reg = c_class_trib_reg

    @property
    def p_aliq_efet_reg_ibsuf(self):
        """Gets the p_aliq_efet_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501

        Alíquota do IBS da UF.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The p_aliq_efet_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._p_aliq_efet_reg_ibsuf

    @p_aliq_efet_reg_ibsuf.setter
    def p_aliq_efet_reg_ibsuf(self, p_aliq_efet_reg_ibsuf):
        """Sets the p_aliq_efet_reg_ibsuf of this CteOsSefazTribRegularOS.

        Alíquota do IBS da UF.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param p_aliq_efet_reg_ibsuf: The p_aliq_efet_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501
        :type p_aliq_efet_reg_ibsuf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_aliq_efet_reg_ibsuf is not None and p_aliq_efet_reg_ibsuf < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_aliq_efet_reg_ibsuf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_aliq_efet_reg_ibsuf = p_aliq_efet_reg_ibsuf

    @property
    def v_trib_reg_ibsuf(self):
        """Gets the v_trib_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501

        Valor do IBS da UF.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The v_trib_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._v_trib_reg_ibsuf

    @v_trib_reg_ibsuf.setter
    def v_trib_reg_ibsuf(self, v_trib_reg_ibsuf):
        """Sets the v_trib_reg_ibsuf of this CteOsSefazTribRegularOS.

        Valor do IBS da UF.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param v_trib_reg_ibsuf: The v_trib_reg_ibsuf of this CteOsSefazTribRegularOS.  # noqa: E501
        :type v_trib_reg_ibsuf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_trib_reg_ibsuf is not None and v_trib_reg_ibsuf < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_trib_reg_ibsuf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_trib_reg_ibsuf = v_trib_reg_ibsuf

    @property
    def p_aliq_efet_reg_ibs_mun(self):
        """Gets the p_aliq_efet_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501

        Alíquota do IBS do Município.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The p_aliq_efet_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._p_aliq_efet_reg_ibs_mun

    @p_aliq_efet_reg_ibs_mun.setter
    def p_aliq_efet_reg_ibs_mun(self, p_aliq_efet_reg_ibs_mun):
        """Sets the p_aliq_efet_reg_ibs_mun of this CteOsSefazTribRegularOS.

        Alíquota do IBS do Município.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param p_aliq_efet_reg_ibs_mun: The p_aliq_efet_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501
        :type p_aliq_efet_reg_ibs_mun: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_aliq_efet_reg_ibs_mun is not None and p_aliq_efet_reg_ibs_mun < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_aliq_efet_reg_ibs_mun`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_aliq_efet_reg_ibs_mun = p_aliq_efet_reg_ibs_mun

    @property
    def v_trib_reg_ibs_mun(self):
        """Gets the v_trib_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501

        Valor do IBS do Município.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The v_trib_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._v_trib_reg_ibs_mun

    @v_trib_reg_ibs_mun.setter
    def v_trib_reg_ibs_mun(self, v_trib_reg_ibs_mun):
        """Sets the v_trib_reg_ibs_mun of this CteOsSefazTribRegularOS.

        Valor do IBS do Município.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param v_trib_reg_ibs_mun: The v_trib_reg_ibs_mun of this CteOsSefazTribRegularOS.  # noqa: E501
        :type v_trib_reg_ibs_mun: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_trib_reg_ibs_mun is not None and v_trib_reg_ibs_mun < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_trib_reg_ibs_mun`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_trib_reg_ibs_mun = v_trib_reg_ibs_mun

    @property
    def p_aliq_efet_reg_cbs(self):
        """Gets the p_aliq_efet_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501

        Alíquota da CBS.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The p_aliq_efet_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._p_aliq_efet_reg_cbs

    @p_aliq_efet_reg_cbs.setter
    def p_aliq_efet_reg_cbs(self, p_aliq_efet_reg_cbs):
        """Sets the p_aliq_efet_reg_cbs of this CteOsSefazTribRegularOS.

        Alíquota da CBS.  Informar como seria a Alíquota caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param p_aliq_efet_reg_cbs: The p_aliq_efet_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501
        :type p_aliq_efet_reg_cbs: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_aliq_efet_reg_cbs is not None and p_aliq_efet_reg_cbs < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_aliq_efet_reg_cbs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_aliq_efet_reg_cbs = p_aliq_efet_reg_cbs

    @property
    def v_trib_reg_cbs(self):
        """Gets the v_trib_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501

        Valor da CBS.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :return: The v_trib_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501
        :rtype: float
        """
        return self._v_trib_reg_cbs

    @v_trib_reg_cbs.setter
    def v_trib_reg_cbs(self, v_trib_reg_cbs):
        """Sets the v_trib_reg_cbs of this CteOsSefazTribRegularOS.

        Valor da CBS.  Informar como seria o valor do Tributo caso não cumprida a condição resolutória/suspensiva.  # noqa: E501

        :param v_trib_reg_cbs: The v_trib_reg_cbs of this CteOsSefazTribRegularOS.  # noqa: E501
        :type v_trib_reg_cbs: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_trib_reg_cbs is not None and v_trib_reg_cbs < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_trib_reg_cbs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_trib_reg_cbs = v_trib_reg_cbs

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteOsSefazTribRegularOS):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteOsSefazTribRegularOS):
            return True

        return self.to_dict() != other.to_dict()
