# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSimpSefazGPagAntecipadoSimp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ch_dfe_pag_ant': 'str'
    }

    attribute_map = {
        'ch_dfe_pag_ant': 'chDFePagAnt'
    }

    def __init__(self, ch_dfe_pag_ant=None, local_vars_configuration=None):  # noqa: E501
        """CteSimpSefazGPagAntecipadoSimp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._ch_dfe_pag_ant = None
        self.discriminator = None

        self.ch_dfe_pag_ant = ch_dfe_pag_ant

    @property
    def ch_dfe_pag_ant(self):
        """Gets the ch_dfe_pag_ant of this CteSimpSefazGPagAntecipadoSimp.  # noqa: E501

        Chave de acesso do DFe de antecipação de pagamento (com tpPagAnt=1).  Referência a CTe emitido anteriormente, referente a pagamento antecipado.  # noqa: E501

        :return: The ch_dfe_pag_ant of this CteSimpSefazGPagAntecipadoSimp.  # noqa: E501
        :rtype: str
        """
        return self._ch_dfe_pag_ant

    @ch_dfe_pag_ant.setter
    def ch_dfe_pag_ant(self, ch_dfe_pag_ant):
        """Sets the ch_dfe_pag_ant of this CteSimpSefazGPagAntecipadoSimp.

        Chave de acesso do DFe de antecipação de pagamento (com tpPagAnt=1).  Referência a CTe emitido anteriormente, referente a pagamento antecipado.  # noqa: E501

        :param ch_dfe_pag_ant: The ch_dfe_pag_ant of this CteSimpSefazGPagAntecipadoSimp.  # noqa: E501
        :type ch_dfe_pag_ant: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ch_dfe_pag_ant is not None and len(ch_dfe_pag_ant) > 44):
            raise ValueError("Invalid value for `ch_dfe_pag_ant`, length must be less than or equal to `44`")  # noqa: E501

        self._ch_dfe_pag_ant = ch_dfe_pag_ant

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSimpSefazGPagAntecipadoSimp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSimpSefazGPagAntecipadoSimp):
            return True

        return self.to_dict() != other.to_dict()
