# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteOsSefazInfServicoOS(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'x_desc_serv': 'str',
        'inf_q': 'CteOsSefazInfQOS'
    }

    attribute_map = {
        'x_desc_serv': 'xDescServ',
        'inf_q': 'infQ'
    }

    def __init__(self, x_desc_serv=None, inf_q=None, local_vars_configuration=None):  # noqa: E501
        """CteOsSefazInfServicoOS - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._x_desc_serv = None
        self._inf_q = None
        self.discriminator = None

        self.x_desc_serv = x_desc_serv
        if inf_q is not None:
            self.inf_q = inf_q

    @property
    def x_desc_serv(self):
        """Gets the x_desc_serv of this CteOsSefazInfServicoOS.  # noqa: E501

        Descrição do Serviço prestado.  # noqa: E501

        :return: The x_desc_serv of this CteOsSefazInfServicoOS.  # noqa: E501
        :rtype: str
        """
        return self._x_desc_serv

    @x_desc_serv.setter
    def x_desc_serv(self, x_desc_serv):
        """Sets the x_desc_serv of this CteOsSefazInfServicoOS.

        Descrição do Serviço prestado.  # noqa: E501

        :param x_desc_serv: The x_desc_serv of this CteOsSefazInfServicoOS.  # noqa: E501
        :type x_desc_serv: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_desc_serv is not None and len(x_desc_serv) > 30):
            raise ValueError("Invalid value for `x_desc_serv`, length must be less than or equal to `30`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_desc_serv is not None and len(x_desc_serv) < 1):
            raise ValueError("Invalid value for `x_desc_serv`, length must be greater than or equal to `1`")  # noqa: E501

        self._x_desc_serv = x_desc_serv

    @property
    def inf_q(self):
        """Gets the inf_q of this CteOsSefazInfServicoOS.  # noqa: E501


        :return: The inf_q of this CteOsSefazInfServicoOS.  # noqa: E501
        :rtype: CteOsSefazInfQOS
        """
        return self._inf_q

    @inf_q.setter
    def inf_q(self, inf_q):
        """Sets the inf_q of this CteOsSefazInfServicoOS.


        :param inf_q: The inf_q of this CteOsSefazInfServicoOS.  # noqa: E501
        :type inf_q: CteOsSefazInfQOS
        """

        self._inf_q = inf_q

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteOsSefazInfServicoOS):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteOsSefazInfServicoOS):
            return True

        return self.to_dict() != other.to_dict()
