# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSefazNatCarga(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'x_dime': 'str',
        'c_inf_manu': 'list[str]'
    }

    attribute_map = {
        'x_dime': 'xDime',
        'c_inf_manu': 'cInfManu'
    }

    def __init__(self, x_dime=None, c_inf_manu=None, local_vars_configuration=None):  # noqa: E501
        """CteSefazNatCarga - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._x_dime = None
        self._c_inf_manu = None
        self.discriminator = None

        self.x_dime = x_dime
        if c_inf_manu is not None:
            self.c_inf_manu = c_inf_manu

    @property
    def x_dime(self):
        """Gets the x_dime of this CteSefazNatCarga.  # noqa: E501

        Dimensão.  Formato:1234X1234X1234 (cm). Esse campo deve sempre que possível ser preenchido. Entretanto, quando for impossível o preenchimento das dimensões, fica obrigatório o preenchimento da cubagem em metro cúbico do leiaute do CT-e da estrutura genérica (infQ).  # noqa: E501

        :return: The x_dime of this CteSefazNatCarga.  # noqa: E501
        :rtype: str
        """
        return self._x_dime

    @x_dime.setter
    def x_dime(self, x_dime):
        """Sets the x_dime of this CteSefazNatCarga.

        Dimensão.  Formato:1234X1234X1234 (cm). Esse campo deve sempre que possível ser preenchido. Entretanto, quando for impossível o preenchimento das dimensões, fica obrigatório o preenchimento da cubagem em metro cúbico do leiaute do CT-e da estrutura genérica (infQ).  # noqa: E501

        :param x_dime: The x_dime of this CteSefazNatCarga.  # noqa: E501
        :type x_dime: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_dime is not None and len(x_dime) > 14):
            raise ValueError("Invalid value for `x_dime`, length must be less than or equal to `14`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_dime is not None and len(x_dime) < 5):
            raise ValueError("Invalid value for `x_dime`, length must be greater than or equal to `5`")  # noqa: E501

        self._x_dime = x_dime

    @property
    def c_inf_manu(self):
        """Gets the c_inf_manu of this CteSefazNatCarga.  # noqa: E501

        Informações de manuseio.  * 01 - certificado do expedidor para embarque de animal vivo  * 02 - artigo perigoso conforme Declaração do Expedidor anexa  * 03 - somente em aeronave cargueira  * 04 - artigo perigoso - declaração do expedidor não requerida  * 05 - artigo perigoso em quantidade isenta  * 06 - gelo seco para refrigeração (especificar no campo observações a quantidade)  * 07 - não restrito (especificar a Disposição Especial no campo observações)  * 08 - artigo perigoso em carga consolidada (especificar a quantidade no campo observações)  * 09 - autorização da autoridade governamental anexa (especificar no campo observações)  * 10 - baterias de íons de lítio em conformidade com a Seção II da PI965 - CAO  * 11 - baterias de íons de lítio em conformidade com a Seção II da PI966  * 12 - baterias de íons de lítio em conformidade com a Seção II da PI967  * 13 - baterias de metal lítio em conformidade com a Seção II da PI968 — CAO  * 14 - baterias de metal lítio em conformidade com a Seção II da PI969  * 15 - baterias de metal lítio em conformidade com a Seção II da PI970  * 99 - outro (especificar no campo observações)  # noqa: E501

        :return: The c_inf_manu of this CteSefazNatCarga.  # noqa: E501
        :rtype: list[str]
        """
        return self._c_inf_manu

    @c_inf_manu.setter
    def c_inf_manu(self, c_inf_manu):
        """Sets the c_inf_manu of this CteSefazNatCarga.

        Informações de manuseio.  * 01 - certificado do expedidor para embarque de animal vivo  * 02 - artigo perigoso conforme Declaração do Expedidor anexa  * 03 - somente em aeronave cargueira  * 04 - artigo perigoso - declaração do expedidor não requerida  * 05 - artigo perigoso em quantidade isenta  * 06 - gelo seco para refrigeração (especificar no campo observações a quantidade)  * 07 - não restrito (especificar a Disposição Especial no campo observações)  * 08 - artigo perigoso em carga consolidada (especificar a quantidade no campo observações)  * 09 - autorização da autoridade governamental anexa (especificar no campo observações)  * 10 - baterias de íons de lítio em conformidade com a Seção II da PI965 - CAO  * 11 - baterias de íons de lítio em conformidade com a Seção II da PI966  * 12 - baterias de íons de lítio em conformidade com a Seção II da PI967  * 13 - baterias de metal lítio em conformidade com a Seção II da PI968 — CAO  * 14 - baterias de metal lítio em conformidade com a Seção II da PI969  * 15 - baterias de metal lítio em conformidade com a Seção II da PI970  * 99 - outro (especificar no campo observações)  # noqa: E501

        :param c_inf_manu: The c_inf_manu of this CteSefazNatCarga.  # noqa: E501
        :type c_inf_manu: list[str]
        """

        self._c_inf_manu = c_inf_manu

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSefazNatCarga):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSefazNatCarga):
            return True

        return self.to_dict() != other.to_dict()
