# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSimpSefazDetSimp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'n_item': 'int',
        'c_mun_ini': 'str',
        'x_mun_ini': 'str',
        'c_mun_fim': 'str',
        'x_mun_fim': 'str',
        'v_prest': 'float',
        'v_rec': 'float',
        'comp': 'list[CteSimpSefazCompSimp]',
        'inf_nfe': 'list[CteSimpSefazInfNFeSimp]',
        'inf_doc_ant': 'list[CteSimpSefazInfDocAntSimp]'
    }

    attribute_map = {
        'n_item': 'nItem',
        'c_mun_ini': 'cMunIni',
        'x_mun_ini': 'xMunIni',
        'c_mun_fim': 'cMunFim',
        'x_mun_fim': 'xMunFim',
        'v_prest': 'vPrest',
        'v_rec': 'vRec',
        'comp': 'Comp',
        'inf_nfe': 'infNFe',
        'inf_doc_ant': 'infDocAnt'
    }

    def __init__(self, n_item=None, c_mun_ini=None, x_mun_ini=None, c_mun_fim=None, x_mun_fim=None, v_prest=None, v_rec=None, comp=None, inf_nfe=None, inf_doc_ant=None, local_vars_configuration=None):  # noqa: E501
        """CteSimpSefazDetSimp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._n_item = None
        self._c_mun_ini = None
        self._x_mun_ini = None
        self._c_mun_fim = None
        self._x_mun_fim = None
        self._v_prest = None
        self._v_rec = None
        self._comp = None
        self._inf_nfe = None
        self._inf_doc_ant = None
        self.discriminator = None

        self.n_item = n_item
        self.c_mun_ini = c_mun_ini
        self.x_mun_ini = x_mun_ini
        self.c_mun_fim = c_mun_fim
        self.x_mun_fim = x_mun_fim
        self.v_prest = v_prest
        self.v_rec = v_rec
        if comp is not None:
            self.comp = comp
        if inf_nfe is not None:
            self.inf_nfe = inf_nfe
        if inf_doc_ant is not None:
            self.inf_doc_ant = inf_doc_ant

    @property
    def n_item(self):
        """Gets the n_item of this CteSimpSefazDetSimp.  # noqa: E501

        Número identificador do item agrupador da prestação.  # noqa: E501

        :return: The n_item of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: int
        """
        return self._n_item

    @n_item.setter
    def n_item(self, n_item):
        """Sets the n_item of this CteSimpSefazDetSimp.

        Número identificador do item agrupador da prestação.  # noqa: E501

        :param n_item: The n_item of this CteSimpSefazDetSimp.  # noqa: E501
        :type n_item: int
        """
        if (self.local_vars_configuration.client_side_validation and
                n_item is not None and n_item > 990):  # noqa: E501
            raise ValueError("Invalid value for `n_item`, must be a value less than or equal to `990`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                n_item is not None and n_item < 1):  # noqa: E501
            raise ValueError("Invalid value for `n_item`, must be a value greater than or equal to `1`")  # noqa: E501

        self._n_item = n_item

    @property
    def c_mun_ini(self):
        """Gets the c_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501

        Código do Município de início da prestação.  Utilizar a tabela do IBGE. Informar 9999999 para operações com o exterior.  # noqa: E501

        :return: The c_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: str
        """
        return self._c_mun_ini

    @c_mun_ini.setter
    def c_mun_ini(self, c_mun_ini):
        """Sets the c_mun_ini of this CteSimpSefazDetSimp.

        Código do Município de início da prestação.  Utilizar a tabela do IBGE. Informar 9999999 para operações com o exterior.  # noqa: E501

        :param c_mun_ini: The c_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501
        :type c_mun_ini: str
        """

        self._c_mun_ini = c_mun_ini

    @property
    def x_mun_ini(self):
        """Gets the x_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501

        Nome do Município do início da prestação.  Informar 'EXTERIOR' para operações com o exterior.  # noqa: E501

        :return: The x_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: str
        """
        return self._x_mun_ini

    @x_mun_ini.setter
    def x_mun_ini(self, x_mun_ini):
        """Sets the x_mun_ini of this CteSimpSefazDetSimp.

        Nome do Município do início da prestação.  Informar 'EXTERIOR' para operações com o exterior.  # noqa: E501

        :param x_mun_ini: The x_mun_ini of this CteSimpSefazDetSimp.  # noqa: E501
        :type x_mun_ini: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_mun_ini is not None and len(x_mun_ini) > 60):
            raise ValueError("Invalid value for `x_mun_ini`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_mun_ini is not None and len(x_mun_ini) < 2):
            raise ValueError("Invalid value for `x_mun_ini`, length must be greater than or equal to `2`")  # noqa: E501

        self._x_mun_ini = x_mun_ini

    @property
    def c_mun_fim(self):
        """Gets the c_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501

        Código do Município de término da prestação.  Utilizar a tabela do IBGE. Informar 9999999 para operações com o exterior.  # noqa: E501

        :return: The c_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: str
        """
        return self._c_mun_fim

    @c_mun_fim.setter
    def c_mun_fim(self, c_mun_fim):
        """Sets the c_mun_fim of this CteSimpSefazDetSimp.

        Código do Município de término da prestação.  Utilizar a tabela do IBGE. Informar 9999999 para operações com o exterior.  # noqa: E501

        :param c_mun_fim: The c_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501
        :type c_mun_fim: str
        """

        self._c_mun_fim = c_mun_fim

    @property
    def x_mun_fim(self):
        """Gets the x_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501

        Nome do Município do término da prestação.  Informar 'EXTERIOR' para operações com o exterior.  # noqa: E501

        :return: The x_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: str
        """
        return self._x_mun_fim

    @x_mun_fim.setter
    def x_mun_fim(self, x_mun_fim):
        """Sets the x_mun_fim of this CteSimpSefazDetSimp.

        Nome do Município do término da prestação.  Informar 'EXTERIOR' para operações com o exterior.  # noqa: E501

        :param x_mun_fim: The x_mun_fim of this CteSimpSefazDetSimp.  # noqa: E501
        :type x_mun_fim: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_mun_fim is not None and len(x_mun_fim) > 60):
            raise ValueError("Invalid value for `x_mun_fim`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_mun_fim is not None and len(x_mun_fim) < 2):
            raise ValueError("Invalid value for `x_mun_fim`, length must be greater than or equal to `2`")  # noqa: E501

        self._x_mun_fim = x_mun_fim

    @property
    def v_prest(self):
        """Gets the v_prest of this CteSimpSefazDetSimp.  # noqa: E501

        Valorl da Prestação do Serviço.  Pode conter zeros quando o CT-e for de complemento de ICMS.  # noqa: E501

        :return: The v_prest of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: float
        """
        return self._v_prest

    @v_prest.setter
    def v_prest(self, v_prest):
        """Sets the v_prest of this CteSimpSefazDetSimp.

        Valorl da Prestação do Serviço.  Pode conter zeros quando o CT-e for de complemento de ICMS.  # noqa: E501

        :param v_prest: The v_prest of this CteSimpSefazDetSimp.  # noqa: E501
        :type v_prest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_prest is not None and v_prest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_prest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_prest = v_prest

    @property
    def v_rec(self):
        """Gets the v_rec of this CteSimpSefazDetSimp.  # noqa: E501

        Valor a Receber.  # noqa: E501

        :return: The v_rec of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: float
        """
        return self._v_rec

    @v_rec.setter
    def v_rec(self, v_rec):
        """Sets the v_rec of this CteSimpSefazDetSimp.

        Valor a Receber.  # noqa: E501

        :param v_rec: The v_rec of this CteSimpSefazDetSimp.  # noqa: E501
        :type v_rec: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_rec is not None and v_rec < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_rec`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_rec = v_rec

    @property
    def comp(self):
        """Gets the comp of this CteSimpSefazDetSimp.  # noqa: E501


        :return: The comp of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: list[CteSimpSefazCompSimp]
        """
        return self._comp

    @comp.setter
    def comp(self, comp):
        """Sets the comp of this CteSimpSefazDetSimp.


        :param comp: The comp of this CteSimpSefazDetSimp.  # noqa: E501
        :type comp: list[CteSimpSefazCompSimp]
        """

        self._comp = comp

    @property
    def inf_nfe(self):
        """Gets the inf_nfe of this CteSimpSefazDetSimp.  # noqa: E501


        :return: The inf_nfe of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: list[CteSimpSefazInfNFeSimp]
        """
        return self._inf_nfe

    @inf_nfe.setter
    def inf_nfe(self, inf_nfe):
        """Sets the inf_nfe of this CteSimpSefazDetSimp.


        :param inf_nfe: The inf_nfe of this CteSimpSefazDetSimp.  # noqa: E501
        :type inf_nfe: list[CteSimpSefazInfNFeSimp]
        """

        self._inf_nfe = inf_nfe

    @property
    def inf_doc_ant(self):
        """Gets the inf_doc_ant of this CteSimpSefazDetSimp.  # noqa: E501


        :return: The inf_doc_ant of this CteSimpSefazDetSimp.  # noqa: E501
        :rtype: list[CteSimpSefazInfDocAntSimp]
        """
        return self._inf_doc_ant

    @inf_doc_ant.setter
    def inf_doc_ant(self, inf_doc_ant):
        """Sets the inf_doc_ant of this CteSimpSefazDetSimp.


        :param inf_doc_ant: The inf_doc_ant of this CteSimpSefazDetSimp.  # noqa: E501
        :type inf_doc_ant: list[CteSimpSefazInfDocAntSimp]
        """

        self._inf_doc_ant = inf_doc_ant

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSimpSefazDetSimp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSimpSefazDetSimp):
            return True

        return self.to_dict() != other.to_dict()
