# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSefazEmit(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cnpj': 'str',
        'cpf': 'str',
        'ie': 'str',
        'iest': 'str',
        'x_nome': 'str',
        'x_fant': 'str',
        'ender_emit': 'CteSefazEndeEmi',
        'crt': 'int',
        'isuf_emit': 'str'
    }

    attribute_map = {
        'cnpj': 'CNPJ',
        'cpf': 'CPF',
        'ie': 'IE',
        'iest': 'IEST',
        'x_nome': 'xNome',
        'x_fant': 'xFant',
        'ender_emit': 'enderEmit',
        'crt': 'CRT',
        'isuf_emit': 'ISUFEmit'
    }

    def __init__(self, cnpj=None, cpf=None, ie=None, iest=None, x_nome=None, x_fant=None, ender_emit=None, crt=None, isuf_emit=None, local_vars_configuration=None):  # noqa: E501
        """CteSefazEmit - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cnpj = None
        self._cpf = None
        self._ie = None
        self._iest = None
        self._x_nome = None
        self._x_fant = None
        self._ender_emit = None
        self._crt = None
        self._isuf_emit = None
        self.discriminator = None

        self.cnpj = cnpj
        self.cpf = cpf
        self.ie = ie
        self.iest = iest
        self.x_nome = x_nome
        self.x_fant = x_fant
        if ender_emit is not None:
            self.ender_emit = ender_emit
        self.crt = crt
        self.isuf_emit = isuf_emit

    @property
    def cnpj(self):
        """Gets the cnpj of this CteSefazEmit.  # noqa: E501

        CNPJ do emitente.  Informar zeros não significativos.    ***Obrigatório caso o emitente seja pessoa jurídica***.  # noqa: E501

        :return: The cnpj of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._cnpj

    @cnpj.setter
    def cnpj(self, cnpj):
        """Sets the cnpj of this CteSefazEmit.

        CNPJ do emitente.  Informar zeros não significativos.    ***Obrigatório caso o emitente seja pessoa jurídica***.  # noqa: E501

        :param cnpj: The cnpj of this CteSefazEmit.  # noqa: E501
        :type cnpj: str
        """

        self._cnpj = cnpj

    @property
    def cpf(self):
        """Gets the cpf of this CteSefazEmit.  # noqa: E501

        CPF do emitente.  Informar zeros não significativos.  Usar com série específica 920-969 para emitente pessoa física com inscrição estadual.    ***Obrigatório caso o emitente seja pessoa física***.  # noqa: E501

        :return: The cpf of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._cpf

    @cpf.setter
    def cpf(self, cpf):
        """Sets the cpf of this CteSefazEmit.

        CPF do emitente.  Informar zeros não significativos.  Usar com série específica 920-969 para emitente pessoa física com inscrição estadual.    ***Obrigatório caso o emitente seja pessoa física***.  # noqa: E501

        :param cpf: The cpf of this CteSefazEmit.  # noqa: E501
        :type cpf: str
        """

        self._cpf = cpf

    @property
    def ie(self):
        """Gets the ie of this CteSefazEmit.  # noqa: E501

        Inscrição Estadual do Emitente.  A IE do emitente somente ficará sem informação para o caso do Regime Especial da NFF (tpEmis=3).    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :return: The ie of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._ie

    @ie.setter
    def ie(self, ie):
        """Sets the ie of this CteSefazEmit.

        Inscrição Estadual do Emitente.  A IE do emitente somente ficará sem informação para o caso do Regime Especial da NFF (tpEmis=3).    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :param ie: The ie of this CteSefazEmit.  # noqa: E501
        :type ie: str
        """

        self._ie = ie

    @property
    def iest(self):
        """Gets the iest of this CteSefazEmit.  # noqa: E501

        Inscrição Estadual do Substituto Tributário.  # noqa: E501

        :return: The iest of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._iest

    @iest.setter
    def iest(self, iest):
        """Sets the iest of this CteSefazEmit.

        Inscrição Estadual do Substituto Tributário.  # noqa: E501

        :param iest: The iest of this CteSefazEmit.  # noqa: E501
        :type iest: str
        """

        self._iest = iest

    @property
    def x_nome(self):
        """Gets the x_nome of this CteSefazEmit.  # noqa: E501

        Razão social ou Nome do emitente.    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :return: The x_nome of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._x_nome

    @x_nome.setter
    def x_nome(self, x_nome):
        """Sets the x_nome of this CteSefazEmit.

        Razão social ou Nome do emitente.    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :param x_nome: The x_nome of this CteSefazEmit.  # noqa: E501
        :type x_nome: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_nome is not None and len(x_nome) > 60):
            raise ValueError("Invalid value for `x_nome`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_nome is not None and len(x_nome) < 2):
            raise ValueError("Invalid value for `x_nome`, length must be greater than or equal to `2`")  # noqa: E501

        self._x_nome = x_nome

    @property
    def x_fant(self):
        """Gets the x_fant of this CteSefazEmit.  # noqa: E501

        Nome fantasia.    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :return: The x_fant of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._x_fant

    @x_fant.setter
    def x_fant(self, x_fant):
        """Sets the x_fant of this CteSefazEmit.

        Nome fantasia.    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :param x_fant: The x_fant of this CteSefazEmit.  # noqa: E501
        :type x_fant: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_fant is not None and len(x_fant) > 60):
            raise ValueError("Invalid value for `x_fant`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_fant is not None and len(x_fant) < 2):
            raise ValueError("Invalid value for `x_fant`, length must be greater than or equal to `2`")  # noqa: E501

        self._x_fant = x_fant

    @property
    def ender_emit(self):
        """Gets the ender_emit of this CteSefazEmit.  # noqa: E501


        :return: The ender_emit of this CteSefazEmit.  # noqa: E501
        :rtype: CteSefazEndeEmi
        """
        return self._ender_emit

    @ender_emit.setter
    def ender_emit(self, ender_emit):
        """Sets the ender_emit of this CteSefazEmit.


        :param ender_emit: The ender_emit of this CteSefazEmit.  # noqa: E501
        :type ender_emit: CteSefazEndeEmi
        """

        self._ender_emit = ender_emit

    @property
    def crt(self):
        """Gets the crt of this CteSefazEmit.  # noqa: E501

        Código do Regime Tributário. Informar:  * 1 - Simples Nacional;  * 2 - Simples Nacional, excesso sublimite de receita bruta;  * 3 - Regime Normal;  * 4 - Simples Nacional - Microempreendedor Individual (MEI).    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :return: The crt of this CteSefazEmit.  # noqa: E501
        :rtype: int
        """
        return self._crt

    @crt.setter
    def crt(self, crt):
        """Sets the crt of this CteSefazEmit.

        Código do Regime Tributário. Informar:  * 1 - Simples Nacional;  * 2 - Simples Nacional, excesso sublimite de receita bruta;  * 3 - Regime Normal;  * 4 - Simples Nacional - Microempreendedor Individual (MEI).    *Caso não seja informado, será utilizado o do cadastro da empresa.*  # noqa: E501

        :param crt: The crt of this CteSefazEmit.  # noqa: E501
        :type crt: int
        """

        self._crt = crt

    @property
    def isuf_emit(self):
        """Gets the isuf_emit of this CteSefazEmit.  # noqa: E501

        Inscrição do emitente da Suframa.  Informar o número do Cadastro do emitente na Suframa. Campo obrigatório nas operações que se beneficiam de incentivos fiscais existentes nas áreas sob controle da SUFRAMA com alíquota zero da CBS referente aos arts. 451 e 466 da LC 214/25.  # noqa: E501

        :return: The isuf_emit of this CteSefazEmit.  # noqa: E501
        :rtype: str
        """
        return self._isuf_emit

    @isuf_emit.setter
    def isuf_emit(self, isuf_emit):
        """Sets the isuf_emit of this CteSefazEmit.

        Inscrição do emitente da Suframa.  Informar o número do Cadastro do emitente na Suframa. Campo obrigatório nas operações que se beneficiam de incentivos fiscais existentes nas áreas sob controle da SUFRAMA com alíquota zero da CBS referente aos arts. 451 e 466 da LC 214/25.  # noqa: E501

        :param isuf_emit: The isuf_emit of this CteSefazEmit.  # noqa: E501
        :type isuf_emit: str
        """
        if (self.local_vars_configuration.client_side_validation and
                isuf_emit is not None and len(isuf_emit) > 9):
            raise ValueError("Invalid value for `isuf_emit`, length must be less than or equal to `9`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                isuf_emit is not None and len(isuf_emit) < 8):
            raise ValueError("Invalid value for `isuf_emit`, length must be greater than or equal to `8`")  # noqa: E501

        self._isuf_emit = isuf_emit

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSefazEmit):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSefazEmit):
            return True

        return self.to_dict() != other.to_dict()
