# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSefazCompraGovReduzido(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tp_ente_gov': 'int',
        'p_redutor': 'float',
        'tp_oper_gov': 'int',
        'ref_dfe_ant': 'list[str]'
    }

    attribute_map = {
        'tp_ente_gov': 'tpEnteGov',
        'p_redutor': 'pRedutor',
        'tp_oper_gov': 'tpOperGov',
        'ref_dfe_ant': 'refDFeAnt'
    }

    def __init__(self, tp_ente_gov=None, p_redutor=None, tp_oper_gov=None, ref_dfe_ant=None, local_vars_configuration=None):  # noqa: E501
        """CteSefazCompraGovReduzido - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._tp_ente_gov = None
        self._p_redutor = None
        self._tp_oper_gov = None
        self._ref_dfe_ant = None
        self.discriminator = None

        self.tp_ente_gov = tp_ente_gov
        self.p_redutor = p_redutor
        self.tp_oper_gov = tp_oper_gov
        if ref_dfe_ant is not None:
            self.ref_dfe_ant = ref_dfe_ant

    @property
    def tp_ente_gov(self):
        """Gets the tp_ente_gov of this CteSefazCompraGovReduzido.  # noqa: E501

        Para administração pública direta e suas autarquias e fundações:  * 1 - União  * 2 - Estados  * 3 - Distrito Federal  * 4 - Municípios  * 5 - Consórcio Público  * 6 - Comitê Gestor do IBS  # noqa: E501

        :return: The tp_ente_gov of this CteSefazCompraGovReduzido.  # noqa: E501
        :rtype: int
        """
        return self._tp_ente_gov

    @tp_ente_gov.setter
    def tp_ente_gov(self, tp_ente_gov):
        """Sets the tp_ente_gov of this CteSefazCompraGovReduzido.

        Para administração pública direta e suas autarquias e fundações:  * 1 - União  * 2 - Estados  * 3 - Distrito Federal  * 4 - Municípios  * 5 - Consórcio Público  * 6 - Comitê Gestor do IBS  # noqa: E501

        :param tp_ente_gov: The tp_ente_gov of this CteSefazCompraGovReduzido.  # noqa: E501
        :type tp_ente_gov: int
        """

        self._tp_ente_gov = tp_ente_gov

    @property
    def p_redutor(self):
        """Gets the p_redutor of this CteSefazCompraGovReduzido.  # noqa: E501

        Percentual de redução de aliquota em compra governamental.  # noqa: E501

        :return: The p_redutor of this CteSefazCompraGovReduzido.  # noqa: E501
        :rtype: float
        """
        return self._p_redutor

    @p_redutor.setter
    def p_redutor(self, p_redutor):
        """Sets the p_redutor of this CteSefazCompraGovReduzido.

        Percentual de redução de aliquota em compra governamental.  # noqa: E501

        :param p_redutor: The p_redutor of this CteSefazCompraGovReduzido.  # noqa: E501
        :type p_redutor: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_redutor is not None and p_redutor < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_redutor`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_redutor = p_redutor

    @property
    def tp_oper_gov(self):
        """Gets the tp_oper_gov of this CteSefazCompraGovReduzido.  # noqa: E501

        Tipo da operação com ente governamental:  * 1 - Fornecimento com pagamento posterior  * 2 - Recebimento do pagamento com fornecimento já realizado  * 3 - Fornecimento com pagamento já realizado  * 4 - Recebimento do pagamento com fornecimento posterior  # noqa: E501

        :return: The tp_oper_gov of this CteSefazCompraGovReduzido.  # noqa: E501
        :rtype: int
        """
        return self._tp_oper_gov

    @tp_oper_gov.setter
    def tp_oper_gov(self, tp_oper_gov):
        """Sets the tp_oper_gov of this CteSefazCompraGovReduzido.

        Tipo da operação com ente governamental:  * 1 - Fornecimento com pagamento posterior  * 2 - Recebimento do pagamento com fornecimento já realizado  * 3 - Fornecimento com pagamento já realizado  * 4 - Recebimento do pagamento com fornecimento posterior  # noqa: E501

        :param tp_oper_gov: The tp_oper_gov of this CteSefazCompraGovReduzido.  # noqa: E501
        :type tp_oper_gov: int
        """

        self._tp_oper_gov = tp_oper_gov

    @property
    def ref_dfe_ant(self):
        """Gets the ref_dfe_ant of this CteSefazCompraGovReduzido.  # noqa: E501

        Chave de acesso do documento fiscal anterior.  Deverá ser informado para tpOperGov 2 e 3 e vedado para os tipos 1 e 4.  No caso do toOperGov 2 aceitará apenas uma chave referenciada, no tipo 3 poderá aceitar múltiplas chaves  Obs: a chave de acesso deverá ser de um emitente com o mesmo CNPJ base.  # noqa: E501

        :return: The ref_dfe_ant of this CteSefazCompraGovReduzido.  # noqa: E501
        :rtype: list[str]
        """
        return self._ref_dfe_ant

    @ref_dfe_ant.setter
    def ref_dfe_ant(self, ref_dfe_ant):
        """Sets the ref_dfe_ant of this CteSefazCompraGovReduzido.

        Chave de acesso do documento fiscal anterior.  Deverá ser informado para tpOperGov 2 e 3 e vedado para os tipos 1 e 4.  No caso do toOperGov 2 aceitará apenas uma chave referenciada, no tipo 3 poderá aceitar múltiplas chaves  Obs: a chave de acesso deverá ser de um emitente com o mesmo CNPJ base.  # noqa: E501

        :param ref_dfe_ant: The ref_dfe_ant of this CteSefazCompraGovReduzido.  # noqa: E501
        :type ref_dfe_ant: list[str]
        """

        self._ref_dfe_ant = ref_dfe_ant

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSefazCompraGovReduzido):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSefazCompraGovReduzido):
            return True

        return self.to_dict() != other.to_dict()
