# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSefazInfDoc(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'inf_nf': 'list[CteSefazInfNF]',
        'inf_nfe': 'list[CteSefazInfNFe]',
        'inf_outros': 'list[CteSefazInfOutros]',
        'inf_dce': 'list[CteSefazInfDCe]'
    }

    attribute_map = {
        'inf_nf': 'infNF',
        'inf_nfe': 'infNFe',
        'inf_outros': 'infOutros',
        'inf_dce': 'infDCe'
    }

    def __init__(self, inf_nf=None, inf_nfe=None, inf_outros=None, inf_dce=None, local_vars_configuration=None):  # noqa: E501
        """CteSefazInfDoc - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._inf_nf = None
        self._inf_nfe = None
        self._inf_outros = None
        self._inf_dce = None
        self.discriminator = None

        if inf_nf is not None:
            self.inf_nf = inf_nf
        if inf_nfe is not None:
            self.inf_nfe = inf_nfe
        if inf_outros is not None:
            self.inf_outros = inf_outros
        if inf_dce is not None:
            self.inf_dce = inf_dce

    @property
    def inf_nf(self):
        """Gets the inf_nf of this CteSefazInfDoc.  # noqa: E501


        :return: The inf_nf of this CteSefazInfDoc.  # noqa: E501
        :rtype: list[CteSefazInfNF]
        """
        return self._inf_nf

    @inf_nf.setter
    def inf_nf(self, inf_nf):
        """Sets the inf_nf of this CteSefazInfDoc.


        :param inf_nf: The inf_nf of this CteSefazInfDoc.  # noqa: E501
        :type inf_nf: list[CteSefazInfNF]
        """

        self._inf_nf = inf_nf

    @property
    def inf_nfe(self):
        """Gets the inf_nfe of this CteSefazInfDoc.  # noqa: E501


        :return: The inf_nfe of this CteSefazInfDoc.  # noqa: E501
        :rtype: list[CteSefazInfNFe]
        """
        return self._inf_nfe

    @inf_nfe.setter
    def inf_nfe(self, inf_nfe):
        """Sets the inf_nfe of this CteSefazInfDoc.


        :param inf_nfe: The inf_nfe of this CteSefazInfDoc.  # noqa: E501
        :type inf_nfe: list[CteSefazInfNFe]
        """

        self._inf_nfe = inf_nfe

    @property
    def inf_outros(self):
        """Gets the inf_outros of this CteSefazInfDoc.  # noqa: E501


        :return: The inf_outros of this CteSefazInfDoc.  # noqa: E501
        :rtype: list[CteSefazInfOutros]
        """
        return self._inf_outros

    @inf_outros.setter
    def inf_outros(self, inf_outros):
        """Sets the inf_outros of this CteSefazInfDoc.


        :param inf_outros: The inf_outros of this CteSefazInfDoc.  # noqa: E501
        :type inf_outros: list[CteSefazInfOutros]
        """

        self._inf_outros = inf_outros

    @property
    def inf_dce(self):
        """Gets the inf_dce of this CteSefazInfDoc.  # noqa: E501


        :return: The inf_dce of this CteSefazInfDoc.  # noqa: E501
        :rtype: list[CteSefazInfDCe]
        """
        return self._inf_dce

    @inf_dce.setter
    def inf_dce(self, inf_dce):
        """Sets the inf_dce of this CteSefazInfDoc.


        :param inf_dce: The inf_dce of this CteSefazInfDoc.  # noqa: E501
        :type inf_dce: list[CteSefazInfDCe]
        """

        self._inf_dce = inf_dce

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSefazInfDoc):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSefazInfDoc):
            return True

        return self.to_dict() != other.to_dict()
