# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class CteSimpSefazPeriSimp(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'n_onu': 'str',
        'q_tot_emb': 'str',
        'inf_tot_ap': 'CteSimpSefazInfTotAPSimp'
    }

    attribute_map = {
        'n_onu': 'nONU',
        'q_tot_emb': 'qTotEmb',
        'inf_tot_ap': 'infTotAP'
    }

    def __init__(self, n_onu=None, q_tot_emb=None, inf_tot_ap=None, local_vars_configuration=None):  # noqa: E501
        """CteSimpSefazPeriSimp - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._n_onu = None
        self._q_tot_emb = None
        self._inf_tot_ap = None
        self.discriminator = None

        self.n_onu = n_onu
        self.q_tot_emb = q_tot_emb
        self.inf_tot_ap = inf_tot_ap

    @property
    def n_onu(self):
        """Gets the n_onu of this CteSimpSefazPeriSimp.  # noqa: E501

        Número ONU/UN.  Ver a legislação de transporte de produtos perigosos aplicadas ao modal.  # noqa: E501

        :return: The n_onu of this CteSimpSefazPeriSimp.  # noqa: E501
        :rtype: str
        """
        return self._n_onu

    @n_onu.setter
    def n_onu(self, n_onu):
        """Sets the n_onu of this CteSimpSefazPeriSimp.

        Número ONU/UN.  Ver a legislação de transporte de produtos perigosos aplicadas ao modal.  # noqa: E501

        :param n_onu: The n_onu of this CteSimpSefazPeriSimp.  # noqa: E501
        :type n_onu: str
        """

        self._n_onu = n_onu

    @property
    def q_tot_emb(self):
        """Gets the q_tot_emb of this CteSimpSefazPeriSimp.  # noqa: E501

        Quantidade total de volumes contendo artigos perigosos.  Preencher com o número de volumes (unidades) de artigos perigosos, ou seja, cada embalagem devidamente marcada e etiquetada (por ex.: número de caixas, de tambores, de bombonas, dentre outros). Não deve ser preenchido com o número de ULD, pallets ou containers.  # noqa: E501

        :return: The q_tot_emb of this CteSimpSefazPeriSimp.  # noqa: E501
        :rtype: str
        """
        return self._q_tot_emb

    @q_tot_emb.setter
    def q_tot_emb(self, q_tot_emb):
        """Sets the q_tot_emb of this CteSimpSefazPeriSimp.

        Quantidade total de volumes contendo artigos perigosos.  Preencher com o número de volumes (unidades) de artigos perigosos, ou seja, cada embalagem devidamente marcada e etiquetada (por ex.: número de caixas, de tambores, de bombonas, dentre outros). Não deve ser preenchido com o número de ULD, pallets ou containers.  # noqa: E501

        :param q_tot_emb: The q_tot_emb of this CteSimpSefazPeriSimp.  # noqa: E501
        :type q_tot_emb: str
        """
        if (self.local_vars_configuration.client_side_validation and
                q_tot_emb is not None and len(q_tot_emb) > 20):
            raise ValueError("Invalid value for `q_tot_emb`, length must be less than or equal to `20`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                q_tot_emb is not None and len(q_tot_emb) < 1):
            raise ValueError("Invalid value for `q_tot_emb`, length must be greater than or equal to `1`")  # noqa: E501

        self._q_tot_emb = q_tot_emb

    @property
    def inf_tot_ap(self):
        """Gets the inf_tot_ap of this CteSimpSefazPeriSimp.  # noqa: E501


        :return: The inf_tot_ap of this CteSimpSefazPeriSimp.  # noqa: E501
        :rtype: CteSimpSefazInfTotAPSimp
        """
        return self._inf_tot_ap

    @inf_tot_ap.setter
    def inf_tot_ap(self, inf_tot_ap):
        """Sets the inf_tot_ap of this CteSimpSefazPeriSimp.


        :param inf_tot_ap: The inf_tot_ap of this CteSimpSefazPeriSimp.  # noqa: E501
        :type inf_tot_ap: CteSimpSefazInfTotAPSimp
        """
        if self.local_vars_configuration.client_side_validation and inf_tot_ap is None:  # noqa: E501
            raise ValueError("Invalid value for `inf_tot_ap`, must not be `None`")  # noqa: E501

        self._inf_tot_ap = inf_tot_ap

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CteSimpSefazPeriSimp):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CteSimpSefazPeriSimp):
            return True

        return self.to_dict() != other.to_dict()
