# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class DceSefazInfAdic(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'inf_ad_fisco': 'str',
        'inf_cpl': 'str',
        'inf_ad_marketplace': 'str',
        'inf_ad_ect': 'str',
        'obs_emit': 'list[DceSefazObsEmit]',
        'obs_fisco': 'list[DceSefazObsFisco]',
        'obs_marketplace': 'list[DceSefazObsMarketplace]',
        'obs_ect': 'list[DceSefazObsECT]'
    }

    attribute_map = {
        'inf_ad_fisco': 'infAdFisco',
        'inf_cpl': 'infCpl',
        'inf_ad_marketplace': 'infAdMarketplace',
        'inf_ad_ect': 'infAdECT',
        'obs_emit': 'obsEmit',
        'obs_fisco': 'obsFisco',
        'obs_marketplace': 'obsMarketplace',
        'obs_ect': 'obsECT'
    }

    def __init__(self, inf_ad_fisco=None, inf_cpl=None, inf_ad_marketplace=None, inf_ad_ect=None, obs_emit=None, obs_fisco=None, obs_marketplace=None, obs_ect=None, local_vars_configuration=None):  # noqa: E501
        """DceSefazInfAdic - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._inf_ad_fisco = None
        self._inf_cpl = None
        self._inf_ad_marketplace = None
        self._inf_ad_ect = None
        self._obs_emit = None
        self._obs_fisco = None
        self._obs_marketplace = None
        self._obs_ect = None
        self.discriminator = None

        self.inf_ad_fisco = inf_ad_fisco
        self.inf_cpl = inf_cpl
        self.inf_ad_marketplace = inf_ad_marketplace
        self.inf_ad_ect = inf_ad_ect
        if obs_emit is not None:
            self.obs_emit = obs_emit
        if obs_fisco is not None:
            self.obs_fisco = obs_fisco
        if obs_marketplace is not None:
            self.obs_marketplace = obs_marketplace
        if obs_ect is not None:
            self.obs_ect = obs_ect

    @property
    def inf_ad_fisco(self):
        """Gets the inf_ad_fisco of this DceSefazInfAdic.  # noqa: E501

        Informações adicionais de interesse do Fisco.  Norma referenciada, informações complementares, etc.  # noqa: E501

        :return: The inf_ad_fisco of this DceSefazInfAdic.  # noqa: E501
        :rtype: str
        """
        return self._inf_ad_fisco

    @inf_ad_fisco.setter
    def inf_ad_fisco(self, inf_ad_fisco):
        """Sets the inf_ad_fisco of this DceSefazInfAdic.

        Informações adicionais de interesse do Fisco.  Norma referenciada, informações complementares, etc.  # noqa: E501

        :param inf_ad_fisco: The inf_ad_fisco of this DceSefazInfAdic.  # noqa: E501
        :type inf_ad_fisco: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_fisco is not None and len(inf_ad_fisco) > 2000):
            raise ValueError("Invalid value for `inf_ad_fisco`, length must be less than or equal to `2000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_fisco is not None and len(inf_ad_fisco) < 1):
            raise ValueError("Invalid value for `inf_ad_fisco`, length must be greater than or equal to `1`")  # noqa: E501

        self._inf_ad_fisco = inf_ad_fisco

    @property
    def inf_cpl(self):
        """Gets the inf_cpl of this DceSefazInfAdic.  # noqa: E501

        Informações complementares de interesse do Emitente.  # noqa: E501

        :return: The inf_cpl of this DceSefazInfAdic.  # noqa: E501
        :rtype: str
        """
        return self._inf_cpl

    @inf_cpl.setter
    def inf_cpl(self, inf_cpl):
        """Sets the inf_cpl of this DceSefazInfAdic.

        Informações complementares de interesse do Emitente.  # noqa: E501

        :param inf_cpl: The inf_cpl of this DceSefazInfAdic.  # noqa: E501
        :type inf_cpl: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_cpl is not None and len(inf_cpl) > 5000):
            raise ValueError("Invalid value for `inf_cpl`, length must be less than or equal to `5000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                inf_cpl is not None and len(inf_cpl) < 1):
            raise ValueError("Invalid value for `inf_cpl`, length must be greater than or equal to `1`")  # noqa: E501

        self._inf_cpl = inf_cpl

    @property
    def inf_ad_marketplace(self):
        """Gets the inf_ad_marketplace of this DceSefazInfAdic.  # noqa: E501

        Informações Adicionais do MarketPlace.  # noqa: E501

        :return: The inf_ad_marketplace of this DceSefazInfAdic.  # noqa: E501
        :rtype: str
        """
        return self._inf_ad_marketplace

    @inf_ad_marketplace.setter
    def inf_ad_marketplace(self, inf_ad_marketplace):
        """Sets the inf_ad_marketplace of this DceSefazInfAdic.

        Informações Adicionais do MarketPlace.  # noqa: E501

        :param inf_ad_marketplace: The inf_ad_marketplace of this DceSefazInfAdic.  # noqa: E501
        :type inf_ad_marketplace: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_marketplace is not None and len(inf_ad_marketplace) > 5000):
            raise ValueError("Invalid value for `inf_ad_marketplace`, length must be less than or equal to `5000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_marketplace is not None and len(inf_ad_marketplace) < 1):
            raise ValueError("Invalid value for `inf_ad_marketplace`, length must be greater than or equal to `1`")  # noqa: E501

        self._inf_ad_marketplace = inf_ad_marketplace

    @property
    def inf_ad_ect(self):
        """Gets the inf_ad_ect of this DceSefazInfAdic.  # noqa: E501

        Informações Adicionais do Correio.  # noqa: E501

        :return: The inf_ad_ect of this DceSefazInfAdic.  # noqa: E501
        :rtype: str
        """
        return self._inf_ad_ect

    @inf_ad_ect.setter
    def inf_ad_ect(self, inf_ad_ect):
        """Sets the inf_ad_ect of this DceSefazInfAdic.

        Informações Adicionais do Correio.  # noqa: E501

        :param inf_ad_ect: The inf_ad_ect of this DceSefazInfAdic.  # noqa: E501
        :type inf_ad_ect: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_ect is not None and len(inf_ad_ect) > 5000):
            raise ValueError("Invalid value for `inf_ad_ect`, length must be less than or equal to `5000`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_ect is not None and len(inf_ad_ect) < 1):
            raise ValueError("Invalid value for `inf_ad_ect`, length must be greater than or equal to `1`")  # noqa: E501

        self._inf_ad_ect = inf_ad_ect

    @property
    def obs_emit(self):
        """Gets the obs_emit of this DceSefazInfAdic.  # noqa: E501


        :return: The obs_emit of this DceSefazInfAdic.  # noqa: E501
        :rtype: list[DceSefazObsEmit]
        """
        return self._obs_emit

    @obs_emit.setter
    def obs_emit(self, obs_emit):
        """Sets the obs_emit of this DceSefazInfAdic.


        :param obs_emit: The obs_emit of this DceSefazInfAdic.  # noqa: E501
        :type obs_emit: list[DceSefazObsEmit]
        """
        if (self.local_vars_configuration.client_side_validation and
                obs_emit is not None and len(obs_emit) > 10):
            raise ValueError("Invalid value for `obs_emit`, number of items must be less than or equal to `10`")  # noqa: E501

        self._obs_emit = obs_emit

    @property
    def obs_fisco(self):
        """Gets the obs_fisco of this DceSefazInfAdic.  # noqa: E501


        :return: The obs_fisco of this DceSefazInfAdic.  # noqa: E501
        :rtype: list[DceSefazObsFisco]
        """
        return self._obs_fisco

    @obs_fisco.setter
    def obs_fisco(self, obs_fisco):
        """Sets the obs_fisco of this DceSefazInfAdic.


        :param obs_fisco: The obs_fisco of this DceSefazInfAdic.  # noqa: E501
        :type obs_fisco: list[DceSefazObsFisco]
        """
        if (self.local_vars_configuration.client_side_validation and
                obs_fisco is not None and len(obs_fisco) > 10):
            raise ValueError("Invalid value for `obs_fisco`, number of items must be less than or equal to `10`")  # noqa: E501

        self._obs_fisco = obs_fisco

    @property
    def obs_marketplace(self):
        """Gets the obs_marketplace of this DceSefazInfAdic.  # noqa: E501


        :return: The obs_marketplace of this DceSefazInfAdic.  # noqa: E501
        :rtype: list[DceSefazObsMarketplace]
        """
        return self._obs_marketplace

    @obs_marketplace.setter
    def obs_marketplace(self, obs_marketplace):
        """Sets the obs_marketplace of this DceSefazInfAdic.


        :param obs_marketplace: The obs_marketplace of this DceSefazInfAdic.  # noqa: E501
        :type obs_marketplace: list[DceSefazObsMarketplace]
        """
        if (self.local_vars_configuration.client_side_validation and
                obs_marketplace is not None and len(obs_marketplace) > 10):
            raise ValueError("Invalid value for `obs_marketplace`, number of items must be less than or equal to `10`")  # noqa: E501

        self._obs_marketplace = obs_marketplace

    @property
    def obs_ect(self):
        """Gets the obs_ect of this DceSefazInfAdic.  # noqa: E501


        :return: The obs_ect of this DceSefazInfAdic.  # noqa: E501
        :rtype: list[DceSefazObsECT]
        """
        return self._obs_ect

    @obs_ect.setter
    def obs_ect(self, obs_ect):
        """Sets the obs_ect of this DceSefazInfAdic.


        :param obs_ect: The obs_ect of this DceSefazInfAdic.  # noqa: E501
        :type obs_ect: list[DceSefazObsECT]
        """
        if (self.local_vars_configuration.client_side_validation and
                obs_ect is not None and len(obs_ect) > 10):
            raise ValueError("Invalid value for `obs_ect`, number of items must be less than or equal to `10`")  # noqa: E501

        self._obs_ect = obs_ect

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DceSefazInfAdic):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DceSefazInfAdic):
            return True

        return self.to_dict() != other.to_dict()
