# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class DfePedidoInutilizacao(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ambiente': 'str',
        'cnpj': 'str',
        'ano': 'int',
        'serie': 'int',
        'numero_inicial': 'int',
        'numero_final': 'int',
        'justificativa': 'str'
    }

    attribute_map = {
        'ambiente': 'ambiente',
        'cnpj': 'cnpj',
        'ano': 'ano',
        'serie': 'serie',
        'numero_inicial': 'numero_inicial',
        'numero_final': 'numero_final',
        'justificativa': 'justificativa'
    }

    def __init__(self, ambiente=None, cnpj=None, ano=None, serie=None, numero_inicial=None, numero_final=None, justificativa=None, local_vars_configuration=None):  # noqa: E501
        """DfePedidoInutilizacao - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._ambiente = None
        self._cnpj = None
        self._ano = None
        self._serie = None
        self._numero_inicial = None
        self._numero_final = None
        self._justificativa = None
        self.discriminator = None

        self.ambiente = ambiente
        self.cnpj = cnpj
        self.ano = ano
        self.serie = serie
        self.numero_inicial = numero_inicial
        self.numero_final = numero_final
        self.justificativa = justificativa

    @property
    def ambiente(self):
        """Gets the ambiente of this DfePedidoInutilizacao.  # noqa: E501

        Identificação do Ambiente.  # noqa: E501

        :return: The ambiente of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: str
        """
        return self._ambiente

    @ambiente.setter
    def ambiente(self, ambiente):
        """Sets the ambiente of this DfePedidoInutilizacao.

        Identificação do Ambiente.  # noqa: E501

        :param ambiente: The ambiente of this DfePedidoInutilizacao.  # noqa: E501
        :type ambiente: str
        """
        if self.local_vars_configuration.client_side_validation and ambiente is None:  # noqa: E501
            raise ValueError("Invalid value for `ambiente`, must not be `None`")  # noqa: E501
        allowed_values = ["homologacao", "producao"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and ambiente not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `ambiente` ({0}), must be one of {1}"  # noqa: E501
                .format(ambiente, allowed_values)
            )

        self._ambiente = ambiente

    @property
    def cnpj(self):
        """Gets the cnpj of this DfePedidoInutilizacao.  # noqa: E501

        CNPJ do emitente.  # noqa: E501

        :return: The cnpj of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: str
        """
        return self._cnpj

    @cnpj.setter
    def cnpj(self, cnpj):
        """Sets the cnpj of this DfePedidoInutilizacao.

        CNPJ do emitente.  # noqa: E501

        :param cnpj: The cnpj of this DfePedidoInutilizacao.  # noqa: E501
        :type cnpj: str
        """
        if self.local_vars_configuration.client_side_validation and cnpj is None:  # noqa: E501
            raise ValueError("Invalid value for `cnpj`, must not be `None`")  # noqa: E501

        self._cnpj = cnpj

    @property
    def ano(self):
        """Gets the ano of this DfePedidoInutilizacao.  # noqa: E501

        Ano de inutilização da numeração.  # noqa: E501

        :return: The ano of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: int
        """
        return self._ano

    @ano.setter
    def ano(self, ano):
        """Sets the ano of this DfePedidoInutilizacao.

        Ano de inutilização da numeração.  # noqa: E501

        :param ano: The ano of this DfePedidoInutilizacao.  # noqa: E501
        :type ano: int
        """
        if self.local_vars_configuration.client_side_validation and ano is None:  # noqa: E501
            raise ValueError("Invalid value for `ano`, must not be `None`")  # noqa: E501

        self._ano = ano

    @property
    def serie(self):
        """Gets the serie of this DfePedidoInutilizacao.  # noqa: E501

        Série da NF-e.  # noqa: E501

        :return: The serie of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: int
        """
        return self._serie

    @serie.setter
    def serie(self, serie):
        """Sets the serie of this DfePedidoInutilizacao.

        Série da NF-e.  # noqa: E501

        :param serie: The serie of this DfePedidoInutilizacao.  # noqa: E501
        :type serie: int
        """
        if self.local_vars_configuration.client_side_validation and serie is None:  # noqa: E501
            raise ValueError("Invalid value for `serie`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                serie is not None and serie > 999):  # noqa: E501
            raise ValueError("Invalid value for `serie`, must be a value less than or equal to `999`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                serie is not None and serie < 0):  # noqa: E501
            raise ValueError("Invalid value for `serie`, must be a value greater than or equal to `0`")  # noqa: E501

        self._serie = serie

    @property
    def numero_inicial(self):
        """Gets the numero_inicial of this DfePedidoInutilizacao.  # noqa: E501

        Número da NF-e inicial.  # noqa: E501

        :return: The numero_inicial of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: int
        """
        return self._numero_inicial

    @numero_inicial.setter
    def numero_inicial(self, numero_inicial):
        """Sets the numero_inicial of this DfePedidoInutilizacao.

        Número da NF-e inicial.  # noqa: E501

        :param numero_inicial: The numero_inicial of this DfePedidoInutilizacao.  # noqa: E501
        :type numero_inicial: int
        """
        if self.local_vars_configuration.client_side_validation and numero_inicial is None:  # noqa: E501
            raise ValueError("Invalid value for `numero_inicial`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                numero_inicial is not None and numero_inicial > 999999999):  # noqa: E501
            raise ValueError("Invalid value for `numero_inicial`, must be a value less than or equal to `999999999`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                numero_inicial is not None and numero_inicial < 1):  # noqa: E501
            raise ValueError("Invalid value for `numero_inicial`, must be a value greater than or equal to `1`")  # noqa: E501

        self._numero_inicial = numero_inicial

    @property
    def numero_final(self):
        """Gets the numero_final of this DfePedidoInutilizacao.  # noqa: E501

        Número da NF-e final.  # noqa: E501

        :return: The numero_final of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: int
        """
        return self._numero_final

    @numero_final.setter
    def numero_final(self, numero_final):
        """Sets the numero_final of this DfePedidoInutilizacao.

        Número da NF-e final.  # noqa: E501

        :param numero_final: The numero_final of this DfePedidoInutilizacao.  # noqa: E501
        :type numero_final: int
        """
        if self.local_vars_configuration.client_side_validation and numero_final is None:  # noqa: E501
            raise ValueError("Invalid value for `numero_final`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                numero_final is not None and numero_final > 999999999):  # noqa: E501
            raise ValueError("Invalid value for `numero_final`, must be a value less than or equal to `999999999`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                numero_final is not None and numero_final < 1):  # noqa: E501
            raise ValueError("Invalid value for `numero_final`, must be a value greater than or equal to `1`")  # noqa: E501

        self._numero_final = numero_final

    @property
    def justificativa(self):
        """Gets the justificativa of this DfePedidoInutilizacao.  # noqa: E501

        Justificativa do pedido de inutilização.  # noqa: E501

        :return: The justificativa of this DfePedidoInutilizacao.  # noqa: E501
        :rtype: str
        """
        return self._justificativa

    @justificativa.setter
    def justificativa(self, justificativa):
        """Sets the justificativa of this DfePedidoInutilizacao.

        Justificativa do pedido de inutilização.  # noqa: E501

        :param justificativa: The justificativa of this DfePedidoInutilizacao.  # noqa: E501
        :type justificativa: str
        """
        if self.local_vars_configuration.client_side_validation and justificativa is None:  # noqa: E501
            raise ValueError("Invalid value for `justificativa`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                justificativa is not None and len(justificativa) > 255):
            raise ValueError("Invalid value for `justificativa`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                justificativa is not None and len(justificativa) < 15):
            raise ValueError("Invalid value for `justificativa`, length must be greater than or equal to `15`")  # noqa: E501

        self._justificativa = justificativa

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DfePedidoInutilizacao):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DfePedidoInutilizacao):
            return True

        return self.to_dict() != other.to_dict()
