# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class DfeDebug(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'tipo': 'str',
        'created_at': 'datetime',
        'requisicoes': 'list[DfeRequisicaoDebug]'
    }

    attribute_map = {
        'id': 'id',
        'tipo': 'tipo',
        'created_at': 'created_at',
        'requisicoes': 'requisicoes'
    }

    def __init__(self, id=None, tipo=None, created_at=None, requisicoes=None, local_vars_configuration=None):  # noqa: E501
        """DfeDebug - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._tipo = None
        self._created_at = None
        self._requisicoes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if tipo is not None:
            self.tipo = tipo
        if created_at is not None:
            self.created_at = created_at
        if requisicoes is not None:
            self.requisicoes = requisicoes

    @property
    def id(self):
        """Gets the id of this DfeDebug.  # noqa: E501

        Identificador do documento fiscal.  # noqa: E501

        :return: The id of this DfeDebug.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DfeDebug.

        Identificador do documento fiscal.  # noqa: E501

        :param id: The id of this DfeDebug.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def tipo(self):
        """Gets the tipo of this DfeDebug.  # noqa: E501

        Tipo do documento: nfe, nfce, mdfe, nfse, etc.  # noqa: E501

        :return: The tipo of this DfeDebug.  # noqa: E501
        :rtype: str
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo):
        """Sets the tipo of this DfeDebug.

        Tipo do documento: nfe, nfce, mdfe, nfse, etc.  # noqa: E501

        :param tipo: The tipo of this DfeDebug.  # noqa: E501
        :type tipo: str
        """

        self._tipo = tipo

    @property
    def created_at(self):
        """Gets the created_at of this DfeDebug.  # noqa: E501

        Data e hora da criação do documento, representada no formato UTC (Tempo Universal Coordenado).  O valor é retornado no padrão ISO 8601, incluindo o deslocamento de fuso horário 'Z' no final.    Exemplo: \"2025-04-15T14:16:47.775Z\"  # noqa: E501

        :return: The created_at of this DfeDebug.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this DfeDebug.

        Data e hora da criação do documento, representada no formato UTC (Tempo Universal Coordenado).  O valor é retornado no padrão ISO 8601, incluindo o deslocamento de fuso horário 'Z' no final.    Exemplo: \"2025-04-15T14:16:47.775Z\"  # noqa: E501

        :param created_at: The created_at of this DfeDebug.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def requisicoes(self):
        """Gets the requisicoes of this DfeDebug.  # noqa: E501

        Lista de requisições feitas ao autorizador durante o processamento.  # noqa: E501

        :return: The requisicoes of this DfeDebug.  # noqa: E501
        :rtype: list[DfeRequisicaoDebug]
        """
        return self._requisicoes

    @requisicoes.setter
    def requisicoes(self, requisicoes):
        """Sets the requisicoes of this DfeDebug.

        Lista de requisições feitas ao autorizador durante o processamento.  # noqa: E501

        :param requisicoes: The requisicoes of this DfeDebug.  # noqa: E501
        :type requisicoes: list[DfeRequisicaoDebug]
        """

        self._requisicoes = requisicoes

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DfeDebug):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DfeDebug):
            return True

        return self.to_dict() != other.to_dict()
