# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class DocOutNFSe(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'c_mun_nfse_mun': 'str',
        'n_nfse_mun': 'int',
        'c_verif_nfse_mun': 'str'
    }

    attribute_map = {
        'c_mun_nfse_mun': 'cMunNFSeMun',
        'n_nfse_mun': 'nNFSeMun',
        'c_verif_nfse_mun': 'cVerifNFSeMun'
    }

    def __init__(self, c_mun_nfse_mun=None, n_nfse_mun=None, c_verif_nfse_mun=None, local_vars_configuration=None):  # noqa: E501
        """DocOutNFSe - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._c_mun_nfse_mun = None
        self._n_nfse_mun = None
        self._c_verif_nfse_mun = None
        self.discriminator = None

        self.c_mun_nfse_mun = c_mun_nfse_mun
        self.n_nfse_mun = n_nfse_mun
        self.c_verif_nfse_mun = c_verif_nfse_mun

    @property
    def c_mun_nfse_mun(self):
        """Gets the c_mun_nfse_mun of this DocOutNFSe.  # noqa: E501

        Código Município emissor da nota eletrônica municipal (Tabela do IBGE).  # noqa: E501

        :return: The c_mun_nfse_mun of this DocOutNFSe.  # noqa: E501
        :rtype: str
        """
        return self._c_mun_nfse_mun

    @c_mun_nfse_mun.setter
    def c_mun_nfse_mun(self, c_mun_nfse_mun):
        """Sets the c_mun_nfse_mun of this DocOutNFSe.

        Código Município emissor da nota eletrônica municipal (Tabela do IBGE).  # noqa: E501

        :param c_mun_nfse_mun: The c_mun_nfse_mun of this DocOutNFSe.  # noqa: E501
        :type c_mun_nfse_mun: str
        """

        self._c_mun_nfse_mun = c_mun_nfse_mun

    @property
    def n_nfse_mun(self):
        """Gets the n_nfse_mun of this DocOutNFSe.  # noqa: E501

        Número da nota eletrônica municipal.  # noqa: E501

        :return: The n_nfse_mun of this DocOutNFSe.  # noqa: E501
        :rtype: int
        """
        return self._n_nfse_mun

    @n_nfse_mun.setter
    def n_nfse_mun(self, n_nfse_mun):
        """Sets the n_nfse_mun of this DocOutNFSe.

        Número da nota eletrônica municipal.  # noqa: E501

        :param n_nfse_mun: The n_nfse_mun of this DocOutNFSe.  # noqa: E501
        :type n_nfse_mun: int
        """

        self._n_nfse_mun = n_nfse_mun

    @property
    def c_verif_nfse_mun(self):
        """Gets the c_verif_nfse_mun of this DocOutNFSe.  # noqa: E501

        Código de Verificação da nota eletrônica municipal.  # noqa: E501

        :return: The c_verif_nfse_mun of this DocOutNFSe.  # noqa: E501
        :rtype: str
        """
        return self._c_verif_nfse_mun

    @c_verif_nfse_mun.setter
    def c_verif_nfse_mun(self, c_verif_nfse_mun):
        """Sets the c_verif_nfse_mun of this DocOutNFSe.

        Código de Verificação da nota eletrônica municipal.  # noqa: E501

        :param c_verif_nfse_mun: The c_verif_nfse_mun of this DocOutNFSe.  # noqa: E501
        :type c_verif_nfse_mun: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_verif_nfse_mun is not None and len(c_verif_nfse_mun) > 9):
            raise ValueError("Invalid value for `c_verif_nfse_mun`, length must be less than or equal to `9`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_verif_nfse_mun is not None and len(c_verif_nfse_mun) < 1):
            raise ValueError("Invalid value for `c_verif_nfse_mun`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_verif_nfse_mun = c_verif_nfse_mun

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocOutNFSe):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocOutNFSe):
            return True

        return self.to_dict() != other.to_dict()
