# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class EmpresaCertificado(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'created_at': 'datetime',
        'serial_number': 'str',
        'issuer_name': 'str',
        'not_valid_before': 'datetime',
        'not_valid_after': 'datetime',
        'thumbprint': 'str',
        'subject_name': 'str',
        'cpf_cnpj': 'str',
        'nome_razao_social': 'str'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'created_at',
        'serial_number': 'serial_number',
        'issuer_name': 'issuer_name',
        'not_valid_before': 'not_valid_before',
        'not_valid_after': 'not_valid_after',
        'thumbprint': 'thumbprint',
        'subject_name': 'subject_name',
        'cpf_cnpj': 'cpf_cnpj',
        'nome_razao_social': 'nome_razao_social'
    }

    def __init__(self, id=None, created_at=None, serial_number=None, issuer_name=None, not_valid_before=None, not_valid_after=None, thumbprint=None, subject_name=None, cpf_cnpj=None, nome_razao_social=None, local_vars_configuration=None):  # noqa: E501
        """EmpresaCertificado - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._created_at = None
        self._serial_number = None
        self._issuer_name = None
        self._not_valid_before = None
        self._not_valid_after = None
        self._thumbprint = None
        self._subject_name = None
        self._cpf_cnpj = None
        self._nome_razao_social = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if serial_number is not None:
            self.serial_number = serial_number
        if issuer_name is not None:
            self.issuer_name = issuer_name
        if not_valid_before is not None:
            self.not_valid_before = not_valid_before
        if not_valid_after is not None:
            self.not_valid_after = not_valid_after
        if thumbprint is not None:
            self.thumbprint = thumbprint
        if subject_name is not None:
            self.subject_name = subject_name
        if cpf_cnpj is not None:
            self.cpf_cnpj = cpf_cnpj
        if nome_razao_social is not None:
            self.nome_razao_social = nome_razao_social

    @property
    def id(self):
        """Gets the id of this EmpresaCertificado.  # noqa: E501


        :return: The id of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmpresaCertificado.


        :param id: The id of this EmpresaCertificado.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this EmpresaCertificado.  # noqa: E501


        :return: The created_at of this EmpresaCertificado.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this EmpresaCertificado.


        :param created_at: The created_at of this EmpresaCertificado.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def serial_number(self):
        """Gets the serial_number of this EmpresaCertificado.  # noqa: E501


        :return: The serial_number of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this EmpresaCertificado.


        :param serial_number: The serial_number of this EmpresaCertificado.  # noqa: E501
        :type serial_number: str
        """

        self._serial_number = serial_number

    @property
    def issuer_name(self):
        """Gets the issuer_name of this EmpresaCertificado.  # noqa: E501


        :return: The issuer_name of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._issuer_name

    @issuer_name.setter
    def issuer_name(self, issuer_name):
        """Sets the issuer_name of this EmpresaCertificado.


        :param issuer_name: The issuer_name of this EmpresaCertificado.  # noqa: E501
        :type issuer_name: str
        """

        self._issuer_name = issuer_name

    @property
    def not_valid_before(self):
        """Gets the not_valid_before of this EmpresaCertificado.  # noqa: E501


        :return: The not_valid_before of this EmpresaCertificado.  # noqa: E501
        :rtype: datetime
        """
        return self._not_valid_before

    @not_valid_before.setter
    def not_valid_before(self, not_valid_before):
        """Sets the not_valid_before of this EmpresaCertificado.


        :param not_valid_before: The not_valid_before of this EmpresaCertificado.  # noqa: E501
        :type not_valid_before: datetime
        """

        self._not_valid_before = not_valid_before

    @property
    def not_valid_after(self):
        """Gets the not_valid_after of this EmpresaCertificado.  # noqa: E501


        :return: The not_valid_after of this EmpresaCertificado.  # noqa: E501
        :rtype: datetime
        """
        return self._not_valid_after

    @not_valid_after.setter
    def not_valid_after(self, not_valid_after):
        """Sets the not_valid_after of this EmpresaCertificado.


        :param not_valid_after: The not_valid_after of this EmpresaCertificado.  # noqa: E501
        :type not_valid_after: datetime
        """

        self._not_valid_after = not_valid_after

    @property
    def thumbprint(self):
        """Gets the thumbprint of this EmpresaCertificado.  # noqa: E501


        :return: The thumbprint of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._thumbprint

    @thumbprint.setter
    def thumbprint(self, thumbprint):
        """Sets the thumbprint of this EmpresaCertificado.


        :param thumbprint: The thumbprint of this EmpresaCertificado.  # noqa: E501
        :type thumbprint: str
        """

        self._thumbprint = thumbprint

    @property
    def subject_name(self):
        """Gets the subject_name of this EmpresaCertificado.  # noqa: E501


        :return: The subject_name of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._subject_name

    @subject_name.setter
    def subject_name(self, subject_name):
        """Sets the subject_name of this EmpresaCertificado.


        :param subject_name: The subject_name of this EmpresaCertificado.  # noqa: E501
        :type subject_name: str
        """

        self._subject_name = subject_name

    @property
    def cpf_cnpj(self):
        """Gets the cpf_cnpj of this EmpresaCertificado.  # noqa: E501


        :return: The cpf_cnpj of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._cpf_cnpj

    @cpf_cnpj.setter
    def cpf_cnpj(self, cpf_cnpj):
        """Sets the cpf_cnpj of this EmpresaCertificado.


        :param cpf_cnpj: The cpf_cnpj of this EmpresaCertificado.  # noqa: E501
        :type cpf_cnpj: str
        """

        self._cpf_cnpj = cpf_cnpj

    @property
    def nome_razao_social(self):
        """Gets the nome_razao_social of this EmpresaCertificado.  # noqa: E501


        :return: The nome_razao_social of this EmpresaCertificado.  # noqa: E501
        :rtype: str
        """
        return self._nome_razao_social

    @nome_razao_social.setter
    def nome_razao_social(self, nome_razao_social):
        """Sets the nome_razao_social of this EmpresaCertificado.


        :param nome_razao_social: The nome_razao_social of this EmpresaCertificado.  # noqa: E501
        :type nome_razao_social: str
        """

        self._nome_razao_social = nome_razao_social

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmpresaCertificado):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EmpresaCertificado):
            return True

        return self.to_dict() != other.to_dict()
