# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class InfoDedRed(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'p_dr': 'float',
        'v_dr': 'float',
        'documentos': 'ListaDocDedRed'
    }

    attribute_map = {
        'p_dr': 'pDR',
        'v_dr': 'vDR',
        'documentos': 'documentos'
    }

    def __init__(self, p_dr=None, v_dr=None, documentos=None, local_vars_configuration=None):  # noqa: E501
        """InfoDedRed - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._p_dr = None
        self._v_dr = None
        self._documentos = None
        self.discriminator = None

        self.p_dr = p_dr
        self.v_dr = v_dr
        if documentos is not None:
            self.documentos = documentos

    @property
    def p_dr(self):
        """Gets the p_dr of this InfoDedRed.  # noqa: E501

        Valor percentual padrão para dedução/redução do valor do serviço.  # noqa: E501

        :return: The p_dr of this InfoDedRed.  # noqa: E501
        :rtype: float
        """
        return self._p_dr

    @p_dr.setter
    def p_dr(self, p_dr):
        """Sets the p_dr of this InfoDedRed.

        Valor percentual padrão para dedução/redução do valor do serviço.  # noqa: E501

        :param p_dr: The p_dr of this InfoDedRed.  # noqa: E501
        :type p_dr: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_dr is not None and p_dr < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_dr`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_dr = p_dr

    @property
    def v_dr(self):
        """Gets the v_dr of this InfoDedRed.  # noqa: E501

        Valor monetário padrão para dedução/redução do valor do serviço.  # noqa: E501

        :return: The v_dr of this InfoDedRed.  # noqa: E501
        :rtype: float
        """
        return self._v_dr

    @v_dr.setter
    def v_dr(self, v_dr):
        """Sets the v_dr of this InfoDedRed.

        Valor monetário padrão para dedução/redução do valor do serviço.  # noqa: E501

        :param v_dr: The v_dr of this InfoDedRed.  # noqa: E501
        :type v_dr: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_dr is not None and v_dr < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_dr`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_dr = v_dr

    @property
    def documentos(self):
        """Gets the documentos of this InfoDedRed.  # noqa: E501


        :return: The documentos of this InfoDedRed.  # noqa: E501
        :rtype: ListaDocDedRed
        """
        return self._documentos

    @documentos.setter
    def documentos(self, documentos):
        """Sets the documentos of this InfoDedRed.


        :param documentos: The documentos of this InfoDedRed.  # noqa: E501
        :type documentos: ListaDocDedRed
        """

        self._documentos = documentos

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfoDedRed):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InfoDedRed):
            return True

        return self.to_dict() != other.to_dict()
