# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class MdfeSefazAquav(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'irin': 'str',
        'tp_emb': 'str',
        'c_embar': 'str',
        'x_embar': 'str',
        'n_viag': 'str',
        'c_prt_emb': 'str',
        'c_prt_dest': 'str',
        'prt_trans': 'str',
        'tp_nav': 'int',
        'inf_term_carreg': 'list[MdfeSefazInfTermCarreg]',
        'inf_term_descarreg': 'list[MdfeSefazInfTermDescarreg]',
        'inf_emb_comb': 'list[MdfeSefazInfEmbComb]',
        'inf_unid_carga_vazia': 'list[MdfeSefazInfUnidCargaVazia]',
        'inf_unid_transp_vazia': 'list[MdfeSefazInfUnidTranspVazia]',
        'mmsi': 'str'
    }

    attribute_map = {
        'irin': 'irin',
        'tp_emb': 'tpEmb',
        'c_embar': 'cEmbar',
        'x_embar': 'xEmbar',
        'n_viag': 'nViag',
        'c_prt_emb': 'cPrtEmb',
        'c_prt_dest': 'cPrtDest',
        'prt_trans': 'prtTrans',
        'tp_nav': 'tpNav',
        'inf_term_carreg': 'infTermCarreg',
        'inf_term_descarreg': 'infTermDescarreg',
        'inf_emb_comb': 'infEmbComb',
        'inf_unid_carga_vazia': 'infUnidCargaVazia',
        'inf_unid_transp_vazia': 'infUnidTranspVazia',
        'mmsi': 'MMSI'
    }

    def __init__(self, irin=None, tp_emb=None, c_embar=None, x_embar=None, n_viag=None, c_prt_emb=None, c_prt_dest=None, prt_trans=None, tp_nav=None, inf_term_carreg=None, inf_term_descarreg=None, inf_emb_comb=None, inf_unid_carga_vazia=None, inf_unid_transp_vazia=None, mmsi=None, local_vars_configuration=None):  # noqa: E501
        """MdfeSefazAquav - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._irin = None
        self._tp_emb = None
        self._c_embar = None
        self._x_embar = None
        self._n_viag = None
        self._c_prt_emb = None
        self._c_prt_dest = None
        self._prt_trans = None
        self._tp_nav = None
        self._inf_term_carreg = None
        self._inf_term_descarreg = None
        self._inf_emb_comb = None
        self._inf_unid_carga_vazia = None
        self._inf_unid_transp_vazia = None
        self._mmsi = None
        self.discriminator = None

        self.irin = irin
        self.tp_emb = tp_emb
        self.c_embar = c_embar
        self.x_embar = x_embar
        self.n_viag = n_viag
        self.c_prt_emb = c_prt_emb
        self.c_prt_dest = c_prt_dest
        self.prt_trans = prt_trans
        self.tp_nav = tp_nav
        if inf_term_carreg is not None:
            self.inf_term_carreg = inf_term_carreg
        if inf_term_descarreg is not None:
            self.inf_term_descarreg = inf_term_descarreg
        if inf_emb_comb is not None:
            self.inf_emb_comb = inf_emb_comb
        if inf_unid_carga_vazia is not None:
            self.inf_unid_carga_vazia = inf_unid_carga_vazia
        if inf_unid_transp_vazia is not None:
            self.inf_unid_transp_vazia = inf_unid_transp_vazia
        self.mmsi = mmsi

    @property
    def irin(self):
        """Gets the irin of this MdfeSefazAquav.  # noqa: E501

        Irin do navio sempre deverá ser informado.  # noqa: E501

        :return: The irin of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._irin

    @irin.setter
    def irin(self, irin):
        """Sets the irin of this MdfeSefazAquav.

        Irin do navio sempre deverá ser informado.  # noqa: E501

        :param irin: The irin of this MdfeSefazAquav.  # noqa: E501
        :type irin: str
        """
        if (self.local_vars_configuration.client_side_validation and
                irin is not None and len(irin) > 10):
            raise ValueError("Invalid value for `irin`, length must be less than or equal to `10`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                irin is not None and len(irin) < 1):
            raise ValueError("Invalid value for `irin`, length must be greater than or equal to `1`")  # noqa: E501

        self._irin = irin

    @property
    def tp_emb(self):
        """Gets the tp_emb of this MdfeSefazAquav.  # noqa: E501

        Código do tipo de embarcação.  Preencher com código da Tabela de Tipo de Embarcação definida no Ministério dos Transportes.  # noqa: E501

        :return: The tp_emb of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._tp_emb

    @tp_emb.setter
    def tp_emb(self, tp_emb):
        """Sets the tp_emb of this MdfeSefazAquav.

        Código do tipo de embarcação.  Preencher com código da Tabela de Tipo de Embarcação definida no Ministério dos Transportes.  # noqa: E501

        :param tp_emb: The tp_emb of this MdfeSefazAquav.  # noqa: E501
        :type tp_emb: str
        """

        self._tp_emb = tp_emb

    @property
    def c_embar(self):
        """Gets the c_embar of this MdfeSefazAquav.  # noqa: E501

        Código da embarcação.  # noqa: E501

        :return: The c_embar of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._c_embar

    @c_embar.setter
    def c_embar(self, c_embar):
        """Sets the c_embar of this MdfeSefazAquav.

        Código da embarcação.  # noqa: E501

        :param c_embar: The c_embar of this MdfeSefazAquav.  # noqa: E501
        :type c_embar: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_embar is not None and len(c_embar) > 10):
            raise ValueError("Invalid value for `c_embar`, length must be less than or equal to `10`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_embar is not None and len(c_embar) < 1):
            raise ValueError("Invalid value for `c_embar`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_embar = c_embar

    @property
    def x_embar(self):
        """Gets the x_embar of this MdfeSefazAquav.  # noqa: E501

        Nome da embarcação.  # noqa: E501

        :return: The x_embar of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._x_embar

    @x_embar.setter
    def x_embar(self, x_embar):
        """Sets the x_embar of this MdfeSefazAquav.

        Nome da embarcação.  # noqa: E501

        :param x_embar: The x_embar of this MdfeSefazAquav.  # noqa: E501
        :type x_embar: str
        """
        if (self.local_vars_configuration.client_side_validation and
                x_embar is not None and len(x_embar) > 60):
            raise ValueError("Invalid value for `x_embar`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                x_embar is not None and len(x_embar) < 1):
            raise ValueError("Invalid value for `x_embar`, length must be greater than or equal to `1`")  # noqa: E501

        self._x_embar = x_embar

    @property
    def n_viag(self):
        """Gets the n_viag of this MdfeSefazAquav.  # noqa: E501

        Número da Viagem.  # noqa: E501

        :return: The n_viag of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._n_viag

    @n_viag.setter
    def n_viag(self, n_viag):
        """Sets the n_viag of this MdfeSefazAquav.

        Número da Viagem.  # noqa: E501

        :param n_viag: The n_viag of this MdfeSefazAquav.  # noqa: E501
        :type n_viag: str
        """

        self._n_viag = n_viag

    @property
    def c_prt_emb(self):
        """Gets the c_prt_emb of this MdfeSefazAquav.  # noqa: E501

        Código do Porto de Embarque.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.  # noqa: E501

        :return: The c_prt_emb of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._c_prt_emb

    @c_prt_emb.setter
    def c_prt_emb(self, c_prt_emb):
        """Sets the c_prt_emb of this MdfeSefazAquav.

        Código do Porto de Embarque.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.  # noqa: E501

        :param c_prt_emb: The c_prt_emb of this MdfeSefazAquav.  # noqa: E501
        :type c_prt_emb: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_prt_emb is not None and len(c_prt_emb) > 5):
            raise ValueError("Invalid value for `c_prt_emb`, length must be less than or equal to `5`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_prt_emb is not None and len(c_prt_emb) < 1):
            raise ValueError("Invalid value for `c_prt_emb`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_prt_emb = c_prt_emb

    @property
    def c_prt_dest(self):
        """Gets the c_prt_dest of this MdfeSefazAquav.  # noqa: E501

        Código do Porto de Destino.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.  # noqa: E501

        :return: The c_prt_dest of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._c_prt_dest

    @c_prt_dest.setter
    def c_prt_dest(self, c_prt_dest):
        """Sets the c_prt_dest of this MdfeSefazAquav.

        Código do Porto de Destino.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.  # noqa: E501

        :param c_prt_dest: The c_prt_dest of this MdfeSefazAquav.  # noqa: E501
        :type c_prt_dest: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_prt_dest is not None and len(c_prt_dest) > 5):
            raise ValueError("Invalid value for `c_prt_dest`, length must be less than or equal to `5`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_prt_dest is not None and len(c_prt_dest) < 1):
            raise ValueError("Invalid value for `c_prt_dest`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_prt_dest = c_prt_dest

    @property
    def prt_trans(self):
        """Gets the prt_trans of this MdfeSefazAquav.  # noqa: E501

        Porto de Transbordo.  # noqa: E501

        :return: The prt_trans of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._prt_trans

    @prt_trans.setter
    def prt_trans(self, prt_trans):
        """Sets the prt_trans of this MdfeSefazAquav.

        Porto de Transbordo.  # noqa: E501

        :param prt_trans: The prt_trans of this MdfeSefazAquav.  # noqa: E501
        :type prt_trans: str
        """
        if (self.local_vars_configuration.client_side_validation and
                prt_trans is not None and len(prt_trans) > 60):
            raise ValueError("Invalid value for `prt_trans`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                prt_trans is not None and len(prt_trans) < 1):
            raise ValueError("Invalid value for `prt_trans`, length must be greater than or equal to `1`")  # noqa: E501

        self._prt_trans = prt_trans

    @property
    def tp_nav(self):
        """Gets the tp_nav of this MdfeSefazAquav.  # noqa: E501

        Tipo de Navegação.  Preencher com:  * 0 - Interior  * 1 - Cabotagem  # noqa: E501

        :return: The tp_nav of this MdfeSefazAquav.  # noqa: E501
        :rtype: int
        """
        return self._tp_nav

    @tp_nav.setter
    def tp_nav(self, tp_nav):
        """Sets the tp_nav of this MdfeSefazAquav.

        Tipo de Navegação.  Preencher com:  * 0 - Interior  * 1 - Cabotagem  # noqa: E501

        :param tp_nav: The tp_nav of this MdfeSefazAquav.  # noqa: E501
        :type tp_nav: int
        """

        self._tp_nav = tp_nav

    @property
    def inf_term_carreg(self):
        """Gets the inf_term_carreg of this MdfeSefazAquav.  # noqa: E501


        :return: The inf_term_carreg of this MdfeSefazAquav.  # noqa: E501
        :rtype: list[MdfeSefazInfTermCarreg]
        """
        return self._inf_term_carreg

    @inf_term_carreg.setter
    def inf_term_carreg(self, inf_term_carreg):
        """Sets the inf_term_carreg of this MdfeSefazAquav.


        :param inf_term_carreg: The inf_term_carreg of this MdfeSefazAquav.  # noqa: E501
        :type inf_term_carreg: list[MdfeSefazInfTermCarreg]
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_term_carreg is not None and len(inf_term_carreg) > 5):
            raise ValueError("Invalid value for `inf_term_carreg`, number of items must be less than or equal to `5`")  # noqa: E501

        self._inf_term_carreg = inf_term_carreg

    @property
    def inf_term_descarreg(self):
        """Gets the inf_term_descarreg of this MdfeSefazAquav.  # noqa: E501


        :return: The inf_term_descarreg of this MdfeSefazAquav.  # noqa: E501
        :rtype: list[MdfeSefazInfTermDescarreg]
        """
        return self._inf_term_descarreg

    @inf_term_descarreg.setter
    def inf_term_descarreg(self, inf_term_descarreg):
        """Sets the inf_term_descarreg of this MdfeSefazAquav.


        :param inf_term_descarreg: The inf_term_descarreg of this MdfeSefazAquav.  # noqa: E501
        :type inf_term_descarreg: list[MdfeSefazInfTermDescarreg]
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_term_descarreg is not None and len(inf_term_descarreg) > 5):
            raise ValueError("Invalid value for `inf_term_descarreg`, number of items must be less than or equal to `5`")  # noqa: E501

        self._inf_term_descarreg = inf_term_descarreg

    @property
    def inf_emb_comb(self):
        """Gets the inf_emb_comb of this MdfeSefazAquav.  # noqa: E501


        :return: The inf_emb_comb of this MdfeSefazAquav.  # noqa: E501
        :rtype: list[MdfeSefazInfEmbComb]
        """
        return self._inf_emb_comb

    @inf_emb_comb.setter
    def inf_emb_comb(self, inf_emb_comb):
        """Sets the inf_emb_comb of this MdfeSefazAquav.


        :param inf_emb_comb: The inf_emb_comb of this MdfeSefazAquav.  # noqa: E501
        :type inf_emb_comb: list[MdfeSefazInfEmbComb]
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_emb_comb is not None and len(inf_emb_comb) > 30):
            raise ValueError("Invalid value for `inf_emb_comb`, number of items must be less than or equal to `30`")  # noqa: E501

        self._inf_emb_comb = inf_emb_comb

    @property
    def inf_unid_carga_vazia(self):
        """Gets the inf_unid_carga_vazia of this MdfeSefazAquav.  # noqa: E501


        :return: The inf_unid_carga_vazia of this MdfeSefazAquav.  # noqa: E501
        :rtype: list[MdfeSefazInfUnidCargaVazia]
        """
        return self._inf_unid_carga_vazia

    @inf_unid_carga_vazia.setter
    def inf_unid_carga_vazia(self, inf_unid_carga_vazia):
        """Sets the inf_unid_carga_vazia of this MdfeSefazAquav.


        :param inf_unid_carga_vazia: The inf_unid_carga_vazia of this MdfeSefazAquav.  # noqa: E501
        :type inf_unid_carga_vazia: list[MdfeSefazInfUnidCargaVazia]
        """

        self._inf_unid_carga_vazia = inf_unid_carga_vazia

    @property
    def inf_unid_transp_vazia(self):
        """Gets the inf_unid_transp_vazia of this MdfeSefazAquav.  # noqa: E501


        :return: The inf_unid_transp_vazia of this MdfeSefazAquav.  # noqa: E501
        :rtype: list[MdfeSefazInfUnidTranspVazia]
        """
        return self._inf_unid_transp_vazia

    @inf_unid_transp_vazia.setter
    def inf_unid_transp_vazia(self, inf_unid_transp_vazia):
        """Sets the inf_unid_transp_vazia of this MdfeSefazAquav.


        :param inf_unid_transp_vazia: The inf_unid_transp_vazia of this MdfeSefazAquav.  # noqa: E501
        :type inf_unid_transp_vazia: list[MdfeSefazInfUnidTranspVazia]
        """

        self._inf_unid_transp_vazia = inf_unid_transp_vazia

    @property
    def mmsi(self):
        """Gets the mmsi of this MdfeSefazAquav.  # noqa: E501

        Maritime Mobile Service Identify.  Preencher com o MMSI (Maritime Mobile Service Identify) fornecido pela ANATEL ou autoridade de telecomunicações de origem da embarcação.  # noqa: E501

        :return: The mmsi of this MdfeSefazAquav.  # noqa: E501
        :rtype: str
        """
        return self._mmsi

    @mmsi.setter
    def mmsi(self, mmsi):
        """Sets the mmsi of this MdfeSefazAquav.

        Maritime Mobile Service Identify.  Preencher com o MMSI (Maritime Mobile Service Identify) fornecido pela ANATEL ou autoridade de telecomunicações de origem da embarcação.  # noqa: E501

        :param mmsi: The mmsi of this MdfeSefazAquav.  # noqa: E501
        :type mmsi: str
        """
        if (self.local_vars_configuration.client_side_validation and
                mmsi is not None and len(mmsi) > 9):
            raise ValueError("Invalid value for `mmsi`, length must be less than or equal to `9`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                mmsi is not None and len(mmsi) < 1):
            raise ValueError("Invalid value for `mmsi`, length must be greater than or equal to `1`")  # noqa: E501

        self._mmsi = mmsi

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MdfeSefazAquav):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MdfeSefazAquav):
            return True

        return self.to_dict() != other.to_dict()
