# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfcomSefazPagamentoRTC(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'n_pag': 'str',
        'id_transacao': 'str',
        'tp_meio_pgto': 'str',
        'cnpj_receb': 'str',
        'cnpj_base_psp': 'str'
    }

    attribute_map = {
        'n_pag': 'nPag',
        'id_transacao': 'idTransacao',
        'tp_meio_pgto': 'tpMeioPgto',
        'cnpj_receb': 'CNPJReceb',
        'cnpj_base_psp': 'CNPJBasePSP'
    }

    def __init__(self, n_pag=None, id_transacao=None, tp_meio_pgto=None, cnpj_receb=None, cnpj_base_psp=None, local_vars_configuration=None):  # noqa: E501
        """NfcomSefazPagamentoRTC - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._n_pag = None
        self._id_transacao = None
        self._tp_meio_pgto = None
        self._cnpj_receb = None
        self._cnpj_base_psp = None
        self.discriminator = None

        self.n_pag = n_pag
        self.id_transacao = id_transacao
        self.tp_meio_pgto = tp_meio_pgto
        self.cnpj_receb = cnpj_receb
        self.cnpj_base_psp = cnpj_base_psp

    @property
    def n_pag(self):
        """Gets the n_pag of this NfcomSefazPagamentoRTC.  # noqa: E501

        Número sequencial do pagamento.  # noqa: E501

        :return: The n_pag of this NfcomSefazPagamentoRTC.  # noqa: E501
        :rtype: str
        """
        return self._n_pag

    @n_pag.setter
    def n_pag(self, n_pag):
        """Sets the n_pag of this NfcomSefazPagamentoRTC.

        Número sequencial do pagamento.  # noqa: E501

        :param n_pag: The n_pag of this NfcomSefazPagamentoRTC.  # noqa: E501
        :type n_pag: str
        """

        self._n_pag = n_pag

    @property
    def id_transacao(self):
        """Gets the id_transacao of this NfcomSefazPagamentoRTC.  # noqa: E501

        ID específico da transação financeira conforme o meio de pagamento.  # noqa: E501

        :return: The id_transacao of this NfcomSefazPagamentoRTC.  # noqa: E501
        :rtype: str
        """
        return self._id_transacao

    @id_transacao.setter
    def id_transacao(self, id_transacao):
        """Sets the id_transacao of this NfcomSefazPagamentoRTC.

        ID específico da transação financeira conforme o meio de pagamento.  # noqa: E501

        :param id_transacao: The id_transacao of this NfcomSefazPagamentoRTC.  # noqa: E501
        :type id_transacao: str
        """
        if (self.local_vars_configuration.client_side_validation and
                id_transacao is not None and len(id_transacao) > 35):
            raise ValueError("Invalid value for `id_transacao`, length must be less than or equal to `35`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                id_transacao is not None and len(id_transacao) < 2):
            raise ValueError("Invalid value for `id_transacao`, length must be greater than or equal to `2`")  # noqa: E501

        self._id_transacao = id_transacao

    @property
    def tp_meio_pgto(self):
        """Gets the tp_meio_pgto of this NfcomSefazPagamentoRTC.  # noqa: E501

        (Meio de pagamento utilizado (ver IT DFe 2026.001).  # noqa: E501

        :return: The tp_meio_pgto of this NfcomSefazPagamentoRTC.  # noqa: E501
        :rtype: str
        """
        return self._tp_meio_pgto

    @tp_meio_pgto.setter
    def tp_meio_pgto(self, tp_meio_pgto):
        """Sets the tp_meio_pgto of this NfcomSefazPagamentoRTC.

        (Meio de pagamento utilizado (ver IT DFe 2026.001).  # noqa: E501

        :param tp_meio_pgto: The tp_meio_pgto of this NfcomSefazPagamentoRTC.  # noqa: E501
        :type tp_meio_pgto: str
        """

        self._tp_meio_pgto = tp_meio_pgto

    @property
    def cnpj_receb(self):
        """Gets the cnpj_receb of this NfcomSefazPagamentoRTC.  # noqa: E501

        CNPJ do recebedor do pagamento.  Informar zeros não significativos.  # noqa: E501

        :return: The cnpj_receb of this NfcomSefazPagamentoRTC.  # noqa: E501
        :rtype: str
        """
        return self._cnpj_receb

    @cnpj_receb.setter
    def cnpj_receb(self, cnpj_receb):
        """Sets the cnpj_receb of this NfcomSefazPagamentoRTC.

        CNPJ do recebedor do pagamento.  Informar zeros não significativos.  # noqa: E501

        :param cnpj_receb: The cnpj_receb of this NfcomSefazPagamentoRTC.  # noqa: E501
        :type cnpj_receb: str
        """

        self._cnpj_receb = cnpj_receb

    @property
    def cnpj_base_psp(self):
        """Gets the cnpj_base_psp of this NfcomSefazPagamentoRTC.  # noqa: E501

        CNPJ base da instituição financeira.  Informar zeros não significativos.  # noqa: E501

        :return: The cnpj_base_psp of this NfcomSefazPagamentoRTC.  # noqa: E501
        :rtype: str
        """
        return self._cnpj_base_psp

    @cnpj_base_psp.setter
    def cnpj_base_psp(self, cnpj_base_psp):
        """Sets the cnpj_base_psp of this NfcomSefazPagamentoRTC.

        CNPJ base da instituição financeira.  Informar zeros não significativos.  # noqa: E501

        :param cnpj_base_psp: The cnpj_base_psp of this NfcomSefazPagamentoRTC.  # noqa: E501
        :type cnpj_base_psp: str
        """

        self._cnpj_base_psp = cnpj_base_psp

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfcomSefazPagamentoRTC):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfcomSefazPagamentoRTC):
            return True

        return self.to_dict() != other.to_dict()
