# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfcomSefazGProcRef(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v_item': 'float',
        'q_faturada': 'float',
        'v_prod': 'float',
        'v_desc': 'float',
        'v_outro': 'float',
        'ind_devolucao': 'int',
        'v_bc': 'float',
        'p_icms': 'float',
        'v_icms': 'float',
        'v_pis': 'float',
        'v_cofins': 'float',
        'v_fcp': 'float',
        'g_proc': 'list[NfcomSefazGProc]'
    }

    attribute_map = {
        'v_item': 'vItem',
        'q_faturada': 'qFaturada',
        'v_prod': 'vProd',
        'v_desc': 'vDesc',
        'v_outro': 'vOutro',
        'ind_devolucao': 'indDevolucao',
        'v_bc': 'vBC',
        'p_icms': 'pICMS',
        'v_icms': 'vICMS',
        'v_pis': 'vPIS',
        'v_cofins': 'vCOFINS',
        'v_fcp': 'vFCP',
        'g_proc': 'gProc'
    }

    def __init__(self, v_item=None, q_faturada=None, v_prod=None, v_desc=None, v_outro=None, ind_devolucao=None, v_bc=None, p_icms=None, v_icms=None, v_pis=None, v_cofins=None, v_fcp=None, g_proc=None, local_vars_configuration=None):  # noqa: E501
        """NfcomSefazGProcRef - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._v_item = None
        self._q_faturada = None
        self._v_prod = None
        self._v_desc = None
        self._v_outro = None
        self._ind_devolucao = None
        self._v_bc = None
        self._p_icms = None
        self._v_icms = None
        self._v_pis = None
        self._v_cofins = None
        self._v_fcp = None
        self._g_proc = None
        self.discriminator = None

        self.v_item = v_item
        self.q_faturada = q_faturada
        self.v_prod = v_prod
        self.v_desc = v_desc
        self.v_outro = v_outro
        self.ind_devolucao = ind_devolucao
        self.v_bc = v_bc
        self.p_icms = p_icms
        self.v_icms = v_icms
        self.v_pis = v_pis
        self.v_cofins = v_cofins
        self.v_fcp = v_fcp
        self.g_proc = g_proc

    @property
    def v_item(self):
        """Gets the v_item of this NfcomSefazGProcRef.  # noqa: E501

        Valor unitário do item.  Informar o valor sem a influência da decisão judicial/administrativa.  # noqa: E501

        :return: The v_item of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_item

    @v_item.setter
    def v_item(self, v_item):
        """Sets the v_item of this NfcomSefazGProcRef.

        Valor unitário do item.  Informar o valor sem a influência da decisão judicial/administrativa.  # noqa: E501

        :param v_item: The v_item of this NfcomSefazGProcRef.  # noqa: E501
        :type v_item: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_item is not None and v_item < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_item`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_item = v_item

    @property
    def q_faturada(self):
        """Gets the q_faturada of this NfcomSefazGProcRef.  # noqa: E501

        Quantidade Faturada.  Informar a quantidade de comercialização do produto .  # noqa: E501

        :return: The q_faturada of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._q_faturada

    @q_faturada.setter
    def q_faturada(self, q_faturada):
        """Sets the q_faturada of this NfcomSefazGProcRef.

        Quantidade Faturada.  Informar a quantidade de comercialização do produto .  # noqa: E501

        :param q_faturada: The q_faturada of this NfcomSefazGProcRef.  # noqa: E501
        :type q_faturada: float
        """
        if (self.local_vars_configuration.client_side_validation and
                q_faturada is not None and q_faturada < 0):  # noqa: E501
            raise ValueError("Invalid value for `q_faturada`, must be a value greater than or equal to `0`")  # noqa: E501

        self._q_faturada = q_faturada

    @property
    def v_prod(self):
        """Gets the v_prod of this NfcomSefazGProcRef.  # noqa: E501

        Valor total do item.  # noqa: E501

        :return: The v_prod of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_prod

    @v_prod.setter
    def v_prod(self, v_prod):
        """Sets the v_prod of this NfcomSefazGProcRef.

        Valor total do item.  # noqa: E501

        :param v_prod: The v_prod of this NfcomSefazGProcRef.  # noqa: E501
        :type v_prod: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_prod is not None and v_prod < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_prod`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_prod = v_prod

    @property
    def v_desc(self):
        """Gets the v_desc of this NfcomSefazGProcRef.  # noqa: E501

        Valor do Desconto.  # noqa: E501

        :return: The v_desc of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_desc

    @v_desc.setter
    def v_desc(self, v_desc):
        """Sets the v_desc of this NfcomSefazGProcRef.

        Valor do Desconto.  # noqa: E501

        :param v_desc: The v_desc of this NfcomSefazGProcRef.  # noqa: E501
        :type v_desc: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc is not None and v_desc < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_desc = v_desc

    @property
    def v_outro(self):
        """Gets the v_outro of this NfcomSefazGProcRef.  # noqa: E501

        Outras despesas acessórias.  # noqa: E501

        :return: The v_outro of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_outro

    @v_outro.setter
    def v_outro(self, v_outro):
        """Sets the v_outro of this NfcomSefazGProcRef.

        Outras despesas acessórias.  # noqa: E501

        :param v_outro: The v_outro of this NfcomSefazGProcRef.  # noqa: E501
        :type v_outro: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_outro is not None and v_outro < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_outro`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_outro = v_outro

    @property
    def ind_devolucao(self):
        """Gets the ind_devolucao of this NfcomSefazGProcRef.  # noqa: E501

        Indicador de devolução do valor do item.  * 1 - Devolução do valor do item  # noqa: E501

        :return: The ind_devolucao of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: int
        """
        return self._ind_devolucao

    @ind_devolucao.setter
    def ind_devolucao(self, ind_devolucao):
        """Sets the ind_devolucao of this NfcomSefazGProcRef.

        Indicador de devolução do valor do item.  * 1 - Devolução do valor do item  # noqa: E501

        :param ind_devolucao: The ind_devolucao of this NfcomSefazGProcRef.  # noqa: E501
        :type ind_devolucao: int
        """

        self._ind_devolucao = ind_devolucao

    @property
    def v_bc(self):
        """Gets the v_bc of this NfcomSefazGProcRef.  # noqa: E501

        Valor da BC do ICMS.  # noqa: E501

        :return: The v_bc of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_bc

    @v_bc.setter
    def v_bc(self, v_bc):
        """Sets the v_bc of this NfcomSefazGProcRef.

        Valor da BC do ICMS.  # noqa: E501

        :param v_bc: The v_bc of this NfcomSefazGProcRef.  # noqa: E501
        :type v_bc: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bc is not None and v_bc < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bc = v_bc

    @property
    def p_icms(self):
        """Gets the p_icms of this NfcomSefazGProcRef.  # noqa: E501

        Alíquota do ICMS.  # noqa: E501

        :return: The p_icms of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._p_icms

    @p_icms.setter
    def p_icms(self, p_icms):
        """Sets the p_icms of this NfcomSefazGProcRef.

        Alíquota do ICMS.  # noqa: E501

        :param p_icms: The p_icms of this NfcomSefazGProcRef.  # noqa: E501
        :type p_icms: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_icms is not None and p_icms < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_icms`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_icms = p_icms

    @property
    def v_icms(self):
        """Gets the v_icms of this NfcomSefazGProcRef.  # noqa: E501

        Valor do ICMS.  # noqa: E501

        :return: The v_icms of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_icms

    @v_icms.setter
    def v_icms(self, v_icms):
        """Sets the v_icms of this NfcomSefazGProcRef.

        Valor do ICMS.  # noqa: E501

        :param v_icms: The v_icms of this NfcomSefazGProcRef.  # noqa: E501
        :type v_icms: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms is not None and v_icms < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms = v_icms

    @property
    def v_pis(self):
        """Gets the v_pis of this NfcomSefazGProcRef.  # noqa: E501

        Valor do PIS.  # noqa: E501

        :return: The v_pis of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_pis

    @v_pis.setter
    def v_pis(self, v_pis):
        """Sets the v_pis of this NfcomSefazGProcRef.

        Valor do PIS.  # noqa: E501

        :param v_pis: The v_pis of this NfcomSefazGProcRef.  # noqa: E501
        :type v_pis: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_pis is not None and v_pis < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_pis`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_pis = v_pis

    @property
    def v_cofins(self):
        """Gets the v_cofins of this NfcomSefazGProcRef.  # noqa: E501

        Valor do COFINS.  # noqa: E501

        :return: The v_cofins of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_cofins

    @v_cofins.setter
    def v_cofins(self, v_cofins):
        """Sets the v_cofins of this NfcomSefazGProcRef.

        Valor do COFINS.  # noqa: E501

        :param v_cofins: The v_cofins of this NfcomSefazGProcRef.  # noqa: E501
        :type v_cofins: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_cofins is not None and v_cofins < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_cofins`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_cofins = v_cofins

    @property
    def v_fcp(self):
        """Gets the v_fcp of this NfcomSefazGProcRef.  # noqa: E501

        Valor do Fundo de Combate à Pobreza (FCP).  # noqa: E501

        :return: The v_fcp of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: float
        """
        return self._v_fcp

    @v_fcp.setter
    def v_fcp(self, v_fcp):
        """Sets the v_fcp of this NfcomSefazGProcRef.

        Valor do Fundo de Combate à Pobreza (FCP).  # noqa: E501

        :param v_fcp: The v_fcp of this NfcomSefazGProcRef.  # noqa: E501
        :type v_fcp: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcp is not None and v_fcp < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcp`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcp = v_fcp

    @property
    def g_proc(self):
        """Gets the g_proc of this NfcomSefazGProcRef.  # noqa: E501


        :return: The g_proc of this NfcomSefazGProcRef.  # noqa: E501
        :rtype: list[NfcomSefazGProc]
        """
        return self._g_proc

    @g_proc.setter
    def g_proc(self, g_proc):
        """Sets the g_proc of this NfcomSefazGProcRef.


        :param g_proc: The g_proc of this NfcomSefazGProcRef.  # noqa: E501
        :type g_proc: list[NfcomSefazGProc]
        """
        if self.local_vars_configuration.client_side_validation and g_proc is None:  # noqa: E501
            raise ValueError("Invalid value for `g_proc`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                g_proc is not None and len(g_proc) > 10):
            raise ValueError("Invalid value for `g_proc`, number of items must be less than or equal to `10`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                g_proc is not None and len(g_proc) < 1):
            raise ValueError("Invalid value for `g_proc`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._g_proc = g_proc

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfcomSefazGProcRef):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfcomSefazGProcRef):
            return True

        return self.to_dict() != other.to_dict()
