# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfcomSefazDet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'n_item': 'int',
        'ch_nf_com_ant': 'str',
        'n_item_ant': 'str',
        'ind_nf_com_ant_papel_fat_central': 'int',
        'prod': 'NfcomSefazProd',
        'imposto': 'NfcomSefazImposto',
        'g_proc_ref': 'NfcomSefazGProcRef',
        'g_ressarc': 'NfcomSefazGRessarc',
        'inf_ad_prod': 'str'
    }

    attribute_map = {
        'n_item': 'nItem',
        'ch_nf_com_ant': 'chNFComAnt',
        'n_item_ant': 'nItemAnt',
        'ind_nf_com_ant_papel_fat_central': 'indNFComAntPapelFatCentral',
        'prod': 'prod',
        'imposto': 'imposto',
        'g_proc_ref': 'gProcRef',
        'g_ressarc': 'gRessarc',
        'inf_ad_prod': 'infAdProd'
    }

    def __init__(self, n_item=None, ch_nf_com_ant=None, n_item_ant=None, ind_nf_com_ant_papel_fat_central=None, prod=None, imposto=None, g_proc_ref=None, g_ressarc=None, inf_ad_prod=None, local_vars_configuration=None):  # noqa: E501
        """NfcomSefazDet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._n_item = None
        self._ch_nf_com_ant = None
        self._n_item_ant = None
        self._ind_nf_com_ant_papel_fat_central = None
        self._prod = None
        self._imposto = None
        self._g_proc_ref = None
        self._g_ressarc = None
        self._inf_ad_prod = None
        self.discriminator = None

        self.n_item = n_item
        self.ch_nf_com_ant = ch_nf_com_ant
        self.n_item_ant = n_item_ant
        self.ind_nf_com_ant_papel_fat_central = ind_nf_com_ant_papel_fat_central
        self.prod = prod
        self.imposto = imposto
        if g_proc_ref is not None:
            self.g_proc_ref = g_proc_ref
        if g_ressarc is not None:
            self.g_ressarc = g_ressarc
        self.inf_ad_prod = inf_ad_prod

    @property
    def n_item(self):
        """Gets the n_item of this NfcomSefazDet.  # noqa: E501

        Número do item da NFCom.  # noqa: E501

        :return: The n_item of this NfcomSefazDet.  # noqa: E501
        :rtype: int
        """
        return self._n_item

    @n_item.setter
    def n_item(self, n_item):
        """Sets the n_item of this NfcomSefazDet.

        Número do item da NFCom.  # noqa: E501

        :param n_item: The n_item of this NfcomSefazDet.  # noqa: E501
        :type n_item: int
        """
        if (self.local_vars_configuration.client_side_validation and
                n_item is not None and n_item > 9999):  # noqa: E501
            raise ValueError("Invalid value for `n_item`, must be a value less than or equal to `9999`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                n_item is not None and n_item < 1):  # noqa: E501
            raise ValueError("Invalid value for `n_item`, must be a value greater than or equal to `1`")  # noqa: E501

        self._n_item = n_item

    @property
    def ch_nf_com_ant(self):
        """Gets the ch_nf_com_ant of this NfcomSefazDet.  # noqa: E501

        Chave de Acesso da NFCom anterior.  Informar chave de acesso de referencia anterior  TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.  # noqa: E501

        :return: The ch_nf_com_ant of this NfcomSefazDet.  # noqa: E501
        :rtype: str
        """
        return self._ch_nf_com_ant

    @ch_nf_com_ant.setter
    def ch_nf_com_ant(self, ch_nf_com_ant):
        """Sets the ch_nf_com_ant of this NfcomSefazDet.

        Chave de Acesso da NFCom anterior.  Informar chave de acesso de referencia anterior  TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.  # noqa: E501

        :param ch_nf_com_ant: The ch_nf_com_ant of this NfcomSefazDet.  # noqa: E501
        :type ch_nf_com_ant: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ch_nf_com_ant is not None and len(ch_nf_com_ant) > 44):
            raise ValueError("Invalid value for `ch_nf_com_ant`, length must be less than or equal to `44`")  # noqa: E501

        self._ch_nf_com_ant = ch_nf_com_ant

    @property
    def n_item_ant(self):
        """Gets the n_item_ant of this NfcomSefazDet.  # noqa: E501

        Número do item da NFCom anterior.  Informar nro do item da chave de acesso de referencia anterior  TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.  # noqa: E501

        :return: The n_item_ant of this NfcomSefazDet.  # noqa: E501
        :rtype: str
        """
        return self._n_item_ant

    @n_item_ant.setter
    def n_item_ant(self, n_item_ant):
        """Sets the n_item_ant of this NfcomSefazDet.

        Número do item da NFCom anterior.  Informar nro do item da chave de acesso de referencia anterior  TAG OPCIONAL, DEVE SER INFORMADA APENAS NOS CASOS PREVISTOS DE NOTA ANTERIOR REFERENCIADA.  # noqa: E501

        :param n_item_ant: The n_item_ant of this NfcomSefazDet.  # noqa: E501
        :type n_item_ant: str
        """

        self._n_item_ant = n_item_ant

    @property
    def ind_nf_com_ant_papel_fat_central(self):
        """Gets the ind_nf_com_ant_papel_fat_central of this NfcomSefazDet.  # noqa: E501

        Indicador de Nota anterior em papel no faturamento centralizado.  Informa que a NFCom Anterior de Faturamento centralizado não é eletrônica.  # noqa: E501

        :return: The ind_nf_com_ant_papel_fat_central of this NfcomSefazDet.  # noqa: E501
        :rtype: int
        """
        return self._ind_nf_com_ant_papel_fat_central

    @ind_nf_com_ant_papel_fat_central.setter
    def ind_nf_com_ant_papel_fat_central(self, ind_nf_com_ant_papel_fat_central):
        """Sets the ind_nf_com_ant_papel_fat_central of this NfcomSefazDet.

        Indicador de Nota anterior em papel no faturamento centralizado.  Informa que a NFCom Anterior de Faturamento centralizado não é eletrônica.  # noqa: E501

        :param ind_nf_com_ant_papel_fat_central: The ind_nf_com_ant_papel_fat_central of this NfcomSefazDet.  # noqa: E501
        :type ind_nf_com_ant_papel_fat_central: int
        """

        self._ind_nf_com_ant_papel_fat_central = ind_nf_com_ant_papel_fat_central

    @property
    def prod(self):
        """Gets the prod of this NfcomSefazDet.  # noqa: E501


        :return: The prod of this NfcomSefazDet.  # noqa: E501
        :rtype: NfcomSefazProd
        """
        return self._prod

    @prod.setter
    def prod(self, prod):
        """Sets the prod of this NfcomSefazDet.


        :param prod: The prod of this NfcomSefazDet.  # noqa: E501
        :type prod: NfcomSefazProd
        """
        if self.local_vars_configuration.client_side_validation and prod is None:  # noqa: E501
            raise ValueError("Invalid value for `prod`, must not be `None`")  # noqa: E501

        self._prod = prod

    @property
    def imposto(self):
        """Gets the imposto of this NfcomSefazDet.  # noqa: E501


        :return: The imposto of this NfcomSefazDet.  # noqa: E501
        :rtype: NfcomSefazImposto
        """
        return self._imposto

    @imposto.setter
    def imposto(self, imposto):
        """Sets the imposto of this NfcomSefazDet.


        :param imposto: The imposto of this NfcomSefazDet.  # noqa: E501
        :type imposto: NfcomSefazImposto
        """
        if self.local_vars_configuration.client_side_validation and imposto is None:  # noqa: E501
            raise ValueError("Invalid value for `imposto`, must not be `None`")  # noqa: E501

        self._imposto = imposto

    @property
    def g_proc_ref(self):
        """Gets the g_proc_ref of this NfcomSefazDet.  # noqa: E501


        :return: The g_proc_ref of this NfcomSefazDet.  # noqa: E501
        :rtype: NfcomSefazGProcRef
        """
        return self._g_proc_ref

    @g_proc_ref.setter
    def g_proc_ref(self, g_proc_ref):
        """Sets the g_proc_ref of this NfcomSefazDet.


        :param g_proc_ref: The g_proc_ref of this NfcomSefazDet.  # noqa: E501
        :type g_proc_ref: NfcomSefazGProcRef
        """

        self._g_proc_ref = g_proc_ref

    @property
    def g_ressarc(self):
        """Gets the g_ressarc of this NfcomSefazDet.  # noqa: E501


        :return: The g_ressarc of this NfcomSefazDet.  # noqa: E501
        :rtype: NfcomSefazGRessarc
        """
        return self._g_ressarc

    @g_ressarc.setter
    def g_ressarc(self, g_ressarc):
        """Sets the g_ressarc of this NfcomSefazDet.


        :param g_ressarc: The g_ressarc of this NfcomSefazDet.  # noqa: E501
        :type g_ressarc: NfcomSefazGRessarc
        """

        self._g_ressarc = g_ressarc

    @property
    def inf_ad_prod(self):
        """Gets the inf_ad_prod of this NfcomSefazDet.  # noqa: E501

        Informações adicionais do produto (norma referenciada, informações complementares, etc).  # noqa: E501

        :return: The inf_ad_prod of this NfcomSefazDet.  # noqa: E501
        :rtype: str
        """
        return self._inf_ad_prod

    @inf_ad_prod.setter
    def inf_ad_prod(self, inf_ad_prod):
        """Sets the inf_ad_prod of this NfcomSefazDet.

        Informações adicionais do produto (norma referenciada, informações complementares, etc).  # noqa: E501

        :param inf_ad_prod: The inf_ad_prod of this NfcomSefazDet.  # noqa: E501
        :type inf_ad_prod: str
        """
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_prod is not None and len(inf_ad_prod) > 500):
            raise ValueError("Invalid value for `inf_ad_prod`, length must be less than or equal to `500`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                inf_ad_prod is not None and len(inf_ad_prod) < 1):
            raise ValueError("Invalid value for `inf_ad_prod`, length must be greater than or equal to `1`")  # noqa: E501

        self._inf_ad_prod = inf_ad_prod

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfcomSefazDet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfcomSefazDet):
            return True

        return self.to_dict() != other.to_dict()
