# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfcomSefazICMSUFDest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'c_uf_dest': 'int',
        'v_bcuf_dest': 'float',
        'p_fcpuf_dest': 'float',
        'p_icmsuf_dest': 'float',
        'v_fcpuf_dest': 'float',
        'v_icmsuf_dest': 'float',
        'v_icmsuf_emi': 'float',
        'c_benef_uf_dest': 'str'
    }

    attribute_map = {
        'c_uf_dest': 'cUFDest',
        'v_bcuf_dest': 'vBCUFDest',
        'p_fcpuf_dest': 'pFCPUFDest',
        'p_icmsuf_dest': 'pICMSUFDest',
        'v_fcpuf_dest': 'vFCPUFDest',
        'v_icmsuf_dest': 'vICMSUFDest',
        'v_icmsuf_emi': 'vICMSUFEmi',
        'c_benef_uf_dest': 'cBenefUFDest'
    }

    def __init__(self, c_uf_dest=None, v_bcuf_dest=None, p_fcpuf_dest=None, p_icmsuf_dest=None, v_fcpuf_dest=None, v_icmsuf_dest=None, v_icmsuf_emi=None, c_benef_uf_dest=None, local_vars_configuration=None):  # noqa: E501
        """NfcomSefazICMSUFDest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._c_uf_dest = None
        self._v_bcuf_dest = None
        self._p_fcpuf_dest = None
        self._p_icmsuf_dest = None
        self._v_fcpuf_dest = None
        self._v_icmsuf_dest = None
        self._v_icmsuf_emi = None
        self._c_benef_uf_dest = None
        self.discriminator = None

        self.c_uf_dest = c_uf_dest
        self.v_bcuf_dest = v_bcuf_dest
        self.p_fcpuf_dest = p_fcpuf_dest
        self.p_icmsuf_dest = p_icmsuf_dest
        self.v_fcpuf_dest = v_fcpuf_dest
        self.v_icmsuf_dest = v_icmsuf_dest
        self.v_icmsuf_emi = v_icmsuf_emi
        self.c_benef_uf_dest = c_benef_uf_dest

    @property
    def c_uf_dest(self):
        """Gets the c_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501


        :return: The c_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: int
        """
        return self._c_uf_dest

    @c_uf_dest.setter
    def c_uf_dest(self, c_uf_dest):
        """Sets the c_uf_dest of this NfcomSefazICMSUFDest.


        :param c_uf_dest: The c_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type c_uf_dest: int
        """

        self._c_uf_dest = c_uf_dest

    @property
    def v_bcuf_dest(self):
        """Gets the v_bcuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Valor da BC do ICMS na UF de destino.  # noqa: E501

        :return: The v_bcuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_bcuf_dest

    @v_bcuf_dest.setter
    def v_bcuf_dest(self, v_bcuf_dest):
        """Sets the v_bcuf_dest of this NfcomSefazICMSUFDest.

        Valor da BC do ICMS na UF de destino.  # noqa: E501

        :param v_bcuf_dest: The v_bcuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type v_bcuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bcuf_dest is not None and v_bcuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bcuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bcuf_dest = v_bcuf_dest

    @property
    def p_fcpuf_dest(self):
        """Gets the p_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Percentual do ICMS relativo ao Fundo de Combate à pobreza (FCP) na UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.  # noqa: E501

        :return: The p_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_fcpuf_dest

    @p_fcpuf_dest.setter
    def p_fcpuf_dest(self, p_fcpuf_dest):
        """Sets the p_fcpuf_dest of this NfcomSefazICMSUFDest.

        Percentual do ICMS relativo ao Fundo de Combate à pobreza (FCP) na UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.  # noqa: E501

        :param p_fcpuf_dest: The p_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type p_fcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_fcpuf_dest is not None and p_fcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_fcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_fcpuf_dest = p_fcpuf_dest

    @property
    def p_icmsuf_dest(self):
        """Gets the p_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Alíquota interna da UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.  # noqa: E501

        :return: The p_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_icmsuf_dest

    @p_icmsuf_dest.setter
    def p_icmsuf_dest(self, p_icmsuf_dest):
        """Sets the p_icmsuf_dest of this NfcomSefazICMSUFDest.

        Alíquota interna da UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.  # noqa: E501

        :param p_icmsuf_dest: The p_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type p_icmsuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_icmsuf_dest is not None and p_icmsuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_icmsuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_icmsuf_dest = p_icmsuf_dest

    @property
    def v_fcpuf_dest(self):
        """Gets the v_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Valor do ICMS relativo ao Fundo de Combate á Pobreza (FCP) da UF de destino.  # noqa: E501

        :return: The v_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_fcpuf_dest

    @v_fcpuf_dest.setter
    def v_fcpuf_dest(self, v_fcpuf_dest):
        """Sets the v_fcpuf_dest of this NfcomSefazICMSUFDest.

        Valor do ICMS relativo ao Fundo de Combate á Pobreza (FCP) da UF de destino.  # noqa: E501

        :param v_fcpuf_dest: The v_fcpuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type v_fcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcpuf_dest is not None and v_fcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcpuf_dest = v_fcpuf_dest

    @property
    def v_icmsuf_dest(self):
        """Gets the v_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Valor do ICMS de partilha para a UF de destino.  # noqa: E501

        :return: The v_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_dest

    @v_icmsuf_dest.setter
    def v_icmsuf_dest(self, v_icmsuf_dest):
        """Sets the v_icmsuf_dest of this NfcomSefazICMSUFDest.

        Valor do ICMS de partilha para a UF de destino.  # noqa: E501

        :param v_icmsuf_dest: The v_icmsuf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type v_icmsuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_dest is not None and v_icmsuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_dest = v_icmsuf_dest

    @property
    def v_icmsuf_emi(self):
        """Gets the v_icmsuf_emi of this NfcomSefazICMSUFDest.  # noqa: E501

        Valor do ICMS de partilha para a UF de emissão.  # noqa: E501

        :return: The v_icmsuf_emi of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_emi

    @v_icmsuf_emi.setter
    def v_icmsuf_emi(self, v_icmsuf_emi):
        """Sets the v_icmsuf_emi of this NfcomSefazICMSUFDest.

        Valor do ICMS de partilha para a UF de emissão.  # noqa: E501

        :param v_icmsuf_emi: The v_icmsuf_emi of this NfcomSefazICMSUFDest.  # noqa: E501
        :type v_icmsuf_emi: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_emi is not None and v_icmsuf_emi < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_emi`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_emi = v_icmsuf_emi

    @property
    def c_benef_uf_dest(self):
        """Gets the c_benef_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501

        Código de Benefício Fiscal na UF destino aplicado ao item.  Código de Benefício Fiscal utilizado pela UF, aplicado ao  item.  # noqa: E501

        :return: The c_benef_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :rtype: str
        """
        return self._c_benef_uf_dest

    @c_benef_uf_dest.setter
    def c_benef_uf_dest(self, c_benef_uf_dest):
        """Sets the c_benef_uf_dest of this NfcomSefazICMSUFDest.

        Código de Benefício Fiscal na UF destino aplicado ao item.  Código de Benefício Fiscal utilizado pela UF, aplicado ao  item.  # noqa: E501

        :param c_benef_uf_dest: The c_benef_uf_dest of this NfcomSefazICMSUFDest.  # noqa: E501
        :type c_benef_uf_dest: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_benef_uf_dest is not None and len(c_benef_uf_dest) > 10):
            raise ValueError("Invalid value for `c_benef_uf_dest`, length must be less than or equal to `10`")  # noqa: E501

        self._c_benef_uf_dest = c_benef_uf_dest

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfcomSefazICMSUFDest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfcomSefazICMSUFDest):
            return True

        return self.to_dict() != other.to_dict()
