# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.9
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazNFref(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ref_nfe': 'str',
        'ref_nfe_sig': 'str',
        'ref_nf': 'NfeSefazRefNF',
        'ref_nfp': 'NfeSefazRefNFP',
        'ref_cte': 'str',
        'ref_ecf': 'NfeSefazRefECF'
    }

    attribute_map = {
        'ref_nfe': 'refNFe',
        'ref_nfe_sig': 'refNFeSig',
        'ref_nf': 'refNF',
        'ref_nfp': 'refNFP',
        'ref_cte': 'refCTe',
        'ref_ecf': 'refECF'
    }

    def __init__(self, ref_nfe=None, ref_nfe_sig=None, ref_nf=None, ref_nfp=None, ref_cte=None, ref_ecf=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazNFref - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._ref_nfe = None
        self._ref_nfe_sig = None
        self._ref_nf = None
        self._ref_nfp = None
        self._ref_cte = None
        self._ref_ecf = None
        self.discriminator = None

        self.ref_nfe = ref_nfe
        self.ref_nfe_sig = ref_nfe_sig
        if ref_nf is not None:
            self.ref_nf = ref_nf
        if ref_nfp is not None:
            self.ref_nfp = ref_nfp
        self.ref_cte = ref_cte
        if ref_ecf is not None:
            self.ref_ecf = ref_ecf

    @property
    def ref_nfe(self):
        """Gets the ref_nfe of this NfeSefazNFref.  # noqa: E501

        Chave de acesso das NF-e referenciadas. Chave de acesso compostas por Código da UF (tabela do IBGE) + AAMM da emissão + CNPJ do Emitente + modelo, série e número da NF-e Referenciada + Código Numérico + DV.  # noqa: E501

        :return: The ref_nfe of this NfeSefazNFref.  # noqa: E501
        :rtype: str
        """
        return self._ref_nfe

    @ref_nfe.setter
    def ref_nfe(self, ref_nfe):
        """Sets the ref_nfe of this NfeSefazNFref.

        Chave de acesso das NF-e referenciadas. Chave de acesso compostas por Código da UF (tabela do IBGE) + AAMM da emissão + CNPJ do Emitente + modelo, série e número da NF-e Referenciada + Código Numérico + DV.  # noqa: E501

        :param ref_nfe: The ref_nfe of this NfeSefazNFref.  # noqa: E501
        :type ref_nfe: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ref_nfe is not None and len(ref_nfe) > 44):
            raise ValueError("Invalid value for `ref_nfe`, length must be less than or equal to `44`")  # noqa: E501

        self._ref_nfe = ref_nfe

    @property
    def ref_nfe_sig(self):
        """Gets the ref_nfe_sig of this NfeSefazNFref.  # noqa: E501

        Referencia uma NF-e (modelo 55) emitida anteriormente pela sua Chave de Acesso com código numérico zerado, permitindo manter o sigilo da NF-e referenciada.  # noqa: E501

        :return: The ref_nfe_sig of this NfeSefazNFref.  # noqa: E501
        :rtype: str
        """
        return self._ref_nfe_sig

    @ref_nfe_sig.setter
    def ref_nfe_sig(self, ref_nfe_sig):
        """Sets the ref_nfe_sig of this NfeSefazNFref.

        Referencia uma NF-e (modelo 55) emitida anteriormente pela sua Chave de Acesso com código numérico zerado, permitindo manter o sigilo da NF-e referenciada.  # noqa: E501

        :param ref_nfe_sig: The ref_nfe_sig of this NfeSefazNFref.  # noqa: E501
        :type ref_nfe_sig: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ref_nfe_sig is not None and len(ref_nfe_sig) > 44):
            raise ValueError("Invalid value for `ref_nfe_sig`, length must be less than or equal to `44`")  # noqa: E501

        self._ref_nfe_sig = ref_nfe_sig

    @property
    def ref_nf(self):
        """Gets the ref_nf of this NfeSefazNFref.  # noqa: E501


        :return: The ref_nf of this NfeSefazNFref.  # noqa: E501
        :rtype: NfeSefazRefNF
        """
        return self._ref_nf

    @ref_nf.setter
    def ref_nf(self, ref_nf):
        """Sets the ref_nf of this NfeSefazNFref.


        :param ref_nf: The ref_nf of this NfeSefazNFref.  # noqa: E501
        :type ref_nf: NfeSefazRefNF
        """

        self._ref_nf = ref_nf

    @property
    def ref_nfp(self):
        """Gets the ref_nfp of this NfeSefazNFref.  # noqa: E501


        :return: The ref_nfp of this NfeSefazNFref.  # noqa: E501
        :rtype: NfeSefazRefNFP
        """
        return self._ref_nfp

    @ref_nfp.setter
    def ref_nfp(self, ref_nfp):
        """Sets the ref_nfp of this NfeSefazNFref.


        :param ref_nfp: The ref_nfp of this NfeSefazNFref.  # noqa: E501
        :type ref_nfp: NfeSefazRefNFP
        """

        self._ref_nfp = ref_nfp

    @property
    def ref_cte(self):
        """Gets the ref_cte of this NfeSefazNFref.  # noqa: E501

        Utilizar esta TAG para referenciar um CT-e emitido anteriormente, vinculada a NF-e atual.  # noqa: E501

        :return: The ref_cte of this NfeSefazNFref.  # noqa: E501
        :rtype: str
        """
        return self._ref_cte

    @ref_cte.setter
    def ref_cte(self, ref_cte):
        """Sets the ref_cte of this NfeSefazNFref.

        Utilizar esta TAG para referenciar um CT-e emitido anteriormente, vinculada a NF-e atual.  # noqa: E501

        :param ref_cte: The ref_cte of this NfeSefazNFref.  # noqa: E501
        :type ref_cte: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ref_cte is not None and len(ref_cte) > 44):
            raise ValueError("Invalid value for `ref_cte`, length must be less than or equal to `44`")  # noqa: E501

        self._ref_cte = ref_cte

    @property
    def ref_ecf(self):
        """Gets the ref_ecf of this NfeSefazNFref.  # noqa: E501


        :return: The ref_ecf of this NfeSefazNFref.  # noqa: E501
        :rtype: NfeSefazRefECF
        """
        return self._ref_ecf

    @ref_ecf.setter
    def ref_ecf(self, ref_ecf):
        """Sets the ref_ecf of this NfeSefazNFref.


        :param ref_ecf: The ref_ecf of this NfeSefazNFref.  # noqa: E501
        :type ref_ecf: NfeSefazRefECF
        """

        self._ref_ecf = ref_ecf

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazNFref):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazNFref):
            return True

        return self.to_dict() != other.to_dict()
