# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazGIBS(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'g_ibsuf': 'NfeSefazGIBSGIBSUF',
        'g_ibs_mun': 'NfeSefazGIBSGIBSMun',
        'v_ibs': 'float',
        'v_cred_pres': 'float',
        'v_cred_pres_cond_sus': 'float'
    }

    attribute_map = {
        'g_ibsuf': 'gIBSUF',
        'g_ibs_mun': 'gIBSMun',
        'v_ibs': 'vIBS',
        'v_cred_pres': 'vCredPres',
        'v_cred_pres_cond_sus': 'vCredPresCondSus'
    }

    def __init__(self, g_ibsuf=None, g_ibs_mun=None, v_ibs=None, v_cred_pres=None, v_cred_pres_cond_sus=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazGIBS - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._g_ibsuf = None
        self._g_ibs_mun = None
        self._v_ibs = None
        self._v_cred_pres = None
        self._v_cred_pres_cond_sus = None
        self.discriminator = None

        self.g_ibsuf = g_ibsuf
        self.g_ibs_mun = g_ibs_mun
        self.v_ibs = v_ibs
        self.v_cred_pres = v_cred_pres
        self.v_cred_pres_cond_sus = v_cred_pres_cond_sus

    @property
    def g_ibsuf(self):
        """Gets the g_ibsuf of this NfeSefazGIBS.  # noqa: E501


        :return: The g_ibsuf of this NfeSefazGIBS.  # noqa: E501
        :rtype: NfeSefazGIBSGIBSUF
        """
        return self._g_ibsuf

    @g_ibsuf.setter
    def g_ibsuf(self, g_ibsuf):
        """Sets the g_ibsuf of this NfeSefazGIBS.


        :param g_ibsuf: The g_ibsuf of this NfeSefazGIBS.  # noqa: E501
        :type g_ibsuf: NfeSefazGIBSGIBSUF
        """
        if self.local_vars_configuration.client_side_validation and g_ibsuf is None:  # noqa: E501
            raise ValueError("Invalid value for `g_ibsuf`, must not be `None`")  # noqa: E501

        self._g_ibsuf = g_ibsuf

    @property
    def g_ibs_mun(self):
        """Gets the g_ibs_mun of this NfeSefazGIBS.  # noqa: E501


        :return: The g_ibs_mun of this NfeSefazGIBS.  # noqa: E501
        :rtype: NfeSefazGIBSGIBSMun
        """
        return self._g_ibs_mun

    @g_ibs_mun.setter
    def g_ibs_mun(self, g_ibs_mun):
        """Sets the g_ibs_mun of this NfeSefazGIBS.


        :param g_ibs_mun: The g_ibs_mun of this NfeSefazGIBS.  # noqa: E501
        :type g_ibs_mun: NfeSefazGIBSGIBSMun
        """
        if self.local_vars_configuration.client_side_validation and g_ibs_mun is None:  # noqa: E501
            raise ValueError("Invalid value for `g_ibs_mun`, must not be `None`")  # noqa: E501

        self._g_ibs_mun = g_ibs_mun

    @property
    def v_ibs(self):
        """Gets the v_ibs of this NfeSefazGIBS.  # noqa: E501

        Valor total do IBS.  # noqa: E501

        :return: The v_ibs of this NfeSefazGIBS.  # noqa: E501
        :rtype: float
        """
        return self._v_ibs

    @v_ibs.setter
    def v_ibs(self, v_ibs):
        """Sets the v_ibs of this NfeSefazGIBS.

        Valor total do IBS.  # noqa: E501

        :param v_ibs: The v_ibs of this NfeSefazGIBS.  # noqa: E501
        :type v_ibs: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ibs is not None and v_ibs < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ibs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ibs = v_ibs

    @property
    def v_cred_pres(self):
        """Gets the v_cred_pres of this NfeSefazGIBS.  # noqa: E501

        Total do Crédito Presumido.  # noqa: E501

        :return: The v_cred_pres of this NfeSefazGIBS.  # noqa: E501
        :rtype: float
        """
        return self._v_cred_pres

    @v_cred_pres.setter
    def v_cred_pres(self, v_cred_pres):
        """Sets the v_cred_pres of this NfeSefazGIBS.

        Total do Crédito Presumido.  # noqa: E501

        :param v_cred_pres: The v_cred_pres of this NfeSefazGIBS.  # noqa: E501
        :type v_cred_pres: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_cred_pres is not None and v_cred_pres < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_cred_pres`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_cred_pres = v_cred_pres

    @property
    def v_cred_pres_cond_sus(self):
        """Gets the v_cred_pres_cond_sus of this NfeSefazGIBS.  # noqa: E501

        Total do Crédito Presumido Condição Suspensiva.  # noqa: E501

        :return: The v_cred_pres_cond_sus of this NfeSefazGIBS.  # noqa: E501
        :rtype: float
        """
        return self._v_cred_pres_cond_sus

    @v_cred_pres_cond_sus.setter
    def v_cred_pres_cond_sus(self, v_cred_pres_cond_sus):
        """Sets the v_cred_pres_cond_sus of this NfeSefazGIBS.

        Total do Crédito Presumido Condição Suspensiva.  # noqa: E501

        :param v_cred_pres_cond_sus: The v_cred_pres_cond_sus of this NfeSefazGIBS.  # noqa: E501
        :type v_cred_pres_cond_sus: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_cred_pres_cond_sus is not None and v_cred_pres_cond_sus < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_cred_pres_cond_sus`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_cred_pres_cond_sus = v_cred_pres_cond_sus

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazGIBS):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazGIBS):
            return True

        return self.to_dict() != other.to_dict()
