# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazICMSTot(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v_bc': 'float',
        'v_icms': 'float',
        'v_icms_deson': 'float',
        'v_fcpuf_dest': 'float',
        'v_icmsuf_dest': 'float',
        'v_icmsuf_remet': 'float',
        'v_fcp': 'float',
        'v_bcst': 'float',
        'v_st': 'float',
        'v_fcpst': 'float',
        'v_fcpst_ret': 'float',
        'q_bc_mono': 'float',
        'v_icms_mono': 'float',
        'q_bc_mono_reten': 'float',
        'v_icms_mono_reten': 'float',
        'q_bc_mono_ret': 'float',
        'v_icms_mono_ret': 'float',
        'v_prod': 'float',
        'v_frete': 'float',
        'v_seg': 'float',
        'v_desc': 'float',
        'v_ii': 'float',
        'v_ipi': 'float',
        'v_ipi_devol': 'float',
        'v_pis': 'float',
        'v_cofins': 'float',
        'v_outro': 'float',
        'v_nf': 'float',
        'v_tot_trib': 'float'
    }

    attribute_map = {
        'v_bc': 'vBC',
        'v_icms': 'vICMS',
        'v_icms_deson': 'vICMSDeson',
        'v_fcpuf_dest': 'vFCPUFDest',
        'v_icmsuf_dest': 'vICMSUFDest',
        'v_icmsuf_remet': 'vICMSUFRemet',
        'v_fcp': 'vFCP',
        'v_bcst': 'vBCST',
        'v_st': 'vST',
        'v_fcpst': 'vFCPST',
        'v_fcpst_ret': 'vFCPSTRet',
        'q_bc_mono': 'qBCMono',
        'v_icms_mono': 'vICMSMono',
        'q_bc_mono_reten': 'qBCMonoReten',
        'v_icms_mono_reten': 'vICMSMonoReten',
        'q_bc_mono_ret': 'qBCMonoRet',
        'v_icms_mono_ret': 'vICMSMonoRet',
        'v_prod': 'vProd',
        'v_frete': 'vFrete',
        'v_seg': 'vSeg',
        'v_desc': 'vDesc',
        'v_ii': 'vII',
        'v_ipi': 'vIPI',
        'v_ipi_devol': 'vIPIDevol',
        'v_pis': 'vPIS',
        'v_cofins': 'vCOFINS',
        'v_outro': 'vOutro',
        'v_nf': 'vNF',
        'v_tot_trib': 'vTotTrib'
    }

    def __init__(self, v_bc=None, v_icms=None, v_icms_deson=None, v_fcpuf_dest=None, v_icmsuf_dest=None, v_icmsuf_remet=None, v_fcp=None, v_bcst=None, v_st=None, v_fcpst=None, v_fcpst_ret=None, q_bc_mono=None, v_icms_mono=None, q_bc_mono_reten=None, v_icms_mono_reten=None, q_bc_mono_ret=None, v_icms_mono_ret=None, v_prod=None, v_frete=None, v_seg=None, v_desc=None, v_ii=None, v_ipi=None, v_ipi_devol=None, v_pis=None, v_cofins=None, v_outro=None, v_nf=None, v_tot_trib=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazICMSTot - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._v_bc = None
        self._v_icms = None
        self._v_icms_deson = None
        self._v_fcpuf_dest = None
        self._v_icmsuf_dest = None
        self._v_icmsuf_remet = None
        self._v_fcp = None
        self._v_bcst = None
        self._v_st = None
        self._v_fcpst = None
        self._v_fcpst_ret = None
        self._q_bc_mono = None
        self._v_icms_mono = None
        self._q_bc_mono_reten = None
        self._v_icms_mono_reten = None
        self._q_bc_mono_ret = None
        self._v_icms_mono_ret = None
        self._v_prod = None
        self._v_frete = None
        self._v_seg = None
        self._v_desc = None
        self._v_ii = None
        self._v_ipi = None
        self._v_ipi_devol = None
        self._v_pis = None
        self._v_cofins = None
        self._v_outro = None
        self._v_nf = None
        self._v_tot_trib = None
        self.discriminator = None

        self.v_bc = v_bc
        self.v_icms = v_icms
        self.v_icms_deson = v_icms_deson
        self.v_fcpuf_dest = v_fcpuf_dest
        self.v_icmsuf_dest = v_icmsuf_dest
        self.v_icmsuf_remet = v_icmsuf_remet
        self.v_fcp = v_fcp
        self.v_bcst = v_bcst
        self.v_st = v_st
        self.v_fcpst = v_fcpst
        self.v_fcpst_ret = v_fcpst_ret
        self.q_bc_mono = q_bc_mono
        self.v_icms_mono = v_icms_mono
        self.q_bc_mono_reten = q_bc_mono_reten
        self.v_icms_mono_reten = v_icms_mono_reten
        self.q_bc_mono_ret = q_bc_mono_ret
        self.v_icms_mono_ret = v_icms_mono_ret
        self.v_prod = v_prod
        self.v_frete = v_frete
        self.v_seg = v_seg
        self.v_desc = v_desc
        self.v_ii = v_ii
        self.v_ipi = v_ipi
        self.v_ipi_devol = v_ipi_devol
        self.v_pis = v_pis
        self.v_cofins = v_cofins
        self.v_outro = v_outro
        self.v_nf = v_nf
        self.v_tot_trib = v_tot_trib

    @property
    def v_bc(self):
        """Gets the v_bc of this NfeSefazICMSTot.  # noqa: E501

        BC do ICMS.  # noqa: E501

        :return: The v_bc of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_bc

    @v_bc.setter
    def v_bc(self, v_bc):
        """Sets the v_bc of this NfeSefazICMSTot.

        BC do ICMS.  # noqa: E501

        :param v_bc: The v_bc of this NfeSefazICMSTot.  # noqa: E501
        :type v_bc: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bc is not None and v_bc < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bc = v_bc

    @property
    def v_icms(self):
        """Gets the v_icms of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do ICMS.  # noqa: E501

        :return: The v_icms of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icms

    @v_icms.setter
    def v_icms(self, v_icms):
        """Sets the v_icms of this NfeSefazICMSTot.

        Valor Total do ICMS.  # noqa: E501

        :param v_icms: The v_icms of this NfeSefazICMSTot.  # noqa: E501
        :type v_icms: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms is not None and v_icms < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms = v_icms

    @property
    def v_icms_deson(self):
        """Gets the v_icms_deson of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do ICMS desonerado.  # noqa: E501

        :return: The v_icms_deson of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icms_deson

    @v_icms_deson.setter
    def v_icms_deson(self, v_icms_deson):
        """Sets the v_icms_deson of this NfeSefazICMSTot.

        Valor Total do ICMS desonerado.  # noqa: E501

        :param v_icms_deson: The v_icms_deson of this NfeSefazICMSTot.  # noqa: E501
        :type v_icms_deson: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms_deson is not None and v_icms_deson < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms_deson`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms_deson = v_icms_deson

    @property
    def v_fcpuf_dest(self):
        """Gets the v_fcpuf_dest of this NfeSefazICMSTot.  # noqa: E501

        Valor total do ICMS relativo ao Fundo de Combate à Pobreza (FCP) para a UF de destino.  # noqa: E501

        :return: The v_fcpuf_dest of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_fcpuf_dest

    @v_fcpuf_dest.setter
    def v_fcpuf_dest(self, v_fcpuf_dest):
        """Sets the v_fcpuf_dest of this NfeSefazICMSTot.

        Valor total do ICMS relativo ao Fundo de Combate à Pobreza (FCP) para a UF de destino.  # noqa: E501

        :param v_fcpuf_dest: The v_fcpuf_dest of this NfeSefazICMSTot.  # noqa: E501
        :type v_fcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcpuf_dest is not None and v_fcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcpuf_dest = v_fcpuf_dest

    @property
    def v_icmsuf_dest(self):
        """Gets the v_icmsuf_dest of this NfeSefazICMSTot.  # noqa: E501

        Valor total do ICMS de partilha para a UF do destinatário.  # noqa: E501

        :return: The v_icmsuf_dest of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_dest

    @v_icmsuf_dest.setter
    def v_icmsuf_dest(self, v_icmsuf_dest):
        """Sets the v_icmsuf_dest of this NfeSefazICMSTot.

        Valor total do ICMS de partilha para a UF do destinatário.  # noqa: E501

        :param v_icmsuf_dest: The v_icmsuf_dest of this NfeSefazICMSTot.  # noqa: E501
        :type v_icmsuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_dest is not None and v_icmsuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_dest = v_icmsuf_dest

    @property
    def v_icmsuf_remet(self):
        """Gets the v_icmsuf_remet of this NfeSefazICMSTot.  # noqa: E501

        Valor total do ICMS de partilha para a UF do remetente.  # noqa: E501

        :return: The v_icmsuf_remet of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_remet

    @v_icmsuf_remet.setter
    def v_icmsuf_remet(self, v_icmsuf_remet):
        """Sets the v_icmsuf_remet of this NfeSefazICMSTot.

        Valor total do ICMS de partilha para a UF do remetente.  # noqa: E501

        :param v_icmsuf_remet: The v_icmsuf_remet of this NfeSefazICMSTot.  # noqa: E501
        :type v_icmsuf_remet: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_remet is not None and v_icmsuf_remet < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_remet`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_remet = v_icmsuf_remet

    @property
    def v_fcp(self):
        """Gets the v_fcp of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do FCP (Fundo de Combate à Pobreza).  # noqa: E501

        :return: The v_fcp of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_fcp

    @v_fcp.setter
    def v_fcp(self, v_fcp):
        """Sets the v_fcp of this NfeSefazICMSTot.

        Valor Total do FCP (Fundo de Combate à Pobreza).  # noqa: E501

        :param v_fcp: The v_fcp of this NfeSefazICMSTot.  # noqa: E501
        :type v_fcp: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcp is not None and v_fcp < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcp`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcp = v_fcp

    @property
    def v_bcst(self):
        """Gets the v_bcst of this NfeSefazICMSTot.  # noqa: E501

        BC do ICMS ST.  # noqa: E501

        :return: The v_bcst of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_bcst

    @v_bcst.setter
    def v_bcst(self, v_bcst):
        """Sets the v_bcst of this NfeSefazICMSTot.

        BC do ICMS ST.  # noqa: E501

        :param v_bcst: The v_bcst of this NfeSefazICMSTot.  # noqa: E501
        :type v_bcst: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bcst is not None and v_bcst < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bcst`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bcst = v_bcst

    @property
    def v_st(self):
        """Gets the v_st of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do ICMS ST.  # noqa: E501

        :return: The v_st of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_st

    @v_st.setter
    def v_st(self, v_st):
        """Sets the v_st of this NfeSefazICMSTot.

        Valor Total do ICMS ST.  # noqa: E501

        :param v_st: The v_st of this NfeSefazICMSTot.  # noqa: E501
        :type v_st: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_st is not None and v_st < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_st`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_st = v_st

    @property
    def v_fcpst(self):
        """Gets the v_fcpst of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do FCP (Fundo de Combate à Pobreza) retido por substituição tributária.  # noqa: E501

        :return: The v_fcpst of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_fcpst

    @v_fcpst.setter
    def v_fcpst(self, v_fcpst):
        """Sets the v_fcpst of this NfeSefazICMSTot.

        Valor Total do FCP (Fundo de Combate à Pobreza) retido por substituição tributária.  # noqa: E501

        :param v_fcpst: The v_fcpst of this NfeSefazICMSTot.  # noqa: E501
        :type v_fcpst: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcpst is not None and v_fcpst < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcpst`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcpst = v_fcpst

    @property
    def v_fcpst_ret(self):
        """Gets the v_fcpst_ret of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do FCP (Fundo de Combate à Pobreza) retido anteriormente por substituição tributária.  # noqa: E501

        :return: The v_fcpst_ret of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_fcpst_ret

    @v_fcpst_ret.setter
    def v_fcpst_ret(self, v_fcpst_ret):
        """Sets the v_fcpst_ret of this NfeSefazICMSTot.

        Valor Total do FCP (Fundo de Combate à Pobreza) retido anteriormente por substituição tributária.  # noqa: E501

        :param v_fcpst_ret: The v_fcpst_ret of this NfeSefazICMSTot.  # noqa: E501
        :type v_fcpst_ret: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcpst_ret is not None and v_fcpst_ret < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcpst_ret`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcpst_ret = v_fcpst_ret

    @property
    def q_bc_mono(self):
        """Gets the q_bc_mono of this NfeSefazICMSTot.  # noqa: E501

        Valor total da quantidade tributada do ICMS monofásico próprio.  # noqa: E501

        :return: The q_bc_mono of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._q_bc_mono

    @q_bc_mono.setter
    def q_bc_mono(self, q_bc_mono):
        """Sets the q_bc_mono of this NfeSefazICMSTot.

        Valor total da quantidade tributada do ICMS monofásico próprio.  # noqa: E501

        :param q_bc_mono: The q_bc_mono of this NfeSefazICMSTot.  # noqa: E501
        :type q_bc_mono: float
        """
        if (self.local_vars_configuration.client_side_validation and
                q_bc_mono is not None and q_bc_mono < 0):  # noqa: E501
            raise ValueError("Invalid value for `q_bc_mono`, must be a value greater than or equal to `0`")  # noqa: E501

        self._q_bc_mono = q_bc_mono

    @property
    def v_icms_mono(self):
        """Gets the v_icms_mono of this NfeSefazICMSTot.  # noqa: E501

        Valor total do ICMS monofásico próprio.  # noqa: E501

        :return: The v_icms_mono of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icms_mono

    @v_icms_mono.setter
    def v_icms_mono(self, v_icms_mono):
        """Sets the v_icms_mono of this NfeSefazICMSTot.

        Valor total do ICMS monofásico próprio.  # noqa: E501

        :param v_icms_mono: The v_icms_mono of this NfeSefazICMSTot.  # noqa: E501
        :type v_icms_mono: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms_mono is not None and v_icms_mono < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms_mono`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms_mono = v_icms_mono

    @property
    def q_bc_mono_reten(self):
        """Gets the q_bc_mono_reten of this NfeSefazICMSTot.  # noqa: E501

        Valor total da quantidade tributada do ICMS monofásico sujeito a retenção.  # noqa: E501

        :return: The q_bc_mono_reten of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._q_bc_mono_reten

    @q_bc_mono_reten.setter
    def q_bc_mono_reten(self, q_bc_mono_reten):
        """Sets the q_bc_mono_reten of this NfeSefazICMSTot.

        Valor total da quantidade tributada do ICMS monofásico sujeito a retenção.  # noqa: E501

        :param q_bc_mono_reten: The q_bc_mono_reten of this NfeSefazICMSTot.  # noqa: E501
        :type q_bc_mono_reten: float
        """
        if (self.local_vars_configuration.client_side_validation and
                q_bc_mono_reten is not None and q_bc_mono_reten < 0):  # noqa: E501
            raise ValueError("Invalid value for `q_bc_mono_reten`, must be a value greater than or equal to `0`")  # noqa: E501

        self._q_bc_mono_reten = q_bc_mono_reten

    @property
    def v_icms_mono_reten(self):
        """Gets the v_icms_mono_reten of this NfeSefazICMSTot.  # noqa: E501

        Valor total do ICMS monofásico sujeito a retenção.  # noqa: E501

        :return: The v_icms_mono_reten of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icms_mono_reten

    @v_icms_mono_reten.setter
    def v_icms_mono_reten(self, v_icms_mono_reten):
        """Sets the v_icms_mono_reten of this NfeSefazICMSTot.

        Valor total do ICMS monofásico sujeito a retenção.  # noqa: E501

        :param v_icms_mono_reten: The v_icms_mono_reten of this NfeSefazICMSTot.  # noqa: E501
        :type v_icms_mono_reten: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms_mono_reten is not None and v_icms_mono_reten < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms_mono_reten`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms_mono_reten = v_icms_mono_reten

    @property
    def q_bc_mono_ret(self):
        """Gets the q_bc_mono_ret of this NfeSefazICMSTot.  # noqa: E501

        Valor total da quantidade tributada do ICMS monofásico retido anteriormente.  # noqa: E501

        :return: The q_bc_mono_ret of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._q_bc_mono_ret

    @q_bc_mono_ret.setter
    def q_bc_mono_ret(self, q_bc_mono_ret):
        """Sets the q_bc_mono_ret of this NfeSefazICMSTot.

        Valor total da quantidade tributada do ICMS monofásico retido anteriormente.  # noqa: E501

        :param q_bc_mono_ret: The q_bc_mono_ret of this NfeSefazICMSTot.  # noqa: E501
        :type q_bc_mono_ret: float
        """
        if (self.local_vars_configuration.client_side_validation and
                q_bc_mono_ret is not None and q_bc_mono_ret < 0):  # noqa: E501
            raise ValueError("Invalid value for `q_bc_mono_ret`, must be a value greater than or equal to `0`")  # noqa: E501

        self._q_bc_mono_ret = q_bc_mono_ret

    @property
    def v_icms_mono_ret(self):
        """Gets the v_icms_mono_ret of this NfeSefazICMSTot.  # noqa: E501

        Valor do ICMS monofásico retido anteriormente.  # noqa: E501

        :return: The v_icms_mono_ret of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_icms_mono_ret

    @v_icms_mono_ret.setter
    def v_icms_mono_ret(self, v_icms_mono_ret):
        """Sets the v_icms_mono_ret of this NfeSefazICMSTot.

        Valor do ICMS monofásico retido anteriormente.  # noqa: E501

        :param v_icms_mono_ret: The v_icms_mono_ret of this NfeSefazICMSTot.  # noqa: E501
        :type v_icms_mono_ret: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms_mono_ret is not None and v_icms_mono_ret < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms_mono_ret`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms_mono_ret = v_icms_mono_ret

    @property
    def v_prod(self):
        """Gets the v_prod of this NfeSefazICMSTot.  # noqa: E501

        Valor Total dos produtos e serviços.  # noqa: E501

        :return: The v_prod of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_prod

    @v_prod.setter
    def v_prod(self, v_prod):
        """Sets the v_prod of this NfeSefazICMSTot.

        Valor Total dos produtos e serviços.  # noqa: E501

        :param v_prod: The v_prod of this NfeSefazICMSTot.  # noqa: E501
        :type v_prod: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_prod is not None and v_prod < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_prod`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_prod = v_prod

    @property
    def v_frete(self):
        """Gets the v_frete of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do Frete.  # noqa: E501

        :return: The v_frete of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_frete

    @v_frete.setter
    def v_frete(self, v_frete):
        """Sets the v_frete of this NfeSefazICMSTot.

        Valor Total do Frete.  # noqa: E501

        :param v_frete: The v_frete of this NfeSefazICMSTot.  # noqa: E501
        :type v_frete: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_frete is not None and v_frete < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_frete`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_frete = v_frete

    @property
    def v_seg(self):
        """Gets the v_seg of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do Seguro.  # noqa: E501

        :return: The v_seg of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_seg

    @v_seg.setter
    def v_seg(self, v_seg):
        """Sets the v_seg of this NfeSefazICMSTot.

        Valor Total do Seguro.  # noqa: E501

        :param v_seg: The v_seg of this NfeSefazICMSTot.  # noqa: E501
        :type v_seg: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_seg is not None and v_seg < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_seg`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_seg = v_seg

    @property
    def v_desc(self):
        """Gets the v_desc of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do Desconto.  # noqa: E501

        :return: The v_desc of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_desc

    @v_desc.setter
    def v_desc(self, v_desc):
        """Sets the v_desc of this NfeSefazICMSTot.

        Valor Total do Desconto.  # noqa: E501

        :param v_desc: The v_desc of this NfeSefazICMSTot.  # noqa: E501
        :type v_desc: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc is not None and v_desc < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_desc = v_desc

    @property
    def v_ii(self):
        """Gets the v_ii of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do II.  # noqa: E501

        :return: The v_ii of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_ii

    @v_ii.setter
    def v_ii(self, v_ii):
        """Sets the v_ii of this NfeSefazICMSTot.

        Valor Total do II.  # noqa: E501

        :param v_ii: The v_ii of this NfeSefazICMSTot.  # noqa: E501
        :type v_ii: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ii is not None and v_ii < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ii`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ii = v_ii

    @property
    def v_ipi(self):
        """Gets the v_ipi of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do IPI.  # noqa: E501

        :return: The v_ipi of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_ipi

    @v_ipi.setter
    def v_ipi(self, v_ipi):
        """Sets the v_ipi of this NfeSefazICMSTot.

        Valor Total do IPI.  # noqa: E501

        :param v_ipi: The v_ipi of this NfeSefazICMSTot.  # noqa: E501
        :type v_ipi: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ipi is not None and v_ipi < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ipi`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ipi = v_ipi

    @property
    def v_ipi_devol(self):
        """Gets the v_ipi_devol of this NfeSefazICMSTot.  # noqa: E501

        Valor Total do IPI devolvido. Deve ser informado quando preenchido o Grupo Tributos Devolvidos na emissão de nota finNFe=4 (devolução) nas operações com não contribuintes do IPI. Corresponde ao total da soma dos campos id: UA04.  # noqa: E501

        :return: The v_ipi_devol of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_ipi_devol

    @v_ipi_devol.setter
    def v_ipi_devol(self, v_ipi_devol):
        """Sets the v_ipi_devol of this NfeSefazICMSTot.

        Valor Total do IPI devolvido. Deve ser informado quando preenchido o Grupo Tributos Devolvidos na emissão de nota finNFe=4 (devolução) nas operações com não contribuintes do IPI. Corresponde ao total da soma dos campos id: UA04.  # noqa: E501

        :param v_ipi_devol: The v_ipi_devol of this NfeSefazICMSTot.  # noqa: E501
        :type v_ipi_devol: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ipi_devol is not None and v_ipi_devol < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ipi_devol`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ipi_devol = v_ipi_devol

    @property
    def v_pis(self):
        """Gets the v_pis of this NfeSefazICMSTot.  # noqa: E501

        Valor do PIS.  # noqa: E501

        :return: The v_pis of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_pis

    @v_pis.setter
    def v_pis(self, v_pis):
        """Sets the v_pis of this NfeSefazICMSTot.

        Valor do PIS.  # noqa: E501

        :param v_pis: The v_pis of this NfeSefazICMSTot.  # noqa: E501
        :type v_pis: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_pis is not None and v_pis < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_pis`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_pis = v_pis

    @property
    def v_cofins(self):
        """Gets the v_cofins of this NfeSefazICMSTot.  # noqa: E501

        Valor do COFINS.  # noqa: E501

        :return: The v_cofins of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_cofins

    @v_cofins.setter
    def v_cofins(self, v_cofins):
        """Sets the v_cofins of this NfeSefazICMSTot.

        Valor do COFINS.  # noqa: E501

        :param v_cofins: The v_cofins of this NfeSefazICMSTot.  # noqa: E501
        :type v_cofins: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_cofins is not None and v_cofins < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_cofins`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_cofins = v_cofins

    @property
    def v_outro(self):
        """Gets the v_outro of this NfeSefazICMSTot.  # noqa: E501

        Outras Despesas acessórias.  # noqa: E501

        :return: The v_outro of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_outro

    @v_outro.setter
    def v_outro(self, v_outro):
        """Sets the v_outro of this NfeSefazICMSTot.

        Outras Despesas acessórias.  # noqa: E501

        :param v_outro: The v_outro of this NfeSefazICMSTot.  # noqa: E501
        :type v_outro: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_outro is not None and v_outro < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_outro`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_outro = v_outro

    @property
    def v_nf(self):
        """Gets the v_nf of this NfeSefazICMSTot.  # noqa: E501

        Valor Total da NF-e.  # noqa: E501

        :return: The v_nf of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_nf

    @v_nf.setter
    def v_nf(self, v_nf):
        """Sets the v_nf of this NfeSefazICMSTot.

        Valor Total da NF-e.  # noqa: E501

        :param v_nf: The v_nf of this NfeSefazICMSTot.  # noqa: E501
        :type v_nf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_nf is not None and v_nf < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_nf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_nf = v_nf

    @property
    def v_tot_trib(self):
        """Gets the v_tot_trib of this NfeSefazICMSTot.  # noqa: E501

        Valor estimado total de impostos federais, estaduais e municipais.  # noqa: E501

        :return: The v_tot_trib of this NfeSefazICMSTot.  # noqa: E501
        :rtype: float
        """
        return self._v_tot_trib

    @v_tot_trib.setter
    def v_tot_trib(self, v_tot_trib):
        """Sets the v_tot_trib of this NfeSefazICMSTot.

        Valor estimado total de impostos federais, estaduais e municipais.  # noqa: E501

        :param v_tot_trib: The v_tot_trib of this NfeSefazICMSTot.  # noqa: E501
        :type v_tot_trib: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_tot_trib is not None and v_tot_trib < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_tot_trib`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_tot_trib = v_tot_trib

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazICMSTot):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazICMSTot):
            return True

        return self.to_dict() != other.to_dict()
