# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazICMSUFDest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v_bcuf_dest': 'float',
        'v_bcfcpuf_dest': 'float',
        'p_fcpuf_dest': 'float',
        'p_icmsuf_dest': 'float',
        'p_icms_inter': 'float',
        'p_icms_inter_part': 'float',
        'v_fcpuf_dest': 'float',
        'v_icmsuf_dest': 'float',
        'v_icmsuf_remet': 'float'
    }

    attribute_map = {
        'v_bcuf_dest': 'vBCUFDest',
        'v_bcfcpuf_dest': 'vBCFCPUFDest',
        'p_fcpuf_dest': 'pFCPUFDest',
        'p_icmsuf_dest': 'pICMSUFDest',
        'p_icms_inter': 'pICMSInter',
        'p_icms_inter_part': 'pICMSInterPart',
        'v_fcpuf_dest': 'vFCPUFDest',
        'v_icmsuf_dest': 'vICMSUFDest',
        'v_icmsuf_remet': 'vICMSUFRemet'
    }

    def __init__(self, v_bcuf_dest=None, v_bcfcpuf_dest=None, p_fcpuf_dest=None, p_icmsuf_dest=None, p_icms_inter=None, p_icms_inter_part=None, v_fcpuf_dest=None, v_icmsuf_dest=None, v_icmsuf_remet=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazICMSUFDest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._v_bcuf_dest = None
        self._v_bcfcpuf_dest = None
        self._p_fcpuf_dest = None
        self._p_icmsuf_dest = None
        self._p_icms_inter = None
        self._p_icms_inter_part = None
        self._v_fcpuf_dest = None
        self._v_icmsuf_dest = None
        self._v_icmsuf_remet = None
        self.discriminator = None

        self.v_bcuf_dest = v_bcuf_dest
        self.v_bcfcpuf_dest = v_bcfcpuf_dest
        self.p_fcpuf_dest = p_fcpuf_dest
        self.p_icmsuf_dest = p_icmsuf_dest
        self.p_icms_inter = p_icms_inter
        self.p_icms_inter_part = p_icms_inter_part
        self.v_fcpuf_dest = v_fcpuf_dest
        self.v_icmsuf_dest = v_icmsuf_dest
        self.v_icmsuf_remet = v_icmsuf_remet

    @property
    def v_bcuf_dest(self):
        """Gets the v_bcuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Valor da Base de Cálculo do ICMS na UF do destinatário.  # noqa: E501

        :return: The v_bcuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_bcuf_dest

    @v_bcuf_dest.setter
    def v_bcuf_dest(self, v_bcuf_dest):
        """Sets the v_bcuf_dest of this NfeSefazICMSUFDest.

        Valor da Base de Cálculo do ICMS na UF do destinatário.  # noqa: E501

        :param v_bcuf_dest: The v_bcuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type v_bcuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bcuf_dest is not None and v_bcuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bcuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bcuf_dest = v_bcuf_dest

    @property
    def v_bcfcpuf_dest(self):
        """Gets the v_bcfcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Valor da Base de Cálculo do FCP na UF do destinatário.  # noqa: E501

        :return: The v_bcfcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_bcfcpuf_dest

    @v_bcfcpuf_dest.setter
    def v_bcfcpuf_dest(self, v_bcfcpuf_dest):
        """Sets the v_bcfcpuf_dest of this NfeSefazICMSUFDest.

        Valor da Base de Cálculo do FCP na UF do destinatário.  # noqa: E501

        :param v_bcfcpuf_dest: The v_bcfcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type v_bcfcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bcfcpuf_dest is not None and v_bcfcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bcfcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bcfcpuf_dest = v_bcfcpuf_dest

    @property
    def p_fcpuf_dest(self):
        """Gets the p_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Percentual adicional inserido na alíquota interna da UF de destino, relativo ao Fundo de Combate à Pobreza (FCP) naquela UF.  # noqa: E501

        :return: The p_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_fcpuf_dest

    @p_fcpuf_dest.setter
    def p_fcpuf_dest(self, p_fcpuf_dest):
        """Sets the p_fcpuf_dest of this NfeSefazICMSUFDest.

        Percentual adicional inserido na alíquota interna da UF de destino, relativo ao Fundo de Combate à Pobreza (FCP) naquela UF.  # noqa: E501

        :param p_fcpuf_dest: The p_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type p_fcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_fcpuf_dest is not None and p_fcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_fcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_fcpuf_dest = p_fcpuf_dest

    @property
    def p_icmsuf_dest(self):
        """Gets the p_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Alíquota adotada nas operações internas na UF do destinatário para o produto / mercadoria.  # noqa: E501

        :return: The p_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_icmsuf_dest

    @p_icmsuf_dest.setter
    def p_icmsuf_dest(self, p_icmsuf_dest):
        """Sets the p_icmsuf_dest of this NfeSefazICMSUFDest.

        Alíquota adotada nas operações internas na UF do destinatário para o produto / mercadoria.  # noqa: E501

        :param p_icmsuf_dest: The p_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type p_icmsuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_icmsuf_dest is not None and p_icmsuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_icmsuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_icmsuf_dest = p_icmsuf_dest

    @property
    def p_icms_inter(self):
        """Gets the p_icms_inter of this NfeSefazICMSUFDest.  # noqa: E501

        Alíquota interestadual das UF envolvidas:  * 4%% alíquota interestadual para produtos importados  * 7%% para os Estados de origem do Sul e Sudeste (exceto ES), destinado para os Estados do Norte e Nordeste  ou ES  * 12%% para os demais casos.  # noqa: E501

        :return: The p_icms_inter of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_icms_inter

    @p_icms_inter.setter
    def p_icms_inter(self, p_icms_inter):
        """Sets the p_icms_inter of this NfeSefazICMSUFDest.

        Alíquota interestadual das UF envolvidas:  * 4%% alíquota interestadual para produtos importados  * 7%% para os Estados de origem do Sul e Sudeste (exceto ES), destinado para os Estados do Norte e Nordeste  ou ES  * 12%% para os demais casos.  # noqa: E501

        :param p_icms_inter: The p_icms_inter of this NfeSefazICMSUFDest.  # noqa: E501
        :type p_icms_inter: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_icms_inter is not None and p_icms_inter < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_icms_inter`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_icms_inter = p_icms_inter

    @property
    def p_icms_inter_part(self):
        """Gets the p_icms_inter_part of this NfeSefazICMSUFDest.  # noqa: E501

        Percentual de partilha para a UF do destinatário:  * 40%% em 2016  * 60%% em 2017  * 80%% em 2018  * 100%% a partir de 2019.  # noqa: E501

        :return: The p_icms_inter_part of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._p_icms_inter_part

    @p_icms_inter_part.setter
    def p_icms_inter_part(self, p_icms_inter_part):
        """Sets the p_icms_inter_part of this NfeSefazICMSUFDest.

        Percentual de partilha para a UF do destinatário:  * 40%% em 2016  * 60%% em 2017  * 80%% em 2018  * 100%% a partir de 2019.  # noqa: E501

        :param p_icms_inter_part: The p_icms_inter_part of this NfeSefazICMSUFDest.  # noqa: E501
        :type p_icms_inter_part: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_icms_inter_part is not None and p_icms_inter_part < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_icms_inter_part`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_icms_inter_part = p_icms_inter_part

    @property
    def v_fcpuf_dest(self):
        """Gets the v_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Valor do ICMS relativo ao Fundo de Combate à Pobreza (FCP) da UF de destino.  # noqa: E501

        :return: The v_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_fcpuf_dest

    @v_fcpuf_dest.setter
    def v_fcpuf_dest(self, v_fcpuf_dest):
        """Sets the v_fcpuf_dest of this NfeSefazICMSUFDest.

        Valor do ICMS relativo ao Fundo de Combate à Pobreza (FCP) da UF de destino.  # noqa: E501

        :param v_fcpuf_dest: The v_fcpuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type v_fcpuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_fcpuf_dest is not None and v_fcpuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_fcpuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_fcpuf_dest = v_fcpuf_dest

    @property
    def v_icmsuf_dest(self):
        """Gets the v_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501

        Valor do ICMS de partilha para a UF do destinatário.  # noqa: E501

        :return: The v_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_dest

    @v_icmsuf_dest.setter
    def v_icmsuf_dest(self, v_icmsuf_dest):
        """Sets the v_icmsuf_dest of this NfeSefazICMSUFDest.

        Valor do ICMS de partilha para a UF do destinatário.  # noqa: E501

        :param v_icmsuf_dest: The v_icmsuf_dest of this NfeSefazICMSUFDest.  # noqa: E501
        :type v_icmsuf_dest: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_dest is not None and v_icmsuf_dest < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_dest`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_dest = v_icmsuf_dest

    @property
    def v_icmsuf_remet(self):
        """Gets the v_icmsuf_remet of this NfeSefazICMSUFDest.  # noqa: E501

        Valor do ICMS de partilha para a UF do remetente. Nota: A partir de 2019, este valor será zero.  # noqa: E501

        :return: The v_icmsuf_remet of this NfeSefazICMSUFDest.  # noqa: E501
        :rtype: float
        """
        return self._v_icmsuf_remet

    @v_icmsuf_remet.setter
    def v_icmsuf_remet(self, v_icmsuf_remet):
        """Sets the v_icmsuf_remet of this NfeSefazICMSUFDest.

        Valor do ICMS de partilha para a UF do remetente. Nota: A partir de 2019, este valor será zero.  # noqa: E501

        :param v_icmsuf_remet: The v_icmsuf_remet of this NfeSefazICMSUFDest.  # noqa: E501
        :type v_icmsuf_remet: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icmsuf_remet is not None and v_icmsuf_remet < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icmsuf_remet`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icmsuf_remet = v_icmsuf_remet

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazICMSUFDest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazICMSUFDest):
            return True

        return self.to_dict() != other.to_dict()
