# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazISSQN(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v_bc': 'float',
        'v_aliq': 'float',
        'v_issqn': 'float',
        'c_mun_fg': 'str',
        'c_list_serv': 'str',
        'v_deducao': 'float',
        'v_outro': 'float',
        'v_desc_incond': 'float',
        'v_desc_cond': 'float',
        'v_iss_ret': 'float',
        'ind_iss': 'int',
        'c_servico': 'str',
        'c_mun': 'str',
        'c_pais': 'str',
        'n_processo': 'str',
        'ind_incentivo': 'int'
    }

    attribute_map = {
        'v_bc': 'vBC',
        'v_aliq': 'vAliq',
        'v_issqn': 'vISSQN',
        'c_mun_fg': 'cMunFG',
        'c_list_serv': 'cListServ',
        'v_deducao': 'vDeducao',
        'v_outro': 'vOutro',
        'v_desc_incond': 'vDescIncond',
        'v_desc_cond': 'vDescCond',
        'v_iss_ret': 'vISSRet',
        'ind_iss': 'indISS',
        'c_servico': 'cServico',
        'c_mun': 'cMun',
        'c_pais': 'cPais',
        'n_processo': 'nProcesso',
        'ind_incentivo': 'indIncentivo'
    }

    def __init__(self, v_bc=None, v_aliq=None, v_issqn=None, c_mun_fg=None, c_list_serv=None, v_deducao=None, v_outro=None, v_desc_incond=None, v_desc_cond=None, v_iss_ret=None, ind_iss=None, c_servico=None, c_mun=None, c_pais=None, n_processo=None, ind_incentivo=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazISSQN - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._v_bc = None
        self._v_aliq = None
        self._v_issqn = None
        self._c_mun_fg = None
        self._c_list_serv = None
        self._v_deducao = None
        self._v_outro = None
        self._v_desc_incond = None
        self._v_desc_cond = None
        self._v_iss_ret = None
        self._ind_iss = None
        self._c_servico = None
        self._c_mun = None
        self._c_pais = None
        self._n_processo = None
        self._ind_incentivo = None
        self.discriminator = None

        self.v_bc = v_bc
        self.v_aliq = v_aliq
        self.v_issqn = v_issqn
        self.c_mun_fg = c_mun_fg
        self.c_list_serv = c_list_serv
        self.v_deducao = v_deducao
        self.v_outro = v_outro
        self.v_desc_incond = v_desc_incond
        self.v_desc_cond = v_desc_cond
        self.v_iss_ret = v_iss_ret
        self.ind_iss = ind_iss
        self.c_servico = c_servico
        self.c_mun = c_mun
        self.c_pais = c_pais
        self.n_processo = n_processo
        self.ind_incentivo = ind_incentivo

    @property
    def v_bc(self):
        """Gets the v_bc of this NfeSefazISSQN.  # noqa: E501

        Valor da BC do ISSQN.  # noqa: E501

        :return: The v_bc of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_bc

    @v_bc.setter
    def v_bc(self, v_bc):
        """Sets the v_bc of this NfeSefazISSQN.

        Valor da BC do ISSQN.  # noqa: E501

        :param v_bc: The v_bc of this NfeSefazISSQN.  # noqa: E501
        :type v_bc: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_bc is not None and v_bc < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_bc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_bc = v_bc

    @property
    def v_aliq(self):
        """Gets the v_aliq of this NfeSefazISSQN.  # noqa: E501

        Alíquota do ISSQN.  # noqa: E501

        :return: The v_aliq of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_aliq

    @v_aliq.setter
    def v_aliq(self, v_aliq):
        """Sets the v_aliq of this NfeSefazISSQN.

        Alíquota do ISSQN.  # noqa: E501

        :param v_aliq: The v_aliq of this NfeSefazISSQN.  # noqa: E501
        :type v_aliq: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_aliq is not None and v_aliq < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_aliq`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_aliq = v_aliq

    @property
    def v_issqn(self):
        """Gets the v_issqn of this NfeSefazISSQN.  # noqa: E501

        Valor da do ISSQN.  # noqa: E501

        :return: The v_issqn of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_issqn

    @v_issqn.setter
    def v_issqn(self, v_issqn):
        """Sets the v_issqn of this NfeSefazISSQN.

        Valor da do ISSQN.  # noqa: E501

        :param v_issqn: The v_issqn of this NfeSefazISSQN.  # noqa: E501
        :type v_issqn: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_issqn is not None and v_issqn < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_issqn`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_issqn = v_issqn

    @property
    def c_mun_fg(self):
        """Gets the c_mun_fg of this NfeSefazISSQN.  # noqa: E501

        Informar o município de ocorrência do fato gerador do ISSQN. Utilizar a Tabela do IBGE (Anexo VII - Tabela de UF, Município e País). “Atenção, não vincular com os campos B12, C10 ou E10” v2.0.  # noqa: E501

        :return: The c_mun_fg of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._c_mun_fg

    @c_mun_fg.setter
    def c_mun_fg(self, c_mun_fg):
        """Sets the c_mun_fg of this NfeSefazISSQN.

        Informar o município de ocorrência do fato gerador do ISSQN. Utilizar a Tabela do IBGE (Anexo VII - Tabela de UF, Município e País). “Atenção, não vincular com os campos B12, C10 ou E10” v2.0.  # noqa: E501

        :param c_mun_fg: The c_mun_fg of this NfeSefazISSQN.  # noqa: E501
        :type c_mun_fg: str
        """

        self._c_mun_fg = c_mun_fg

    @property
    def c_list_serv(self):
        """Gets the c_list_serv of this NfeSefazISSQN.  # noqa: E501

        Informar o Item da lista de serviços da LC 116/03 em que se classifica o serviço.  # noqa: E501

        :return: The c_list_serv of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._c_list_serv

    @c_list_serv.setter
    def c_list_serv(self, c_list_serv):
        """Sets the c_list_serv of this NfeSefazISSQN.

        Informar o Item da lista de serviços da LC 116/03 em que se classifica o serviço.  # noqa: E501

        :param c_list_serv: The c_list_serv of this NfeSefazISSQN.  # noqa: E501
        :type c_list_serv: str
        """

        self._c_list_serv = c_list_serv

    @property
    def v_deducao(self):
        """Gets the v_deducao of this NfeSefazISSQN.  # noqa: E501

        Valor dedução para redução da base de cálculo.  # noqa: E501

        :return: The v_deducao of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_deducao

    @v_deducao.setter
    def v_deducao(self, v_deducao):
        """Sets the v_deducao of this NfeSefazISSQN.

        Valor dedução para redução da base de cálculo.  # noqa: E501

        :param v_deducao: The v_deducao of this NfeSefazISSQN.  # noqa: E501
        :type v_deducao: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_deducao is not None and v_deducao <= 0):  # noqa: E501
            raise ValueError("Invalid value for `v_deducao`, must be a value greater than `0`")  # noqa: E501

        self._v_deducao = v_deducao

    @property
    def v_outro(self):
        """Gets the v_outro of this NfeSefazISSQN.  # noqa: E501

        Valor outras retenções.  # noqa: E501

        :return: The v_outro of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_outro

    @v_outro.setter
    def v_outro(self, v_outro):
        """Sets the v_outro of this NfeSefazISSQN.

        Valor outras retenções.  # noqa: E501

        :param v_outro: The v_outro of this NfeSefazISSQN.  # noqa: E501
        :type v_outro: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_outro is not None and v_outro <= 0):  # noqa: E501
            raise ValueError("Invalid value for `v_outro`, must be a value greater than `0`")  # noqa: E501

        self._v_outro = v_outro

    @property
    def v_desc_incond(self):
        """Gets the v_desc_incond of this NfeSefazISSQN.  # noqa: E501

        Valor desconto incondicionado.  # noqa: E501

        :return: The v_desc_incond of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_desc_incond

    @v_desc_incond.setter
    def v_desc_incond(self, v_desc_incond):
        """Sets the v_desc_incond of this NfeSefazISSQN.

        Valor desconto incondicionado.  # noqa: E501

        :param v_desc_incond: The v_desc_incond of this NfeSefazISSQN.  # noqa: E501
        :type v_desc_incond: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc_incond is not None and v_desc_incond <= 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc_incond`, must be a value greater than `0`")  # noqa: E501

        self._v_desc_incond = v_desc_incond

    @property
    def v_desc_cond(self):
        """Gets the v_desc_cond of this NfeSefazISSQN.  # noqa: E501

        Valor desconto condicionado.  # noqa: E501

        :return: The v_desc_cond of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_desc_cond

    @v_desc_cond.setter
    def v_desc_cond(self, v_desc_cond):
        """Sets the v_desc_cond of this NfeSefazISSQN.

        Valor desconto condicionado.  # noqa: E501

        :param v_desc_cond: The v_desc_cond of this NfeSefazISSQN.  # noqa: E501
        :type v_desc_cond: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc_cond is not None and v_desc_cond <= 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc_cond`, must be a value greater than `0`")  # noqa: E501

        self._v_desc_cond = v_desc_cond

    @property
    def v_iss_ret(self):
        """Gets the v_iss_ret of this NfeSefazISSQN.  # noqa: E501

        Valor Retenção ISS.  # noqa: E501

        :return: The v_iss_ret of this NfeSefazISSQN.  # noqa: E501
        :rtype: float
        """
        return self._v_iss_ret

    @v_iss_ret.setter
    def v_iss_ret(self, v_iss_ret):
        """Sets the v_iss_ret of this NfeSefazISSQN.

        Valor Retenção ISS.  # noqa: E501

        :param v_iss_ret: The v_iss_ret of this NfeSefazISSQN.  # noqa: E501
        :type v_iss_ret: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_iss_ret is not None and v_iss_ret <= 0):  # noqa: E501
            raise ValueError("Invalid value for `v_iss_ret`, must be a value greater than `0`")  # noqa: E501

        self._v_iss_ret = v_iss_ret

    @property
    def ind_iss(self):
        """Gets the ind_iss of this NfeSefazISSQN.  # noqa: E501

        Exibilidade do ISS:1-Exigível  * 2 - Não incidente  * 3 - Isenção  * 4 - Exportação  * 5 - Imunidade  * 6 - Exig.Susp. Judicial  * 7 - Exig.Susp. ADM  # noqa: E501

        :return: The ind_iss of this NfeSefazISSQN.  # noqa: E501
        :rtype: int
        """
        return self._ind_iss

    @ind_iss.setter
    def ind_iss(self, ind_iss):
        """Sets the ind_iss of this NfeSefazISSQN.

        Exibilidade do ISS:1-Exigível  * 2 - Não incidente  * 3 - Isenção  * 4 - Exportação  * 5 - Imunidade  * 6 - Exig.Susp. Judicial  * 7 - Exig.Susp. ADM  # noqa: E501

        :param ind_iss: The ind_iss of this NfeSefazISSQN.  # noqa: E501
        :type ind_iss: int
        """

        self._ind_iss = ind_iss

    @property
    def c_servico(self):
        """Gets the c_servico of this NfeSefazISSQN.  # noqa: E501

        Código do serviço prestado dentro do município.  # noqa: E501

        :return: The c_servico of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._c_servico

    @c_servico.setter
    def c_servico(self, c_servico):
        """Sets the c_servico of this NfeSefazISSQN.

        Código do serviço prestado dentro do município.  # noqa: E501

        :param c_servico: The c_servico of this NfeSefazISSQN.  # noqa: E501
        :type c_servico: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_servico is not None and len(c_servico) > 20):
            raise ValueError("Invalid value for `c_servico`, length must be less than or equal to `20`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_servico is not None and len(c_servico) < 1):
            raise ValueError("Invalid value for `c_servico`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_servico = c_servico

    @property
    def c_mun(self):
        """Gets the c_mun of this NfeSefazISSQN.  # noqa: E501

        Código do Município de Incidência do Imposto.  # noqa: E501

        :return: The c_mun of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._c_mun

    @c_mun.setter
    def c_mun(self, c_mun):
        """Sets the c_mun of this NfeSefazISSQN.

        Código do Município de Incidência do Imposto.  # noqa: E501

        :param c_mun: The c_mun of this NfeSefazISSQN.  # noqa: E501
        :type c_mun: str
        """

        self._c_mun = c_mun

    @property
    def c_pais(self):
        """Gets the c_pais of this NfeSefazISSQN.  # noqa: E501

        Código de Pais.  # noqa: E501

        :return: The c_pais of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._c_pais

    @c_pais.setter
    def c_pais(self, c_pais):
        """Sets the c_pais of this NfeSefazISSQN.

        Código de Pais.  # noqa: E501

        :param c_pais: The c_pais of this NfeSefazISSQN.  # noqa: E501
        :type c_pais: str
        """

        self._c_pais = c_pais

    @property
    def n_processo(self):
        """Gets the n_processo of this NfeSefazISSQN.  # noqa: E501

        Número do Processo administrativo ou judicial de suspenção do processo.  # noqa: E501

        :return: The n_processo of this NfeSefazISSQN.  # noqa: E501
        :rtype: str
        """
        return self._n_processo

    @n_processo.setter
    def n_processo(self, n_processo):
        """Sets the n_processo of this NfeSefazISSQN.

        Número do Processo administrativo ou judicial de suspenção do processo.  # noqa: E501

        :param n_processo: The n_processo of this NfeSefazISSQN.  # noqa: E501
        :type n_processo: str
        """
        if (self.local_vars_configuration.client_side_validation and
                n_processo is not None and len(n_processo) > 30):
            raise ValueError("Invalid value for `n_processo`, length must be less than or equal to `30`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                n_processo is not None and len(n_processo) < 1):
            raise ValueError("Invalid value for `n_processo`, length must be greater than or equal to `1`")  # noqa: E501

        self._n_processo = n_processo

    @property
    def ind_incentivo(self):
        """Gets the ind_incentivo of this NfeSefazISSQN.  # noqa: E501

        Indicador de Incentivo Fiscal. 1=Sim  * 2 - Não  # noqa: E501

        :return: The ind_incentivo of this NfeSefazISSQN.  # noqa: E501
        :rtype: int
        """
        return self._ind_incentivo

    @ind_incentivo.setter
    def ind_incentivo(self, ind_incentivo):
        """Sets the ind_incentivo of this NfeSefazISSQN.

        Indicador de Incentivo Fiscal. 1=Sim  * 2 - Não  # noqa: E501

        :param ind_incentivo: The ind_incentivo of this NfeSefazISSQN.  # noqa: E501
        :type ind_incentivo: int
        """

        self._ind_incentivo = ind_incentivo

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazISSQN):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazISSQN):
            return True

        return self.to_dict() != other.to_dict()
