# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazIpi(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cnpj_prod': 'str',
        'c_selo': 'str',
        'q_selo': 'int',
        'c_enq': 'str',
        'ipi_trib': 'NfeSefazIPITrib',
        'ipint': 'NfeSefazIPINT'
    }

    attribute_map = {
        'cnpj_prod': 'CNPJProd',
        'c_selo': 'cSelo',
        'q_selo': 'qSelo',
        'c_enq': 'cEnq',
        'ipi_trib': 'IPITrib',
        'ipint': 'IPINT'
    }

    def __init__(self, cnpj_prod=None, c_selo=None, q_selo=None, c_enq=None, ipi_trib=None, ipint=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazIpi - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cnpj_prod = None
        self._c_selo = None
        self._q_selo = None
        self._c_enq = None
        self._ipi_trib = None
        self._ipint = None
        self.discriminator = None

        self.cnpj_prod = cnpj_prod
        self.c_selo = c_selo
        self.q_selo = q_selo
        self.c_enq = c_enq
        if ipi_trib is not None:
            self.ipi_trib = ipi_trib
        if ipint is not None:
            self.ipint = ipint

    @property
    def cnpj_prod(self):
        """Gets the cnpj_prod of this NfeSefazIpi.  # noqa: E501

        CNPJ do produtor da mercadoria, quando diferente do emitente. Somente para os casos de exportação direta ou indireta.  # noqa: E501

        :return: The cnpj_prod of this NfeSefazIpi.  # noqa: E501
        :rtype: str
        """
        return self._cnpj_prod

    @cnpj_prod.setter
    def cnpj_prod(self, cnpj_prod):
        """Sets the cnpj_prod of this NfeSefazIpi.

        CNPJ do produtor da mercadoria, quando diferente do emitente. Somente para os casos de exportação direta ou indireta.  # noqa: E501

        :param cnpj_prod: The cnpj_prod of this NfeSefazIpi.  # noqa: E501
        :type cnpj_prod: str
        """
        if (self.local_vars_configuration.client_side_validation and
                cnpj_prod is not None and len(cnpj_prod) > 14):
            raise ValueError("Invalid value for `cnpj_prod`, length must be less than or equal to `14`")  # noqa: E501

        self._cnpj_prod = cnpj_prod

    @property
    def c_selo(self):
        """Gets the c_selo of this NfeSefazIpi.  # noqa: E501

        Código do selo de controle do IPI.  # noqa: E501

        :return: The c_selo of this NfeSefazIpi.  # noqa: E501
        :rtype: str
        """
        return self._c_selo

    @c_selo.setter
    def c_selo(self, c_selo):
        """Sets the c_selo of this NfeSefazIpi.

        Código do selo de controle do IPI.  # noqa: E501

        :param c_selo: The c_selo of this NfeSefazIpi.  # noqa: E501
        :type c_selo: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_selo is not None and len(c_selo) > 60):
            raise ValueError("Invalid value for `c_selo`, length must be less than or equal to `60`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_selo is not None and len(c_selo) < 1):
            raise ValueError("Invalid value for `c_selo`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_selo = c_selo

    @property
    def q_selo(self):
        """Gets the q_selo of this NfeSefazIpi.  # noqa: E501

        Quantidade de selo de controle do IPI.  # noqa: E501

        :return: The q_selo of this NfeSefazIpi.  # noqa: E501
        :rtype: int
        """
        return self._q_selo

    @q_selo.setter
    def q_selo(self, q_selo):
        """Sets the q_selo of this NfeSefazIpi.

        Quantidade de selo de controle do IPI.  # noqa: E501

        :param q_selo: The q_selo of this NfeSefazIpi.  # noqa: E501
        :type q_selo: int
        """

        self._q_selo = q_selo

    @property
    def c_enq(self):
        """Gets the c_enq of this NfeSefazIpi.  # noqa: E501

        Código de Enquadramento Legal do IPI (tabela a ser criada pela RFB).  # noqa: E501

        :return: The c_enq of this NfeSefazIpi.  # noqa: E501
        :rtype: str
        """
        return self._c_enq

    @c_enq.setter
    def c_enq(self, c_enq):
        """Sets the c_enq of this NfeSefazIpi.

        Código de Enquadramento Legal do IPI (tabela a ser criada pela RFB).  # noqa: E501

        :param c_enq: The c_enq of this NfeSefazIpi.  # noqa: E501
        :type c_enq: str
        """
        if (self.local_vars_configuration.client_side_validation and
                c_enq is not None and len(c_enq) > 3):
            raise ValueError("Invalid value for `c_enq`, length must be less than or equal to `3`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                c_enq is not None and len(c_enq) < 1):
            raise ValueError("Invalid value for `c_enq`, length must be greater than or equal to `1`")  # noqa: E501

        self._c_enq = c_enq

    @property
    def ipi_trib(self):
        """Gets the ipi_trib of this NfeSefazIpi.  # noqa: E501


        :return: The ipi_trib of this NfeSefazIpi.  # noqa: E501
        :rtype: NfeSefazIPITrib
        """
        return self._ipi_trib

    @ipi_trib.setter
    def ipi_trib(self, ipi_trib):
        """Sets the ipi_trib of this NfeSefazIpi.


        :param ipi_trib: The ipi_trib of this NfeSefazIpi.  # noqa: E501
        :type ipi_trib: NfeSefazIPITrib
        """

        self._ipi_trib = ipi_trib

    @property
    def ipint(self):
        """Gets the ipint of this NfeSefazIpi.  # noqa: E501


        :return: The ipint of this NfeSefazIpi.  # noqa: E501
        :rtype: NfeSefazIPINT
        """
        return self._ipint

    @ipint.setter
    def ipint(self, ipint):
        """Sets the ipint of this NfeSefazIpi.


        :param ipint: The ipint of this NfeSefazIpi.  # noqa: E501
        :type ipint: NfeSefazIPINT
        """

        self._ipint = ipint

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazIpi):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazIpi):
            return True

        return self.to_dict() != other.to_dict()
