# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazICMS02(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'orig': 'int',
        'cst': 'str',
        'q_bc_mono': 'float',
        'ad_rem_icms': 'float',
        'v_icms_mono': 'float'
    }

    attribute_map = {
        'orig': 'orig',
        'cst': 'CST',
        'q_bc_mono': 'qBCMono',
        'ad_rem_icms': 'adRemICMS',
        'v_icms_mono': 'vICMSMono'
    }

    def __init__(self, orig=None, cst=None, q_bc_mono=None, ad_rem_icms=None, v_icms_mono=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazICMS02 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._orig = None
        self._cst = None
        self._q_bc_mono = None
        self._ad_rem_icms = None
        self._v_icms_mono = None
        self.discriminator = None

        self.orig = orig
        self.cst = cst
        self.q_bc_mono = q_bc_mono
        self.ad_rem_icms = ad_rem_icms
        self.v_icms_mono = v_icms_mono

    @property
    def orig(self):
        """Gets the orig of this NfeSefazICMS02.  # noqa: E501

        Origem da mercadoria:  * 0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;  * 1 - Estrangeira - Importação direta, exceto a indicada no código 6;  * 2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;  * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%% e inferior ou igual a 70%%;  * 4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;  * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%%;  * 6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;  * 7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural;  * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%%.  # noqa: E501

        :return: The orig of this NfeSefazICMS02.  # noqa: E501
        :rtype: int
        """
        return self._orig

    @orig.setter
    def orig(self, orig):
        """Sets the orig of this NfeSefazICMS02.

        Origem da mercadoria:  * 0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8;  * 1 - Estrangeira - Importação direta, exceto a indicada no código 6;  * 2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7;  * 3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%% e inferior ou igual a 70%%;  * 4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes;  * 5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%%;  * 6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural;  * 7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural;  * 8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%%.  # noqa: E501

        :param orig: The orig of this NfeSefazICMS02.  # noqa: E501
        :type orig: int
        """

        self._orig = orig

    @property
    def cst(self):
        """Gets the cst of this NfeSefazICMS02.  # noqa: E501

        Tributção pelo ICMS  * 02 - Tributação monofásica própria sobre combustíveis  # noqa: E501

        :return: The cst of this NfeSefazICMS02.  # noqa: E501
        :rtype: str
        """
        return self._cst

    @cst.setter
    def cst(self, cst):
        """Sets the cst of this NfeSefazICMS02.

        Tributção pelo ICMS  * 02 - Tributação monofásica própria sobre combustíveis  # noqa: E501

        :param cst: The cst of this NfeSefazICMS02.  # noqa: E501
        :type cst: str
        """

        self._cst = cst

    @property
    def q_bc_mono(self):
        """Gets the q_bc_mono of this NfeSefazICMS02.  # noqa: E501

        Quantidade tributada.  # noqa: E501

        :return: The q_bc_mono of this NfeSefazICMS02.  # noqa: E501
        :rtype: float
        """
        return self._q_bc_mono

    @q_bc_mono.setter
    def q_bc_mono(self, q_bc_mono):
        """Sets the q_bc_mono of this NfeSefazICMS02.

        Quantidade tributada.  # noqa: E501

        :param q_bc_mono: The q_bc_mono of this NfeSefazICMS02.  # noqa: E501
        :type q_bc_mono: float
        """
        if (self.local_vars_configuration.client_side_validation and
                q_bc_mono is not None and q_bc_mono < 0):  # noqa: E501
            raise ValueError("Invalid value for `q_bc_mono`, must be a value greater than or equal to `0`")  # noqa: E501

        self._q_bc_mono = q_bc_mono

    @property
    def ad_rem_icms(self):
        """Gets the ad_rem_icms of this NfeSefazICMS02.  # noqa: E501

        Alíquota ad rem do imposto.  # noqa: E501

        :return: The ad_rem_icms of this NfeSefazICMS02.  # noqa: E501
        :rtype: float
        """
        return self._ad_rem_icms

    @ad_rem_icms.setter
    def ad_rem_icms(self, ad_rem_icms):
        """Sets the ad_rem_icms of this NfeSefazICMS02.

        Alíquota ad rem do imposto.  # noqa: E501

        :param ad_rem_icms: The ad_rem_icms of this NfeSefazICMS02.  # noqa: E501
        :type ad_rem_icms: float
        """
        if (self.local_vars_configuration.client_side_validation and
                ad_rem_icms is not None and ad_rem_icms < 0):  # noqa: E501
            raise ValueError("Invalid value for `ad_rem_icms`, must be a value greater than or equal to `0`")  # noqa: E501

        self._ad_rem_icms = ad_rem_icms

    @property
    def v_icms_mono(self):
        """Gets the v_icms_mono of this NfeSefazICMS02.  # noqa: E501

        Valor do ICMS própri.  # noqa: E501

        :return: The v_icms_mono of this NfeSefazICMS02.  # noqa: E501
        :rtype: float
        """
        return self._v_icms_mono

    @v_icms_mono.setter
    def v_icms_mono(self, v_icms_mono):
        """Sets the v_icms_mono of this NfeSefazICMS02.

        Valor do ICMS própri.  # noqa: E501

        :param v_icms_mono: The v_icms_mono of this NfeSefazICMS02.  # noqa: E501
        :type v_icms_mono: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_icms_mono is not None and v_icms_mono < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_icms_mono`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_icms_mono = v_icms_mono

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazICMS02):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazICMS02):
            return True

        return self.to_dict() != other.to_dict()
