# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.7
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class NfeSefazGMonoDif(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'p_dif_ibs': 'float',
        'v_ibs_mono_dif': 'float',
        'p_dif_cbs': 'float',
        'v_cbs_mono_dif': 'float'
    }

    attribute_map = {
        'p_dif_ibs': 'pDifIBS',
        'v_ibs_mono_dif': 'vIBSMonoDif',
        'p_dif_cbs': 'pDifCBS',
        'v_cbs_mono_dif': 'vCBSMonoDif'
    }

    def __init__(self, p_dif_ibs=None, v_ibs_mono_dif=None, p_dif_cbs=None, v_cbs_mono_dif=None, local_vars_configuration=None):  # noqa: E501
        """NfeSefazGMonoDif - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._p_dif_ibs = None
        self._v_ibs_mono_dif = None
        self._p_dif_cbs = None
        self._v_cbs_mono_dif = None
        self.discriminator = None

        self.p_dif_ibs = p_dif_ibs
        self.v_ibs_mono_dif = v_ibs_mono_dif
        self.p_dif_cbs = p_dif_cbs
        self.v_cbs_mono_dif = v_cbs_mono_dif

    @property
    def p_dif_ibs(self):
        """Gets the p_dif_ibs of this NfeSefazGMonoDif.  # noqa: E501

        Percentual do diferimento do imposto monofásico.  # noqa: E501

        :return: The p_dif_ibs of this NfeSefazGMonoDif.  # noqa: E501
        :rtype: float
        """
        return self._p_dif_ibs

    @p_dif_ibs.setter
    def p_dif_ibs(self, p_dif_ibs):
        """Sets the p_dif_ibs of this NfeSefazGMonoDif.

        Percentual do diferimento do imposto monofásico.  # noqa: E501

        :param p_dif_ibs: The p_dif_ibs of this NfeSefazGMonoDif.  # noqa: E501
        :type p_dif_ibs: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_dif_ibs is not None and p_dif_ibs < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_dif_ibs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_dif_ibs = p_dif_ibs

    @property
    def v_ibs_mono_dif(self):
        """Gets the v_ibs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501

        Valor do IBS monofásico diferido.  # noqa: E501

        :return: The v_ibs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501
        :rtype: float
        """
        return self._v_ibs_mono_dif

    @v_ibs_mono_dif.setter
    def v_ibs_mono_dif(self, v_ibs_mono_dif):
        """Sets the v_ibs_mono_dif of this NfeSefazGMonoDif.

        Valor do IBS monofásico diferido.  # noqa: E501

        :param v_ibs_mono_dif: The v_ibs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501
        :type v_ibs_mono_dif: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ibs_mono_dif is not None and v_ibs_mono_dif < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ibs_mono_dif`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ibs_mono_dif = v_ibs_mono_dif

    @property
    def p_dif_cbs(self):
        """Gets the p_dif_cbs of this NfeSefazGMonoDif.  # noqa: E501

        Percentual do diferimento do imposto monofásico.  # noqa: E501

        :return: The p_dif_cbs of this NfeSefazGMonoDif.  # noqa: E501
        :rtype: float
        """
        return self._p_dif_cbs

    @p_dif_cbs.setter
    def p_dif_cbs(self, p_dif_cbs):
        """Sets the p_dif_cbs of this NfeSefazGMonoDif.

        Percentual do diferimento do imposto monofásico.  # noqa: E501

        :param p_dif_cbs: The p_dif_cbs of this NfeSefazGMonoDif.  # noqa: E501
        :type p_dif_cbs: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_dif_cbs is not None and p_dif_cbs < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_dif_cbs`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_dif_cbs = p_dif_cbs

    @property
    def v_cbs_mono_dif(self):
        """Gets the v_cbs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501

        Valor da CBS monofásica diferida.  # noqa: E501

        :return: The v_cbs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501
        :rtype: float
        """
        return self._v_cbs_mono_dif

    @v_cbs_mono_dif.setter
    def v_cbs_mono_dif(self, v_cbs_mono_dif):
        """Sets the v_cbs_mono_dif of this NfeSefazGMonoDif.

        Valor da CBS monofásica diferida.  # noqa: E501

        :param v_cbs_mono_dif: The v_cbs_mono_dif of this NfeSefazGMonoDif.  # noqa: E501
        :type v_cbs_mono_dif: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_cbs_mono_dif is not None and v_cbs_mono_dif < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_cbs_mono_dif`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_cbs_mono_dif = v_cbs_mono_dif

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NfeSefazGMonoDif):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NfeSefazGMonoDif):
            return True

        return self.to_dict() != other.to_dict()
