# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.11
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class Nfse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'created_at': 'datetime',
        'status': 'str',
        'numero': 'str',
        'codigo_verificacao': 'str',
        'link_url': 'str',
        'data_emissao': 'datetime',
        'ambiente': 'str',
        'referencia': 'str',
        'dps': 'DPS',
        'cancelamento': 'NfseCancelamento',
        'mensagens': 'list[NfseMensagemRetorno]',
        'declaracao_prestacao_servico': 'Rps'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'created_at',
        'status': 'status',
        'numero': 'numero',
        'codigo_verificacao': 'codigo_verificacao',
        'link_url': 'link_url',
        'data_emissao': 'data_emissao',
        'ambiente': 'ambiente',
        'referencia': 'referencia',
        'dps': 'DPS',
        'cancelamento': 'cancelamento',
        'mensagens': 'mensagens',
        'declaracao_prestacao_servico': 'declaracao_prestacao_servico'
    }

    def __init__(self, id=None, created_at=None, status=None, numero=None, codigo_verificacao=None, link_url=None, data_emissao=None, ambiente=None, referencia=None, dps=None, cancelamento=None, mensagens=None, declaracao_prestacao_servico=None, local_vars_configuration=None):  # noqa: E501
        """Nfse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._created_at = None
        self._status = None
        self._numero = None
        self._codigo_verificacao = None
        self._link_url = None
        self._data_emissao = None
        self._ambiente = None
        self._referencia = None
        self._dps = None
        self._cancelamento = None
        self._mensagens = None
        self._declaracao_prestacao_servico = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if status is not None:
            self.status = status
        if numero is not None:
            self.numero = numero
        if codigo_verificacao is not None:
            self.codigo_verificacao = codigo_verificacao
        if link_url is not None:
            self.link_url = link_url
        self.data_emissao = data_emissao
        if ambiente is not None:
            self.ambiente = ambiente
        if referencia is not None:
            self.referencia = referencia
        if dps is not None:
            self.dps = dps
        if cancelamento is not None:
            self.cancelamento = cancelamento
        if mensagens is not None:
            self.mensagens = mensagens
        if declaracao_prestacao_servico is not None:
            self.declaracao_prestacao_servico = declaracao_prestacao_servico

    @property
    def id(self):
        """Gets the id of this Nfse.  # noqa: E501

        ID único da nota gerado automaticamente pela API.  # noqa: E501

        :return: The id of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Nfse.

        ID único da nota gerado automaticamente pela API.  # noqa: E501

        :param id: The id of this Nfse.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this Nfse.  # noqa: E501


        :return: The created_at of this Nfse.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Nfse.


        :param created_at: The created_at of this Nfse.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def status(self):
        """Gets the status of this Nfse.  # noqa: E501


        :return: The status of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Nfse.


        :param status: The status of this Nfse.  # noqa: E501
        :type status: str
        """
        allowed_values = ["processando", "autorizada", "negada", "cancelada", "substituida", "erro"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def numero(self):
        """Gets the numero of this Nfse.  # noqa: E501


        :return: The numero of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._numero

    @numero.setter
    def numero(self, numero):
        """Sets the numero of this Nfse.


        :param numero: The numero of this Nfse.  # noqa: E501
        :type numero: str
        """

        self._numero = numero

    @property
    def codigo_verificacao(self):
        """Gets the codigo_verificacao of this Nfse.  # noqa: E501


        :return: The codigo_verificacao of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._codigo_verificacao

    @codigo_verificacao.setter
    def codigo_verificacao(self, codigo_verificacao):
        """Sets the codigo_verificacao of this Nfse.


        :param codigo_verificacao: The codigo_verificacao of this Nfse.  # noqa: E501
        :type codigo_verificacao: str
        """

        self._codigo_verificacao = codigo_verificacao

    @property
    def link_url(self):
        """Gets the link_url of this Nfse.  # noqa: E501


        :return: The link_url of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._link_url

    @link_url.setter
    def link_url(self, link_url):
        """Sets the link_url of this Nfse.


        :param link_url: The link_url of this Nfse.  # noqa: E501
        :type link_url: str
        """

        self._link_url = link_url

    @property
    def data_emissao(self):
        """Gets the data_emissao of this Nfse.  # noqa: E501


        :return: The data_emissao of this Nfse.  # noqa: E501
        :rtype: datetime
        """
        return self._data_emissao

    @data_emissao.setter
    def data_emissao(self, data_emissao):
        """Sets the data_emissao of this Nfse.


        :param data_emissao: The data_emissao of this Nfse.  # noqa: E501
        :type data_emissao: datetime
        """

        self._data_emissao = data_emissao

    @property
    def ambiente(self):
        """Gets the ambiente of this Nfse.  # noqa: E501


        :return: The ambiente of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._ambiente

    @ambiente.setter
    def ambiente(self, ambiente):
        """Sets the ambiente of this Nfse.


        :param ambiente: The ambiente of this Nfse.  # noqa: E501
        :type ambiente: str
        """
        allowed_values = ["homologacao", "producao"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and ambiente not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `ambiente` ({0}), must be one of {1}"  # noqa: E501
                .format(ambiente, allowed_values)
            )

        self._ambiente = ambiente

    @property
    def referencia(self):
        """Gets the referencia of this Nfse.  # noqa: E501


        :return: The referencia of this Nfse.  # noqa: E501
        :rtype: str
        """
        return self._referencia

    @referencia.setter
    def referencia(self, referencia):
        """Sets the referencia of this Nfse.


        :param referencia: The referencia of this Nfse.  # noqa: E501
        :type referencia: str
        """

        self._referencia = referencia

    @property
    def dps(self):
        """Gets the dps of this Nfse.  # noqa: E501


        :return: The dps of this Nfse.  # noqa: E501
        :rtype: DPS
        """
        return self._dps

    @dps.setter
    def dps(self, dps):
        """Sets the dps of this Nfse.


        :param dps: The dps of this Nfse.  # noqa: E501
        :type dps: DPS
        """

        self._dps = dps

    @property
    def cancelamento(self):
        """Gets the cancelamento of this Nfse.  # noqa: E501


        :return: The cancelamento of this Nfse.  # noqa: E501
        :rtype: NfseCancelamento
        """
        return self._cancelamento

    @cancelamento.setter
    def cancelamento(self, cancelamento):
        """Sets the cancelamento of this Nfse.


        :param cancelamento: The cancelamento of this Nfse.  # noqa: E501
        :type cancelamento: NfseCancelamento
        """

        self._cancelamento = cancelamento

    @property
    def mensagens(self):
        """Gets the mensagens of this Nfse.  # noqa: E501


        :return: The mensagens of this Nfse.  # noqa: E501
        :rtype: list[NfseMensagemRetorno]
        """
        return self._mensagens

    @mensagens.setter
    def mensagens(self, mensagens):
        """Sets the mensagens of this Nfse.


        :param mensagens: The mensagens of this Nfse.  # noqa: E501
        :type mensagens: list[NfseMensagemRetorno]
        """

        self._mensagens = mensagens

    @property
    def declaracao_prestacao_servico(self):
        """Gets the declaracao_prestacao_servico of this Nfse.  # noqa: E501


        :return: The declaracao_prestacao_servico of this Nfse.  # noqa: E501
        :rtype: Rps
        """
        return self._declaracao_prestacao_servico

    @declaracao_prestacao_servico.setter
    def declaracao_prestacao_servico(self, declaracao_prestacao_servico):
        """Sets the declaracao_prestacao_servico of this Nfse.


        :param declaracao_prestacao_servico: The declaracao_prestacao_servico of this Nfse.  # noqa: E501
        :type declaracao_prestacao_servico: Rps
        """

        self._declaracao_prestacao_servico = declaracao_prestacao_servico

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Nfse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Nfse):
            return True

        return self.to_dict() != other.to_dict()
