# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class RpsLote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'created_at': 'datetime',
        'status': 'str',
        'numero': 'str',
        'ambiente': 'str',
        'referencia': 'str',
        'notas': 'list[Nfse]'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'created_at',
        'status': 'status',
        'numero': 'numero',
        'ambiente': 'ambiente',
        'referencia': 'referencia',
        'notas': 'notas'
    }

    def __init__(self, id=None, created_at=None, status=None, numero=None, ambiente=None, referencia=None, notas=None, local_vars_configuration=None):  # noqa: E501
        """RpsLote - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._created_at = None
        self._status = None
        self._numero = None
        self._ambiente = None
        self._referencia = None
        self._notas = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if status is not None:
            self.status = status
        if numero is not None:
            self.numero = numero
        if ambiente is not None:
            self.ambiente = ambiente
        if referencia is not None:
            self.referencia = referencia
        if notas is not None:
            self.notas = notas

    @property
    def id(self):
        """Gets the id of this RpsLote.  # noqa: E501

        ID único do lote gerado automaticamente pela API.  # noqa: E501

        :return: The id of this RpsLote.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RpsLote.

        ID único do lote gerado automaticamente pela API.  # noqa: E501

        :param id: The id of this RpsLote.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this RpsLote.  # noqa: E501


        :return: The created_at of this RpsLote.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this RpsLote.


        :param created_at: The created_at of this RpsLote.  # noqa: E501
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def status(self):
        """Gets the status of this RpsLote.  # noqa: E501


        :return: The status of this RpsLote.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RpsLote.


        :param status: The status of this RpsLote.  # noqa: E501
        :type status: str
        """
        allowed_values = ["novo", "fila_envio", "fila_consulta", "processado", "erro"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def numero(self):
        """Gets the numero of this RpsLote.  # noqa: E501


        :return: The numero of this RpsLote.  # noqa: E501
        :rtype: str
        """
        return self._numero

    @numero.setter
    def numero(self, numero):
        """Sets the numero of this RpsLote.


        :param numero: The numero of this RpsLote.  # noqa: E501
        :type numero: str
        """

        self._numero = numero

    @property
    def ambiente(self):
        """Gets the ambiente of this RpsLote.  # noqa: E501


        :return: The ambiente of this RpsLote.  # noqa: E501
        :rtype: str
        """
        return self._ambiente

    @ambiente.setter
    def ambiente(self, ambiente):
        """Sets the ambiente of this RpsLote.


        :param ambiente: The ambiente of this RpsLote.  # noqa: E501
        :type ambiente: str
        """
        allowed_values = ["homologacao", "producao"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and ambiente not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `ambiente` ({0}), must be one of {1}"  # noqa: E501
                .format(ambiente, allowed_values)
            )

        self._ambiente = ambiente

    @property
    def referencia(self):
        """Gets the referencia of this RpsLote.  # noqa: E501


        :return: The referencia of this RpsLote.  # noqa: E501
        :rtype: str
        """
        return self._referencia

    @referencia.setter
    def referencia(self, referencia):
        """Sets the referencia of this RpsLote.


        :param referencia: The referencia of this RpsLote.  # noqa: E501
        :type referencia: str
        """

        self._referencia = referencia

    @property
    def notas(self):
        """Gets the notas of this RpsLote.  # noqa: E501


        :return: The notas of this RpsLote.  # noqa: E501
        :rtype: list[Nfse]
        """
        return self._notas

    @notas.setter
    def notas(self, notas):
        """Sets the notas of this RpsLote.


        :param notas: The notas of this RpsLote.  # noqa: E501
        :type notas: list[Nfse]
        """

        self._notas = notas

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RpsLote):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RpsLote):
            return True

        return self.to_dict() != other.to_dict()
