# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.12
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class RTCInfoTributosAbrasfUF(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'p_ibsuf': 'float',
        'p_red_aliq_uf': 'float',
        'p_aliq_efet_uf': 'float',
        'v_ibsuf': 'float'
    }

    attribute_map = {
        'p_ibsuf': 'pIBSUF',
        'p_red_aliq_uf': 'pRedAliqUF',
        'p_aliq_efet_uf': 'pAliqEfetUF',
        'v_ibsuf': 'vIBSUF'
    }

    def __init__(self, p_ibsuf=None, p_red_aliq_uf=None, p_aliq_efet_uf=None, v_ibsuf=None, local_vars_configuration=None):  # noqa: E501
        """RTCInfoTributosAbrasfUF - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._p_ibsuf = None
        self._p_red_aliq_uf = None
        self._p_aliq_efet_uf = None
        self._v_ibsuf = None
        self.discriminator = None

        self.p_ibsuf = p_ibsuf
        self.p_red_aliq_uf = p_red_aliq_uf
        self.p_aliq_efet_uf = p_aliq_efet_uf
        self.v_ibsuf = v_ibsuf

    @property
    def p_ibsuf(self):
        """Gets the p_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501

        Alíquota da UF para IBS.  # noqa: E501

        :return: The p_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :rtype: float
        """
        return self._p_ibsuf

    @p_ibsuf.setter
    def p_ibsuf(self, p_ibsuf):
        """Sets the p_ibsuf of this RTCInfoTributosAbrasfUF.

        Alíquota da UF para IBS.  # noqa: E501

        :param p_ibsuf: The p_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :type p_ibsuf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_ibsuf is not None and p_ibsuf < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_ibsuf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_ibsuf = p_ibsuf

    @property
    def p_red_aliq_uf(self):
        """Gets the p_red_aliq_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501

        Percentual de redução de alíquota estadual.  # noqa: E501

        :return: The p_red_aliq_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :rtype: float
        """
        return self._p_red_aliq_uf

    @p_red_aliq_uf.setter
    def p_red_aliq_uf(self, p_red_aliq_uf):
        """Sets the p_red_aliq_uf of this RTCInfoTributosAbrasfUF.

        Percentual de redução de alíquota estadual.  # noqa: E501

        :param p_red_aliq_uf: The p_red_aliq_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :type p_red_aliq_uf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_red_aliq_uf is not None and p_red_aliq_uf < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_red_aliq_uf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_red_aliq_uf = p_red_aliq_uf

    @property
    def p_aliq_efet_uf(self):
        """Gets the p_aliq_efet_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501

        Alíquota efetiva do IBS estadual.  pAliqEfetUF = pIBSUF x (1 - pRedAliqUF) x (1 - pRedutor)  # noqa: E501

        :return: The p_aliq_efet_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :rtype: float
        """
        return self._p_aliq_efet_uf

    @p_aliq_efet_uf.setter
    def p_aliq_efet_uf(self, p_aliq_efet_uf):
        """Sets the p_aliq_efet_uf of this RTCInfoTributosAbrasfUF.

        Alíquota efetiva do IBS estadual.  pAliqEfetUF = pIBSUF x (1 - pRedAliqUF) x (1 - pRedutor)  # noqa: E501

        :param p_aliq_efet_uf: The p_aliq_efet_uf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :type p_aliq_efet_uf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_aliq_efet_uf is not None and p_aliq_efet_uf < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_aliq_efet_uf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_aliq_efet_uf = p_aliq_efet_uf

    @property
    def v_ibsuf(self):
        """Gets the v_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501

        Valor do IBS estadual (R$).  vIBSUF = vBC x (pIBSUF ou pAliqEfetUF)  # noqa: E501

        :return: The v_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :rtype: float
        """
        return self._v_ibsuf

    @v_ibsuf.setter
    def v_ibsuf(self, v_ibsuf):
        """Sets the v_ibsuf of this RTCInfoTributosAbrasfUF.

        Valor do IBS estadual (R$).  vIBSUF = vBC x (pIBSUF ou pAliqEfetUF)  # noqa: E501

        :param v_ibsuf: The v_ibsuf of this RTCInfoTributosAbrasfUF.  # noqa: E501
        :type v_ibsuf: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_ibsuf is not None and v_ibsuf < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_ibsuf`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_ibsuf = v_ibsuf

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RTCInfoTributosAbrasfUF):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RTCInfoTributosAbrasfUF):
            return True

        return self.to_dict() != other.to_dict()
