# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class RTCInfoTributosSitClas(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cst': 'str',
        'c_class_trib': 'str',
        'c_cred_pres': 'str',
        'g_trib_regular': 'RTCInfoTributosTribRegular',
        'g_dif': 'RTCInfoTributosDif'
    }

    attribute_map = {
        'cst': 'CST',
        'c_class_trib': 'cClassTrib',
        'c_cred_pres': 'cCredPres',
        'g_trib_regular': 'gTribRegular',
        'g_dif': 'gDif'
    }

    def __init__(self, cst=None, c_class_trib=None, c_cred_pres=None, g_trib_regular=None, g_dif=None, local_vars_configuration=None):  # noqa: E501
        """RTCInfoTributosSitClas - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cst = None
        self._c_class_trib = None
        self._c_cred_pres = None
        self._g_trib_regular = None
        self._g_dif = None
        self.discriminator = None

        self.cst = cst
        self.c_class_trib = c_class_trib
        self.c_cred_pres = c_cred_pres
        if g_trib_regular is not None:
            self.g_trib_regular = g_trib_regular
        if g_dif is not None:
            self.g_dif = g_dif

    @property
    def cst(self):
        """Gets the cst of this RTCInfoTributosSitClas.  # noqa: E501

        Código de Situação Tributária do IBS e da CBS.  # noqa: E501

        :return: The cst of this RTCInfoTributosSitClas.  # noqa: E501
        :rtype: str
        """
        return self._cst

    @cst.setter
    def cst(self, cst):
        """Sets the cst of this RTCInfoTributosSitClas.

        Código de Situação Tributária do IBS e da CBS.  # noqa: E501

        :param cst: The cst of this RTCInfoTributosSitClas.  # noqa: E501
        :type cst: str
        """

        self._cst = cst

    @property
    def c_class_trib(self):
        """Gets the c_class_trib of this RTCInfoTributosSitClas.  # noqa: E501

        Código de Classificação Tributária do IBS e da CBS.  # noqa: E501

        :return: The c_class_trib of this RTCInfoTributosSitClas.  # noqa: E501
        :rtype: str
        """
        return self._c_class_trib

    @c_class_trib.setter
    def c_class_trib(self, c_class_trib):
        """Sets the c_class_trib of this RTCInfoTributosSitClas.

        Código de Classificação Tributária do IBS e da CBS.  # noqa: E501

        :param c_class_trib: The c_class_trib of this RTCInfoTributosSitClas.  # noqa: E501
        :type c_class_trib: str
        """

        self._c_class_trib = c_class_trib

    @property
    def c_cred_pres(self):
        """Gets the c_cred_pres of this RTCInfoTributosSitClas.  # noqa: E501

        Código e Classificação do Crédito Presumido: IBS e CBS.  # noqa: E501

        :return: The c_cred_pres of this RTCInfoTributosSitClas.  # noqa: E501
        :rtype: str
        """
        return self._c_cred_pres

    @c_cred_pres.setter
    def c_cred_pres(self, c_cred_pres):
        """Sets the c_cred_pres of this RTCInfoTributosSitClas.

        Código e Classificação do Crédito Presumido: IBS e CBS.  # noqa: E501

        :param c_cred_pres: The c_cred_pres of this RTCInfoTributosSitClas.  # noqa: E501
        :type c_cred_pres: str
        """

        self._c_cred_pres = c_cred_pres

    @property
    def g_trib_regular(self):
        """Gets the g_trib_regular of this RTCInfoTributosSitClas.  # noqa: E501


        :return: The g_trib_regular of this RTCInfoTributosSitClas.  # noqa: E501
        :rtype: RTCInfoTributosTribRegular
        """
        return self._g_trib_regular

    @g_trib_regular.setter
    def g_trib_regular(self, g_trib_regular):
        """Sets the g_trib_regular of this RTCInfoTributosSitClas.


        :param g_trib_regular: The g_trib_regular of this RTCInfoTributosSitClas.  # noqa: E501
        :type g_trib_regular: RTCInfoTributosTribRegular
        """

        self._g_trib_regular = g_trib_regular

    @property
    def g_dif(self):
        """Gets the g_dif of this RTCInfoTributosSitClas.  # noqa: E501


        :return: The g_dif of this RTCInfoTributosSitClas.  # noqa: E501
        :rtype: RTCInfoTributosDif
        """
        return self._g_dif

    @g_dif.setter
    def g_dif(self, g_dif):
        """Sets the g_dif of this RTCInfoTributosSitClas.


        :param g_dif: The g_dif of this RTCInfoTributosSitClas.  # noqa: E501
        :type g_dif: RTCInfoTributosDif
        """

        self._g_dif = g_dif

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RTCInfoTributosSitClas):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RTCInfoTributosSitClas):
            return True

        return self.to_dict() != other.to_dict()
