# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.8
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class TribTotalPercent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'p_tot_trib_fed': 'float',
        'p_tot_trib_est': 'float',
        'p_tot_trib_mun': 'float'
    }

    attribute_map = {
        'p_tot_trib_fed': 'pTotTribFed',
        'p_tot_trib_est': 'pTotTribEst',
        'p_tot_trib_mun': 'pTotTribMun'
    }

    def __init__(self, p_tot_trib_fed=None, p_tot_trib_est=None, p_tot_trib_mun=None, local_vars_configuration=None):  # noqa: E501
        """TribTotalPercent - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._p_tot_trib_fed = None
        self._p_tot_trib_est = None
        self._p_tot_trib_mun = None
        self.discriminator = None

        self.p_tot_trib_fed = p_tot_trib_fed
        self.p_tot_trib_est = p_tot_trib_est
        self.p_tot_trib_mun = p_tot_trib_mun

    @property
    def p_tot_trib_fed(self):
        """Gets the p_tot_trib_fed of this TribTotalPercent.  # noqa: E501

        Valor percentual total aproximado dos tributos federais (%%).  # noqa: E501

        :return: The p_tot_trib_fed of this TribTotalPercent.  # noqa: E501
        :rtype: float
        """
        return self._p_tot_trib_fed

    @p_tot_trib_fed.setter
    def p_tot_trib_fed(self, p_tot_trib_fed):
        """Sets the p_tot_trib_fed of this TribTotalPercent.

        Valor percentual total aproximado dos tributos federais (%%).  # noqa: E501

        :param p_tot_trib_fed: The p_tot_trib_fed of this TribTotalPercent.  # noqa: E501
        :type p_tot_trib_fed: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_tot_trib_fed is not None and p_tot_trib_fed < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_tot_trib_fed`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_tot_trib_fed = p_tot_trib_fed

    @property
    def p_tot_trib_est(self):
        """Gets the p_tot_trib_est of this TribTotalPercent.  # noqa: E501

        Valor percentual total aproximado dos tributos estaduais (%%).  # noqa: E501

        :return: The p_tot_trib_est of this TribTotalPercent.  # noqa: E501
        :rtype: float
        """
        return self._p_tot_trib_est

    @p_tot_trib_est.setter
    def p_tot_trib_est(self, p_tot_trib_est):
        """Sets the p_tot_trib_est of this TribTotalPercent.

        Valor percentual total aproximado dos tributos estaduais (%%).  # noqa: E501

        :param p_tot_trib_est: The p_tot_trib_est of this TribTotalPercent.  # noqa: E501
        :type p_tot_trib_est: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_tot_trib_est is not None and p_tot_trib_est < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_tot_trib_est`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_tot_trib_est = p_tot_trib_est

    @property
    def p_tot_trib_mun(self):
        """Gets the p_tot_trib_mun of this TribTotalPercent.  # noqa: E501

        Valor percentual total aproximado dos tributos municipais (%%).  # noqa: E501

        :return: The p_tot_trib_mun of this TribTotalPercent.  # noqa: E501
        :rtype: float
        """
        return self._p_tot_trib_mun

    @p_tot_trib_mun.setter
    def p_tot_trib_mun(self, p_tot_trib_mun):
        """Sets the p_tot_trib_mun of this TribTotalPercent.

        Valor percentual total aproximado dos tributos municipais (%%).  # noqa: E501

        :param p_tot_trib_mun: The p_tot_trib_mun of this TribTotalPercent.  # noqa: E501
        :type p_tot_trib_mun: float
        """
        if (self.local_vars_configuration.client_side_validation and
                p_tot_trib_mun is not None and p_tot_trib_mun < 0):  # noqa: E501
            raise ValueError("Invalid value for `p_tot_trib_mun`, must be a value greater than or equal to `0`")  # noqa: E501

        self._p_tot_trib_mun = p_tot_trib_mun

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TribTotalPercent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TribTotalPercent):
            return True

        return self.to_dict() != other.to_dict()
