# coding: utf-8

"""
    ACBr API

    API para automação comercial e documentos fiscais.    **Autenticação**  Esta API usa OAuth 2.0 no fluxo `client_credentials`.    **Ambientes disponíveis**  - Produção: `https://prod.acbr.api.br`  - Homologação: `https://hom.acbr.api.br`  - Autenticação para ambos os ambientes: `https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Endpoint para obter o token**  - `POST https://auth.acbr.api.br/realms/ACBrAPI/protocol/openid-connect/token`    **Content-Type**  - `application/x-www-form-urlencoded`    **Parâmetros do corpo**  - `grant_type=client_credentials`  - `client_id=SEU_CLIENT_ID`  - `client_secret=SEU_CLIENT_SECRET`  - `scope=empresa nfe nfse`    **Exemplo de corpo**  - `grant_type=client_credentials&client_id=SEU_CLIENT_ID&client_secret=SEU_CLIENT_SECRET&scope=empresa%20nfe`    **Uso do token nas requisições**  - `Authorization: Bearer SEU_ACCESS_TOKEN`  # noqa: E501

    The version of the OpenAPI document: 3.1.10
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from acbrapi_sdk.configuration import Configuration


class VDescCondIncond(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'v_desc_incond': 'float',
        'v_desc_cond': 'float'
    }

    attribute_map = {
        'v_desc_incond': 'vDescIncond',
        'v_desc_cond': 'vDescCond'
    }

    def __init__(self, v_desc_incond=None, v_desc_cond=None, local_vars_configuration=None):  # noqa: E501
        """VDescCondIncond - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._v_desc_incond = None
        self._v_desc_cond = None
        self.discriminator = None

        self.v_desc_incond = v_desc_incond
        self.v_desc_cond = v_desc_cond

    @property
    def v_desc_incond(self):
        """Gets the v_desc_incond of this VDescCondIncond.  # noqa: E501

        Valor monetário do desconto incondicionado (R$).  # noqa: E501

        :return: The v_desc_incond of this VDescCondIncond.  # noqa: E501
        :rtype: float
        """
        return self._v_desc_incond

    @v_desc_incond.setter
    def v_desc_incond(self, v_desc_incond):
        """Sets the v_desc_incond of this VDescCondIncond.

        Valor monetário do desconto incondicionado (R$).  # noqa: E501

        :param v_desc_incond: The v_desc_incond of this VDescCondIncond.  # noqa: E501
        :type v_desc_incond: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc_incond is not None and v_desc_incond < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc_incond`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_desc_incond = v_desc_incond

    @property
    def v_desc_cond(self):
        """Gets the v_desc_cond of this VDescCondIncond.  # noqa: E501

        Valor monetário do desconto condicionado (R$).  # noqa: E501

        :return: The v_desc_cond of this VDescCondIncond.  # noqa: E501
        :rtype: float
        """
        return self._v_desc_cond

    @v_desc_cond.setter
    def v_desc_cond(self, v_desc_cond):
        """Sets the v_desc_cond of this VDescCondIncond.

        Valor monetário do desconto condicionado (R$).  # noqa: E501

        :param v_desc_cond: The v_desc_cond of this VDescCondIncond.  # noqa: E501
        :type v_desc_cond: float
        """
        if (self.local_vars_configuration.client_side_validation and
                v_desc_cond is not None and v_desc_cond < 0):  # noqa: E501
            raise ValueError("Invalid value for `v_desc_cond`, must be a value greater than or equal to `0`")  # noqa: E501

        self._v_desc_cond = v_desc_cond

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VDescCondIncond):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VDescCondIncond):
            return True

        return self.to_dict() != other.to_dict()
